
-- EL OJO DE LA ETERNIDAD --

-- Malygos --
UPDATE `creature_text_locale` SET `CreatureID`='28859', `GroupID`='0', `ID`='0', `Locale`='esES', `text`='¡Seres inferiores, inmiscuyéndose aquí! ¡Es una lástima que vuestro exceso de valor no compense vuestra estupidez!' WHERE (`CreatureID`='28859') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28859', `GroupID`='0', `ID`='1', `Locale`='esES', `text`='Nadie excepto el Vuelo Azul es bienvenido aquí. ¿Tal vez vengáis de parte de Alexstrasza? ¡Bueno, entonces, os ha enviado a vuestra muerte!' WHERE (`CreatureID`='28859') AND (`GroupID`='0') AND (`ID`='1');
UPDATE `creature_text_locale` SET `CreatureID`='28859', `GroupID`='0', `ID`='2', `Locale`='esES', `text`='¿Qué esperábais lograr? Apareciendo descaradamente en mis dominios... y empleando magia... ¿contra MI?' WHERE (`CreatureID`='28859') AND (`GroupID`='0') AND (`ID`='2');
UPDATE `creature_text_locale` SET `CreatureID`='28859', `GroupID`='0', `ID`='3', `Locale`='esES', `text`='Aquí dentro no tengo límites. Las reglas de vuestra realidad no se aplican aquí. En este reino, ¡yo tengo el control!' WHERE (`CreatureID`='28859') AND (`GroupID`='0') AND (`ID`='3');
UPDATE `creature_text_locale` SET `CreatureID`='28859', `GroupID`='0', `ID`='4', `Locale`='esES', `text`='Os doy una oportunidad. Prométeme fidelidad, y tal vez no os mate por vuestra insolencia.' WHERE (`CreatureID`='28859') AND (`GroupID`='0') AND (`ID`='4');
UPDATE `creature_text_locale` SET `CreatureID`='28859', `GroupID`='1', `ID`='0', `Locale`='esES', `text`='Habéis agotado mi paciencia. ¡Me desharé de vosotros!' WHERE (`CreatureID`='28859') AND (`GroupID`='1') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28859', `GroupID`='2', `ID`='0', `Locale`='esES', `text`='¡No lo conseguiréis mientras me quede aliento!' WHERE (`CreatureID`='28859') AND (`GroupID`='2') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28859', `GroupID`='3', `ID`='0', `Locale`='esES', `text`='¡Al fin te ha alcanzado tu estupidez!' WHERE (`CreatureID`='28859') AND (`GroupID`='3') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28859', `GroupID`='3', `ID`='1', `Locale`='esES', `text`='Más artefactos que confiscar.' WHERE (`CreatureID`='28859') AND (`GroupID`='3') AND (`ID`='1');
UPDATE `creature_text_locale` SET `CreatureID`='28859', `GroupID`='3', `ID`='2', `Locale`='esES', `text`='¡Qué ingenuo!' WHERE (`CreatureID`='28859') AND (`GroupID`='3') AND (`ID`='2');
UPDATE `creature_text_locale` SET `CreatureID`='28859', `GroupID`='4', `ID`='0', `Locale`='esES', `text`='Esperaba acabar con vuestras vidas rápidamente, pero habéis resultado más... resistentes de lo que pensaba. Aun así, vuestros esfuerzos son en vano. Esta guerra es culpa vuestra, imprudentes mortales descuidados. Yo hago lo que debo... y si eso implica vuestra extinción... ¡QUE ASÍ SEA!' WHERE (`CreatureID`='28859') AND (`GroupID`='4') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28859', `GroupID`='5', `ID`='0', `Locale`='esES', `text`='¡Pocos han experimentado el dolor que voy a inflingiros ahora!' WHERE (`CreatureID`='28859') AND (`GroupID`='5') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28859', `GroupID`='6', `ID`='0', `Locale`='esES', `text`='¡Os enseñaré lo poco que sabéis de la magia, niñatos ignorantes!' WHERE (`CreatureID`='28859') AND (`GroupID`='6') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28859', `GroupID`='7', `ID`='0', `Locale`='esES', `text`='¡Mirad indefensos cómo quiebro vuestras esperanzas!' WHERE (`CreatureID`='28859') AND (`GroupID`='7') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28859', `GroupID`='8', `ID`='0', `Locale`='esES', `text`='¡Daré buen uso a tu energía!' WHERE (`CreatureID`='28859') AND (`GroupID`='8') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28859', `GroupID`='8', `ID`='1', `Locale`='esES', `text`='¡Soy el Tejehechizos! ¡Mi poder es infinito!' WHERE (`CreatureID`='28859') AND (`GroupID`='8') AND (`ID`='1');
UPDATE `creature_text_locale` SET `CreatureID`='28859', `GroupID`='8', `ID`='2', `Locale`='esES', `text`='¡Tu espíritu permanecerá aquí para siempre!' WHERE (`CreatureID`='28859') AND (`GroupID`='8') AND (`ID`='2');
UPDATE `creature_text_locale` SET `CreatureID`='28859', `GroupID`='9', `ID`='0', `Locale`='esES', `text`='¡BASTA! ¡Si queréis la magia de Azeroth, la tendréis!' WHERE (`CreatureID`='28859') AND (`GroupID`='9') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28859', `GroupID`='10', `ID`='0', `Locale`='esES', `text`='Ahora aparecen vuestros benefactores, ¡pero llegan demasiado tarde! Los poderes aquí contenidos son suficientes para destruir el mundo diez veces. ¿Qué creéis que os harán a vosotros?' WHERE (`CreatureID`='28859') AND (`GroupID`='10') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28859', `GroupID`='11', `ID`='0', `Locale`='esES', `text`='¡SOMETEOS!' WHERE (`CreatureID`='28859') AND (`GroupID`='11') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28859', `GroupID`='12', `ID`='0', `Locale`='esES', `text`='%s respira hondo.' WHERE (`CreatureID`='28859') AND (`GroupID`='12') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28859', `GroupID`='13', `ID`='0', `Locale`='esES', `text`='¡Los poderes que actuan aquí superan cualquier cosa que podáis imaginar!' WHERE (`CreatureID`='28859') AND (`GroupID`='13') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28859', `GroupID`='14', `ID`='0', `Locale`='esES', `text`='¡SOY IMPARABLE!' WHERE (`CreatureID`='28859') AND (`GroupID`='14') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28859', `GroupID`='15', `ID`='0', `Locale`='esES', `text`='¡Alexstrasza, otra de tus crías cae!' WHERE (`CreatureID`='28859') AND (`GroupID`='15') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28859', `GroupID`='15', `ID`='1', `Locale`='esES', `text`='¡Poco más que mosquitos!' WHERE (`CreatureID`='28859') AND (`GroupID`='15') AND (`ID`='1');
UPDATE `creature_text_locale` SET `CreatureID`='28859', `GroupID`='15', `ID`='2', `Locale`='esES', `text`='¡Vuestros aliados rojos compartirán vuestro mismo destino!' WHERE (`CreatureID`='28859') AND (`GroupID`='15') AND (`ID`='2');
UPDATE `creature_text_locale` SET `CreatureID`='28859', `GroupID`='16', `ID`='0', `Locale`='esES', `text`='¿Aún sigues en pie? No por mucho tiempo.' WHERE (`CreatureID`='28859') AND (`GroupID`='16') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28859', `GroupID`='16', `ID`='1', `Locale`='esES', `text`='¡Tu causa está perdida!' WHERE (`CreatureID`='28859') AND (`GroupID`='16') AND (`ID`='1');
UPDATE `creature_text_locale` SET `CreatureID`='28859', `GroupID`='16', `ID`='2', `Locale`='esES', `text`='¡Vuestras frágiles mentes serán destrozadas!' WHERE (`CreatureID`='28859') AND (`GroupID`='16') AND (`ID`='2');
UPDATE `creature_text_locale` SET `CreatureID`='28859', `GroupID`='17', `ID`='0', `Locale`='esES', `text`='¡Impensable! ¡Los mortales lo destruirán... todo! ¿Hermana, qué has...?' WHERE (`CreatureID`='28859') AND (`GroupID`='17') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28859', `GroupID`='18', `ID`='0', `Locale`='esES', `text`='¡%s fija su mirada en ti!' WHERE (`CreatureID`='28859') AND (`GroupID`='18') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28859', `GroupID`='19', `ID`='0', `Locale`='esES', `text`='¡%s monta en cólera!' WHERE (`CreatureID`='28859') AND (`GroupID`='19') AND (`ID`='0');

-- Alexstrasza la Protectora  --
UPDATE `creature_text_locale` SET `CreatureID`='32295', `GroupID`='0', `ID`='0', `Locale`='esES', `text`='Hice lo que tenía que hacer, hermano. No me dejaste otra alternativa.' WHERE (`CreatureID`='32295') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='32295', `GroupID`='1', `ID`='0', `Locale`='esES', `text`='Y así acaba la guerra de El Nexo.' WHERE (`CreatureID`='32295') AND (`GroupID`='1') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='32295', `GroupID`='2', `ID`='0', `Locale`='esES', `text`='Esta resolución me apena enormemente, pero la destrucción, la monumental pérdida de vida... tenían que acabar. A pesar de las recientes transgresiones de Malygos, lloraré su pérdida. Hubo un tiempo en que fue un guardián, un protector. Hoy ha caído uno de los seres más poderosos del mundo.' WHERE (`CreatureID`='32295') AND (`GroupID`='2') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='32295', `GroupID`='3', `ID`='0', `Locale`='esES', `text`='El Vuelo Rojo se encargará de arreglar la devastación infligida sobre Azeroth. Regresad a casa con vuestra gente y descansad. El mañana os traerá nuevos retos y tenéis que estar preparados para enfrentaros a ellos. La vida... continúa.' WHERE (`CreatureID`='32295') AND (`GroupID`='3') AND (`ID`='0');

-- Chispazo --
UPDATE `creature_text_locale` SET `CreatureID`='30084', `GroupID`='0', `ID`='0', `Locale`='esES', `text`='¡Un %s toma forma a partir de una falla cercana!' WHERE (`CreatureID`='30084') AND (`GroupID`='0') AND (`ID`='0');