
-- TEMPLO OSCURO --

-- Gran señor de la guerra Naj'entus --
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22887', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Moriréis en nombre de Lady Vashj!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22887') AND (`groupid`='0') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22887', `groupid`='1', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Quedaos por aquí!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22887') AND (`groupid`='1') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22887', `groupid`='1', `id`='1', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Me encargaré de ti más tarde.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22887') AND (`groupid`='1') AND (`id`='1');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22887', `groupid`='2', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Tu éxito ha durado poco!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22887') AND (`groupid`='2') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22887', `groupid`='2', `id`='1', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Es hora de que te vayas.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22887') AND (`groupid`='2') AND (`id`='1');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22887', `groupid`='3', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Be\'lanen dalorai!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22887') AND (`groupid`='3') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22887', `groupid`='3', `id`='1', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡La sangre... fluirá!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22887') AND (`groupid`='3') AND (`id`='1');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22887', `groupid`='4', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Bal, lamer zhita!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22887') AND (`groupid`='4') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22887', `groupid`='5', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Mi paciencia se ha agotado! ¡Muere! ¡Muere!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22887') AND (`groupid`='5') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22887', `groupid`='6', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Lord Illidan... os aplastará!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22887') AND (`groupid`='6') AND (`id`='0');

-- Supremus --
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22898', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='%s fija un nuevo objetivo.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22898') AND (`groupid`='0') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22898', `groupid`='1', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡%s golpea el suelo con ira!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22898') AND (`groupid`='1') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22898', `groupid`='2', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡El suelo empieza a abrirse!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22898') AND (`groupid`='2') AND (`id`='0');

-- Señor de batalla Lengua de ceniza --
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22844', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡%s entra en frenesí!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22844') AND (`groupid`='0') AND (`id`='0');

-- Teron Sanguino --
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22871', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Yo fui el primero, ya sabes. Para mí, la ruleta de la muerte ha girado numerosas veces. Ha pasado tanto tiempo... (Suspira). Tengo que ponerme al día.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22871') AND (`groupid`='0') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22871', `groupid`='1', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡La venganza es mía!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22871') AND (`groupid`='1') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22871', `groupid`='2', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Tengo un uso para vosotros...', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22871') AND (`groupid`='2') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22871', `groupid`='2', `id`='1', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Esto empeora.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22871') AND (`groupid`='2') AND (`id`='1');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22871', `groupid`='3', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¿Por qué estáis tan asustados?', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22871') AND (`groupid`='3') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22871', `groupid`='3', `id`='1', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='La muerte no es tan terrible.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22871') AND (`groupid`='3') AND (`id`='1');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22871', `groupid`='4', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Rendíos.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22871') AND (`groupid`='4') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22871', `groupid`='4', `id`='1', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Tengo algo para vosotros...', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22871') AND (`groupid`='4') AND (`id`='1');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22871', `groupid`='5', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Mostraréis el debido respeto!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22871') AND (`groupid`='5') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22871', `groupid`='6', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='La ruleta... gira... de nuevo.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22871') AND (`groupid`='6') AND (`id`='0');

-- Behemoth Mascahuesos --
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='23196', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡%s entra en frenesí!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23196') AND (`groupid`='0') AND (`id`='0');

-- Esencia del sufrimiento --
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='23418', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Solo os esperan dolor y sufrimiento!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23418') AND (`groupid`='0') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='23418', `groupid`='1', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡No me dejéis sola!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23418') AND (`groupid`='1') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='23418', `groupid`='2', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Mirad lo que me habéis hecho hacer!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23418') AND (`groupid`='2') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='23418', `groupid`='2', `id`='1', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡No pregunté por esto!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23418') AND (`groupid`='2') AND (`id`='1');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='23418', `groupid`='2', `id`='2', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='El dolor es solo el comienzo...', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23418') AND (`groupid`='2') AND (`id`='2');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='23418', `groupid`='3', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡No quiero volver!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23418') AND (`groupid`='3') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='23418', `groupid`='4', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¿Ahora que debería hacer?', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23418') AND (`groupid`='4') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='23418', `groupid`='5', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡%s entra en frenesí!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23418') AND (`groupid`='5') AND (`id`='0');

-- Esencia de deseo --
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='23419', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Puedes tener todo lo que desees... pagando su precio.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23419') AND (`groupid`='0') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='23419', `groupid`='1', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='La realización está cerca.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23419') AND (`groupid`='1') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='23419', `groupid`='1', `id`='1', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Sí, ahora os quedaréis con nosotros...', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23419') AND (`groupid`='1') AND (`id`='1');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='23419', `groupid`='1', `id`='2', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Vuestro objetivo excede de vuestra comprensión.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23419') AND (`groupid`='1') AND (`id`='2');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='23419', `groupid`='2', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Tened cuidado con lo que deseáis.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23419') AND (`groupid`='2') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='23419', `groupid`='3', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Estaré esperando.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23419') AND (`groupid`='3') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='23419', `groupid`='4', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡No estaré lejos!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23419') AND (`groupid`='4') AND (`id`='0');

-- Esencia de inquina --
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='23420', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Cuidado: estoy vivo!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23420') AND (`groupid`='0') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='23420', `groupid`='0', `id`='1', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Tan... imprudentes.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23420') AND (`groupid`='0') AND (`id`='1');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='23420', `groupid`='1', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='<risa maníaca>', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23420') AND (`groupid`='1') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='23420', `groupid`='1', `id`='1', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Ya basta! ¡No más!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23420') AND (`groupid`='1') AND (`id`='1');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='23420', `groupid`='2', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡De rodillas!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23420') AND (`groupid`='2') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='23420', `groupid`='3', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Cuidado, cobardes!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23420') AND (`groupid`='3') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='23420', `groupid`='4', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡No seré... ignorado!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23420') AND (`groupid`='4') AND (`id`='0');

-- Gurtogg Sangre Hirviente --
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22948', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='La Horda... os aplastará.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22948') AND (`groupid`='0') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22948', `groupid`='1', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Hora del banquete.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22948') AND (`groupid`='1') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22948', `groupid`='1', `id`='1', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Más! ¡Quiero más!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22948') AND (`groupid`='1') AND (`id`='1');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22948', `groupid`='2', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Beber vuestra sangre. Comer vuestra carne.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22948') AND (`groupid`='2') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22948', `groupid`='2', `id`='1', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Estoy hambriento!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22948') AND (`groupid`='2') AND (`id`='1');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22948', `groupid`='3', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='<balbucea>', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22948') AND (`groupid`='3') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22948', `groupid`='3', `id`='1', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Rasgaré la carne de vuestros huesos!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22948') AND (`groupid`='3') AND (`id`='1');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22948', `groupid`='4', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Aaaargh...', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22948') AND (`groupid`='4') AND (`id`='0');

-- Madre Shahraz --
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22947', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Tenéis que pagar para jugar.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22947') AND (`groupid`='0') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22947', `groupid`='0', `id`='1', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='No estoy impresionada.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22947') AND (`groupid`='0') AND (`id`='1');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22947', `groupid`='0', `id`='2', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¿Estáis disfrutando?', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22947') AND (`groupid`='0') AND (`id`='2');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22947', `groupid`='1', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Y bien... ¿negocios o placer?', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22947') AND (`groupid`='1') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22947', `groupid`='2', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Parecéis un poco tensos...', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22947') AND (`groupid`='2') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22947', `groupid`='2', `id`='1', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='No seáis timidos.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22947') AND (`groupid`='2') AND (`id`='1');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22947', `groupid`='2', `id`='2', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Soy toda... vuestra.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22947') AND (`groupid`='2') AND (`id`='2');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22947', `groupid`='3', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Lo que fácil viene, fácil se va.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22947') AND (`groupid`='3') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22947', `groupid`='3', `id`='1', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Tanto por un final feliz.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22947') AND (`groupid`='3') AND (`id`='1');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22947', `groupid`='4', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Dejad de jugar con mis sentimientos!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22947') AND (`groupid`='4') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22947', `groupid`='5', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='No había... terminado.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22947') AND (`groupid`='5') AND (`id`='0');

-- Lady Malande --
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22951', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Huid o morid!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22951') AND (`groupid`='0') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22951', `groupid`='1', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Por Quel\'Thalas! ¡Por La Fuente del Sol!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22951') AND (`groupid`='1') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22951', `groupid`='2', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Sin segundas oportunidades!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22951') AND (`groupid`='2') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22951', `groupid`='3', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Estoy llena de sorpresas!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22951') AND (`groupid`='3') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22951', `groupid`='4', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Mi trabajo está terminado.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22951') AND (`groupid`='4') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22951', `groupid`='5', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Como debe ser.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22951') AND (`groupid`='5') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22951', `groupid`='6', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='El destino... espera.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22951') AND (`groupid`='6') AND (`id`='0');

-- Gathios el Despedazador --
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22949', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Tengo mejores cosas que hacer...', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22949') AND (`groupid`='0') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22949', `groupid`='1', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Basta de juegos!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22949') AND (`groupid`='1') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22949', `groupid`='2', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Disfrutad de vuestros últimos momentos.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22949') AND (`groupid`='2') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22949', `groupid`='3', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Eres MÍO!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22949') AND (`groupid`='3') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22949', `groupid`='4', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Selama am\'oronor!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22949') AND (`groupid`='4') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22949', `groupid`='5', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Bien hecho!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22949') AND (`groupid`='5') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22949', `groupid`='6', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Lord Illidan, yo...', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22949') AND (`groupid`='6') AND (`id`='0');

-- Veras Sombra Oscura --
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22952', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¿Deseáis ponerme a prueba?', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22952') AND (`groupid`='0') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22952', `groupid`='1', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¿Queréis matarme? ¡Vosotros primero!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22952') AND (`groupid`='1') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22952', `groupid`='2', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='No estáis preparados para esto.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22952') AND (`groupid`='2') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22952', `groupid`='3', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Anar\'alah belore!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22952') AND (`groupid`='3') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22952', `groupid`='4', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Muy valiente.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22952') AND (`groupid`='4') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22952', `groupid`='5', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Una muerte gloriosa!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22952') AND (`groupid`='5') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22952', `groupid`='6', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Habéis tenido... suerte.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22952') AND (`groupid`='6') AND (`id`='0');

-- Akama (1) --
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='23191', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Tábido de la tribu Lengua de Ceniza, tu líder habla.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23191') AND (`groupid`='0') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='23191', `groupid`='1', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='El Traidor ya no nos domina. ¡La magia oscura que practicaba sobre el alma Lengua de Ceniza ha sido destruida!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23191') AND (`groupid`='1') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='23191', `groupid`='2', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Salid de las sombras! ¡He vuelto para guiaros contra vuestro verdadero enemigo! ¡Despojaos de vuestras cadenas y alzad vuestras armas contra vuestros amos Illidari!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23191') AND (`groupid`='2') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='23191', `groupid`='3', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡No duraré mucho más!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23191') AND (`groupid`='3') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='23191', `groupid`='4', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡No! ¡Aún no!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23191') AND (`groupid`='4') AND (`id`='0');

-- Akama (2) --
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='23089', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Tened cuidado, amigos. El Traidor medita en la corte que hay justo allí.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23089') AND (`groupid`='0') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='23089', `groupid`='1', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Yo me encargo de estos chuchos! Atacad ahora, amigos! Atacad al Traidor!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23089') AND (`groupid`='1') AND (`id`='0');

-- Illidan Tempestira --
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22917', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Venid esbirros míos. ¡Dad a este traidor su merecido!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22917') AND (`groupid`='0') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22917', `groupid`='1', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¿Quién será el siguiente en probar mis hojas?', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22917') AND (`groupid`='1') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22917', `groupid`='1', `id`='1', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Esto es demasiado fácil!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22917') AND (`groupid`='1') AND (`id`='1');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22917', `groupid`='2', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡No seré tocado por gente como vosotros!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22917') AND (`groupid`='2') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22917', `groupid`='3', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Observad las llamas de Azzinoth!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22917') AND (`groupid`='3') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22917', `groupid`='4', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Mirad fijamente a los ojos del Traidor!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22917') AND (`groupid`='4') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22917', `groupid`='5', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Contemplad el poder... del demonio interior!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22917') AND (`groupid`='5') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22917', `groupid`='6', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Habéis perdido demasiado tiempo, mortales. Ahora caeréis.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22917') AND (`groupid`='6') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22917', `groupid`='7', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Puedo sentir vuestro odio.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22917') AND (`groupid`='7') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22917', `groupid`='7', `id`='1', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Entregaos a vuestros miedos!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22917') AND (`groupid`='7') AND (`id`='1');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22917', `groupid`='7', `id`='2', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡No sabéis lo que es el poder!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22917') AND (`groupid`='7') AND (`id`='2');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='22917', `groupid`='7', `id`='3', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Tan... arrogante!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='22917') AND (`groupid`='7') AND (`id`='3');

-- Maiev Cantosombrío --
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='23197', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Esto es por Naisha!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23197') AND (`groupid`='0') AND (`id`='0');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='23197', `groupid`='0', `id`='1', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Sangra como yo he sangrado!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23197') AND (`groupid`='0') AND (`id`='1');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='23197', `groupid`='0', `id`='2', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Esta vez no habrá prisión para ti!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23197') AND (`groupid`='0') AND (`id`='2');
UPDATE `tc 3.3.5`.`locales_creature_text` SET `entry`='23197', `groupid`='0', `id`='3', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Conoce tu final, demonio!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23197') AND (`groupid`='0') AND (`id`='3');