
-- LA FORJA DE ALMAS --

-- Velador Guardaalma --
UPDATE `creature_text_locale` SET `CreatureID`='36478', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='¡%s entra en frenesí!' WHERE (`CreatureID`='36478') AND (`GroupID`='0') AND (`ID`='0');

-- Bronjahm --
UPDATE `creature_text_locale` SET `CreatureID`='36497', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='¡Por fin, un público entregado!' WHERE (`CreatureID`='36497') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36497', `GroupID`='1', `ID`='0', `Locale`='esES', `Text`='Combustible para el motor.' WHERE (`CreatureID`='36497') AND (`GroupID`='1') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36497', `GroupID`='1', `ID`='1', `Locale`='esES', `Text`='¡Otra alma para fortalecer al anfitrión!' WHERE (`CreatureID`='36497') AND (`GroupID`='1') AND (`ID`='1');
UPDATE `creature_text_locale` SET `CreatureID`='36497', `GroupID`='2', `ID`='0', `Locale`='esES', `Text`='El Devorador espera...' WHERE (`CreatureID`='36497') AND (`GroupID`='2') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36497', `GroupID`='3', `ID`='0', `Locale`='esES', `Text`='¡El vórtice de la destrucción te llama!' WHERE (`CreatureID`='36497') AND (`GroupID`='3') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36497', `GroupID`='4', `ID`='0', `Locale`='esES', `Text`='¡Separaré tu alma de tu cuerpo!' WHERE (`CreatureID`='36497') AND (`GroupID`='4') AND (`ID`='0');

-- Devoraalmas --
UPDATE `creature_text_locale` SET `CreatureID`='36502', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='¿Os atrevéis a mirar al anfitrión de almas? OS DEVORARÉ ENTEROS.' WHERE (`CreatureID`='36502') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36502', `GroupID`='0', `ID`='1', `Locale`='esES', `Text`='¿Os atrevéis a mirar al anfitrión de almas? OS DEVORARÉ ENTEROS.' WHERE (`CreatureID`='36502') AND (`GroupID`='0') AND (`ID`='1');
UPDATE `creature_text_locale` SET `CreatureID`='36502', `GroupID`='1', `ID`='0', `Locale`='esES', `Text`='¡Condenación!' WHERE (`CreatureID`='36502') AND (`GroupID`='1') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36502', `GroupID`='1', `ID`='1', `Locale`='esES', `Text`='¡Eternamente perdidos!' WHERE (`CreatureID`='36502') AND (`GroupID`='1') AND (`ID`='1');
UPDATE `creature_text_locale` SET `CreatureID`='36502', `GroupID`='2', `ID`='0', `Locale`='esES', `Text`='¡Condenación!' WHERE (`CreatureID`='36502') AND (`GroupID`='2') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36502', `GroupID`='2', `ID`='1', `Locale`='esES', `Text`='¡Eternamente perdidos!' WHERE (`CreatureID`='36502') AND (`GroupID`='2') AND (`ID`='1');
UPDATE `creature_text_locale` SET `CreatureID`='36502', `GroupID`='3', `ID`='0', `Locale`='esES', `Text`='¡Condenación!' WHERE (`CreatureID`='36502') AND (`GroupID`='3') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36502', `GroupID`='3', `ID`='1', `Locale`='esES', `Text`='¡Eternamente perdidos!' WHERE (`CreatureID`='36502') AND (`GroupID`='3') AND (`ID`='1');
UPDATE `creature_text_locale` SET `CreatureID`='36502', `GroupID`='4', `ID`='0', `Locale`='esES', `Text`='¡No se puede amainar la marejada de almas! Solo posponéis lo inevitable.' WHERE (`CreatureID`='36502') AND (`GroupID`='4') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36502', `GroupID`='4', `ID`='1', `Locale`='esES', `Text`='¡No se puede amainar la marejada de almas! Solo posponéis lo inevitable.' WHERE (`CreatureID`='36502') AND (`GroupID`='4') AND (`ID`='1');
UPDATE `creature_text_locale` SET `CreatureID`='36502', `GroupID`='4', `ID`='2', `Locale`='esES', `Text`='¡No se puede amainar la marejada de almas! Solo posponéis lo inevitable.' WHERE (`CreatureID`='36502') AND (`GroupID`='4') AND (`ID`='2');
UPDATE `creature_text_locale` SET `CreatureID`='36502', `GroupID`='5', `ID`='0', `Locale`='esES', `Text`='%s lanza |cFFFFFF00Alma reflejada|r' WHERE (`CreatureID`='36502') AND (`GroupID`='5') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36502', `GroupID`='6', `ID`='0', `Locale`='esES', `Text`='¡%s comienza a |cFFFF0000desatar almas|r!' WHERE (`CreatureID`='36502') AND (`GroupID`='6') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36502', `GroupID`='7', `ID`='0', `Locale`='esES', `Text`='¡SUFRIMIENTO! ¡ANGUSTIA! ¡CAOS! ¡ALZAOS Y COMED!' WHERE (`CreatureID`='36502') AND (`GroupID`='7') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36502', `GroupID`='7', `ID`='1', `Locale`='esES', `Text`='¡SUFRIMIENTO! ¡ANGUSTIA! ¡CAOS! ¡ALZAOS Y COMED!' WHERE (`CreatureID`='36502') AND (`GroupID`='7') AND (`ID`='1');
UPDATE `creature_text_locale` SET `CreatureID`='36502', `GroupID`='7', `ID`='2', `Locale`='esES', `Text`='¡SUFRIMIENTO! ¡ANGUSTIA! ¡CAOS! ¡ALZAOS Y COMED!' WHERE (`CreatureID`='36502') AND (`GroupID`='7') AND (`ID`='2');
UPDATE `creature_text_locale` SET `CreatureID`='36502', `GroupID`='8', `ID`='0', `Locale`='esES', `Text`='¡%s comienza a lanzar Almas gemebundas!' WHERE (`CreatureID`='36502') AND (`GroupID`='8') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36502', `GroupID`='9', `ID`='0', `Locale`='esES', `Text`='Contemplad el abismo y observad vuestro fin.' WHERE (`CreatureID`='36502') AND (`GroupID`='9') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36502', `GroupID`='9', `ID`='1', `Locale`='esES', `Text`='Contemplad el abismo y observad vuestro fin.' WHERE (`CreatureID`='36502') AND (`GroupID`='9') AND (`ID`='1');

-- Lady Jaina Valiente --
UPDATE `creature_text_locale` SET `CreatureID`='37597', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='¡Gracias a la Luz que estáis a salvo! Tenemos mucho trabajo que hacer si queremos derrotar al Rey Exánime y poner fin a la Plaga.' WHERE (`CreatureID`='37597') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37597', `GroupID`='1', `ID`='0', `Locale`='esES', `Text`='Nuestros aliados de la Cruzada Argenta y de los Caballeros de la Espada de Ébano han traspasado la Puerta Principal de la Corona de Hielo y tratan de asentar una avanzada en la Ciudadela.' WHERE (`CreatureID`='37597') AND (`GroupID`='1') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37597', `GroupID`='2', `ID`='0', `Locale`='esES', `Text`='Su éxito depende de lo que descubramos en estas salas malditas. Aunque nuestra misión es arriesgada, ¡debemos perseverar!' WHERE (`CreatureID`='37597') AND (`GroupID`='2') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37597', `GroupID`='3', `ID`='0', `Locale`='esES', `Text`='Con la atención del Rey Exánime puesta en la Puerta Principal, nos abriremos camino por el lateral en busca de información que nos permitirá derrotar a la Plaga de una vez por todas.' WHERE (`CreatureID`='37597') AND (`GroupID`='3') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37597', `GroupID`='4', `ID`='0', `Locale`='esES', `Text`='El IV:7 del rey Varian ha recopilado información sobre el sagrario privado del Rey Exánime en lo profundo de un lugar llamado las Cámaras de Reflexión.' WHERE (`CreatureID`='37597') AND (`GroupID`='4') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37597', `GroupID`='5', `ID`='0', `Locale`='esES', `Text`='Nos abriremos paso a través de este espantoso lugar y encontraremos la forma de entrar en las Cámaras de Reflexión. Siento una magia poderosa oculta en esas cámaras. ¡Una magia que podría ser la clave para destruir a la Plaga!' WHERE (`CreatureID`='37597') AND (`GroupID`='5') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37597', `GroupID`='6', `ID`='0', `Locale`='esES', `Text`='Vuestra primera misión será destruir las máquinas de la muerte de este engranaje de almas y despejar el camino para nuestros soldados.' WHERE (`CreatureID`='37597') AND (`GroupID`='6') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37597', `GroupID`='7', `ID`='0', `Locale`='esES', `Text`='¡Apresuraos, campeones! Ordenaré a las tropas que os sigan.' WHERE (`CreatureID`='37597') AND (`GroupID`='7') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='38160', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='¡Un trabajo excelente, campeones! Asentaremos nuestro campamento base en estas estancias. Mis magos harán que el teletransportador de la Plaga funcione dentro de nada. Entrad en cuanto estéis preparados para la próxima misión. Nos veremos al otro lado.' WHERE (`CreatureID`='38160') AND (`GroupID`='0') AND (`ID`='0');

-- Lady Sylvanas Brisaveloz --
UPDATE `creature_text_locale` SET `CreatureID`='37596', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='La Cruzada Argenta y los Caballeros de la Espada de Ébano han asaltado las puertas de la Ciudadela de la Corona de Hielo y están preparando un ataque sobre la Plaga. Nuestra misión es más sutil, pero igual de importante.' WHERE (`CreatureID`='37596') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37596', `GroupID`='1', `ID`='0', `Locale`='esES', `Text`='Con la atención del Rey Exánime puesta en la Puerta Principal, nos abriremos camino por el lateral en busca de información que nos permitirá derrotar a la Plaga, de una vez por todas.' WHERE (`CreatureID`='37596') AND (`GroupID`='1') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37596', `GroupID`='2', `ID`='0', `Locale`='esES', `Text`='Los exploradores nos han informado de que el Rey Exánime tiene una estancia en el exterior del Trono Helado, en un lugar llamado las Cámaras de Reflexión. Ese es nuestro objetivo, campeones.' WHERE (`CreatureID`='37596') AND (`GroupID`='2') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37596', `GroupID`='3', `ID`='0', `Locale`='esES', `Text`='Abriremos una senda de destrucción hasta ese maldito lugar y encontraremos una forma de entrar en las Cámaras de Reflexión. Si hay algo de valor aquí, lo encontraremos en las cámaras.' WHERE (`CreatureID`='37596') AND (`GroupID`='3') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37596', `GroupID`='4', `ID`='0', `Locale`='esES', `Text`='Vuestra primera misión será destruir las máquinas de la muerte de este engranaje de almas y despejar el camino para nuestros soldados.' WHERE (`CreatureID`='37596') AND (`GroupID`='4') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37596', `GroupID`='5', `ID`='0', `Locale`='esES', `Text`='La Dama Oscura os protege. ¡Daos prisa!' WHERE (`CreatureID`='37596') AND (`GroupID`='5') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='38161', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='¡Un trabajo excelente, campeones! Asentaremos nuestro campamento base en estas estancias. Mis magos harán que el teletransportador de la Plaga funcione dentro de nada. Entrad cuando estéis preparados para la próxima misión. Nos veremos al otro lado.' WHERE (`CreatureID`='38161') AND (`GroupID`='0') AND (`ID`='0');