
-- CÁMARAS DE REFLEXIÓN --

-- Falric --
UPDATE `creature_text_locale` SET `CreatureID`='38112', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='Hombres, mujeres, niños... Nadie se libró de la cólera del maestro. Tu muerte no será distinta.' WHERE (`CreatureID`='38112') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='38112', `GroupID`='1', `ID`='0', `Locale`='esES', `Text`='¡Gusano asqueroso!' WHERE (`CreatureID`='38112') AND (`GroupID`='1') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='38112', `GroupID`='1', `ID`='1', `Locale`='esES', `Text`='¡Los niños de Stratholme lucharon con más saña!' WHERE (`CreatureID`='38112') AND (`GroupID`='1') AND (`ID`='1');
UPDATE `creature_text_locale` SET `CreatureID`='38112', `GroupID`='2', `ID`='0', `Locale`='esES', `Text`='Marwyn, acaba con ellos...' WHERE (`CreatureID`='38112') AND (`GroupID`='2') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='38112', `GroupID`='3', `ID`='0', `Locale`='esES', `Text`='Desesperación... deliciosa...' WHERE (`CreatureID`='38112') AND (`GroupID`='3') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='38112', `GroupID`='4', `ID`='0', `Locale`='esES', `Text`='Miedo... tan estimulante...' WHERE (`CreatureID`='38112') AND (`GroupID`='4') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='38112', `GroupID`='5', `ID`='0', `Locale`='esES', `Text`='Como desees, mi señor.' WHERE (`CreatureID`='38112') AND (`GroupID`='5') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='38112', `GroupID`='6', `ID`='0', `Locale`='esES', `Text`='Soldados de Lordaeron, ¡alzaos ante la llamada de vuestro maestro!' WHERE (`CreatureID`='38112') AND (`GroupID`='6') AND (`ID`='0');

-- Marwyn --
UPDATE `creature_text_locale` SET `CreatureID`='38113', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='¡Aquí solo encontraréis muerte!' WHERE (`CreatureID`='38113') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='38113', `GroupID`='1', `ID`='0', `Locale`='esES', `Text`='Vi la misma mirada en sus ojos cuando murió. Terenas no se lo podía creer.' WHERE (`CreatureID`='38113') AND (`GroupID`='1') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='38113', `GroupID`='1', `ID`='1', `Locale`='esES', `Text`='¡Atragántate con tu dolor!' WHERE (`CreatureID`='38113') AND (`GroupID`='1') AND (`ID`='1');
UPDATE `creature_text_locale` SET `CreatureID`='38113', `GroupID`='2', `ID`='0', `Locale`='esES', `Text`='Sí... Corre... Corre hacia tu destino... Su amargo y frío abrazo te espera.' WHERE (`CreatureID`='38113') AND (`GroupID`='2') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='38113', `GroupID`='3', `ID`='0', `Locale`='esES', `Text`='¡Tu carne se pudrirá ante tus ojos!' WHERE (`CreatureID`='38113') AND (`GroupID`='3') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='38113', `GroupID`='3', `ID`='1', `Locale`='esES', `Text`='¡Consúmete en la nada!' WHERE (`CreatureID`='38113') AND (`GroupID`='3') AND (`ID`='1');
UPDATE `creature_text_locale` SET `CreatureID`='38113', `GroupID`='4', `ID`='0', `Locale`='esES', `Text`='Como desees, mi señor.' WHERE (`CreatureID`='38113') AND (`GroupID`='4') AND (`ID`='0');

-- Rey Exánime --
UPDATE `creature_text_locale` SET `CreatureID`='37226', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='¡SILENCIO, PALADÍN!' WHERE (`CreatureID`='37226') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37226', `GroupID`='1', `ID`='0', `Locale`='esES', `Text`='¿Así que quieres comunicarte con los muertos? Tendrás lo que deseas.' WHERE (`CreatureID`='37226') AND (`GroupID`='1') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37226', `GroupID`='2', `ID`='0', `Locale`='esES', `Text`='Falric. Marwyn. Traed sus cuerpos a mi estancia cuando hayáis terminado.' WHERE (`CreatureID`='37226') AND (`GroupID`='2') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37226', `GroupID`='3', `ID`='0', `Locale`='esES', `Text`='¡Insensata! Buscas lo que asesiné tiempo atrás. Ahora no es más que un fantasma. Un eco lejano en mi mente…' WHERE (`CreatureID`='37226') AND (`GroupID`='3') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37226', `GroupID`='4', `ID`='0', `Locale`='esES', `Text`='No cometeré el mismo error, Sylvanas. Esta vez no habrá escapatoria. ¡Me serviréis en la muerte!' WHERE (`CreatureID`='37226') AND (`GroupID`='4') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36954', `GroupID`='3', `ID`='0', `Locale`='esES', `Text`='Sucumbid al frío de la tumba.' WHERE (`CreatureID`='36954') AND (`GroupID`='3') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36954', `GroupID`='2', `ID`='0', `Locale`='esES', `Text`='¡No hay escapatoria!' WHERE (`CreatureID`='36954') AND (`GroupID`='2') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36954', `GroupID`='1', `ID`='0', `Locale`='esES', `Text`='No cometeré el mismo error, Sylvanas. Esta vez no habrá escapatoria. ¡Me serviréis en la muerte!' WHERE (`CreatureID`='36954') AND (`GroupID`='1') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36954', `GroupID`='7', `ID`='0', `Locale`='esES', `Text`='¡Esbirros, cogedlos! Traedme sus cadáveres.' WHERE (`CreatureID`='36954') AND (`GroupID`='7') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36954', `GroupID`='4', `ID`='0', `Locale`='esES', `Text`='Otro final sin salida.' WHERE (`CreatureID`='36954') AND (`GroupID`='4') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36954', `GroupID`='5', `ID`='0', `Locale`='esES', `Text`='¿Cuánto vais a aguantar?' WHERE (`CreatureID`='36954') AND (`GroupID`='5') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36954', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='Han llegado tus aliados, Jaina, como prometiste. Todos seréis poderosos agentes de la Plaga.' WHERE (`CreatureID`='36954') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36954', `GroupID`='8', `ID`='0', `Locale`='esES', `Text`='El frío abrazo de la muerte os aguarda.' WHERE (`CreatureID`='36954') AND (`GroupID`='8') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36954', `GroupID`='6', `ID`='0', `Locale`='esES', `Text`='Alzaos, esbirros. Que no pasen.' WHERE (`CreatureID`='36954') AND (`GroupID`='6') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36954', `GroupID`='9', `ID`='0', `Locale`='esES', `Text`='No corráis... ¡Sois míos!' WHERE (`CreatureID`='36954') AND (`GroupID`='9') AND (`ID`='0');

-- General Juraescarcha --
UPDATE `creature_text_locale` SET `CreatureID`='36723', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='¡No sois dignos de enfrentaros al Rey Exánime!' WHERE (`CreatureID`='36723') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36723', `GroupID`='1', `ID`='0', `Locale`='esES', `Text`='Maestro, he fracasado...' WHERE (`CreatureID`='36723') AND (`GroupID`='1') AND (`ID`='0');

-- Lady Jaina Valiente --
UPDATE `creature_text_locale` SET `CreatureID`='37221', `GroupID`='3', `ID`='0', `Locale`='esES', `Text`='¡Atrás! ¡Si tocáis la espada, vuestra alma quedará marcada toda la eternidad! Debo intentar ponerme en contacto con los espíritus atrapados en la Agonía de Escarcha. ¡Haceos a un lado! ¡Atrás!' WHERE (`CreatureID`='37221') AND (`GroupID`='3') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37221', `GroupID`='2', `ID`='0', `Locale`='esES', `Text`='La Agonía de Escarcha: la espada que destrozó nuestro reino.' WHERE (`CreatureID`='37221') AND (`GroupID`='2') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37221', `GroupID`='1', `ID`='0', `Locale`='esES', `Text`='¿Qué es eso? ¡Ahí delante! ¿Será…? ¡Héroes, a mí!' WHERE (`CreatureID`='37221') AND (`GroupID`='1') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37221', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='El frío de este lugar... Puedo sentir cómo se congela mi sangre.' WHERE (`CreatureID`='37221') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37221', `GroupID`='4', `ID`='0', `Locale`='esES', `Text`='¡Uther! ¡Querido Uther! Lo... lo siento.' WHERE (`CreatureID`='37221') AND (`GroupID`='4') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37221', `GroupID`='5', `ID`='0', `Locale`='esES', `Text`='¿Arthas está aquí? Tal vez pueda...' WHERE (`CreatureID`='37221') AND (`GroupID`='5') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37221', `GroupID`='6', `ID`='0', `Locale`='esES', `Text`='Pero Uther, si hay alguna esperanza de llegar a Arthas. Debo… intentarlo.' WHERE (`CreatureID`='37221') AND (`GroupID`='6') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37221', `GroupID`='7', `ID`='0', `Locale`='esES', `Text`='Dime cómo, Uther. ¿Cómo acabo con mi príncipe? Mi...' WHERE (`CreatureID`='37221') AND (`GroupID`='7') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37221', `GroupID`='8', `ID`='0', `Locale`='esES', `Text`='Tienes razón, Uther. Perdóname. No... no sé qué me ha pasado. Daremos esta información al Rey y a los caballeros que se enfrentan a la Plaga en la Ciudadela de la Corona de Hielo.' WHERE (`CreatureID`='37221') AND (`GroupID`='8') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37221', `GroupID`='9', `ID`='0', `Locale`='esES', `Text`='¿Quién afrontaría tal carga?' WHERE (`CreatureID`='37221') AND (`GroupID`='9') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37221', `GroupID`='10', `ID`='0', `Locale`='esES', `Text`='Entonces, aún hay esperanza...' WHERE (`CreatureID`='37221') AND (`GroupID`='10') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37221', `GroupID`='11', `ID`='0', `Locale`='esES', `Text`='¡No me privarás de esto, Arthas! Debo saber... Debo averiguar...' WHERE (`CreatureID`='37221') AND (`GroupID`='11') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36955', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='Es demasiado poderoso. ¡Debemos abandonar este lugar ahora mismo! Mi magia podrá inmovilizarlo brevemente. ¡Vamos rápido, héroes!' WHERE (`CreatureID`='36955') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36955', `GroupID`='1', `ID`='0', `Locale`='esES', `Text`='Destruiré esta barrera. ¡Debéis mantener atrás a los no-muertos!' WHERE (`CreatureID`='36955') AND (`GroupID`='1') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36955', `GroupID`='2', `ID`='0', `Locale`='esES', `Text`='¡Otro muro de hielo! Evitad que los no-muertos interrumpan mis conjuros para que pueda derribar este muro.' WHERE (`CreatureID`='36955') AND (`GroupID`='2') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36955', `GroupID`='3', `ID`='0', `Locale`='esES', `Text`='¡Está jugando con nosotros! ¡Le enseñaré lo que le pasa al hielo cuando conoce al fuego!' WHERE (`CreatureID`='36955') AND (`GroupID`='3') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36955', `GroupID`='4', `ID`='0', `Locale`='esES', `Text`='Tus muros no podrán detenernos mucho más, monstruo. ¡Los destruiré todos!' WHERE (`CreatureID`='36955') AND (`GroupID`='4') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36955', `GroupID`='5', `ID`='0', `Locale`='esES', `Text`='Hay una salida ahí delante. ¡VAMOS!' WHERE (`CreatureID`='36955') AND (`GroupID`='5') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36955', `GroupID`='6', `ID`='0', `Locale`='esES', `Text`='Casi estamos… ¡No os rindáis!' WHERE (`CreatureID`='36955') AND (`GroupID`='6') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36955', `GroupID`='7', `ID`='0', `Locale`='esES', `Text`='No... no hay salida. No tenemos más opción que luchar. Armaos de valor, héroes, pues esta es nuestra última batalla.' WHERE (`CreatureID`='36955') AND (`GroupID`='7') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36955', `GroupID`='8', `ID`='0', `Locale`='esES', `Text`='Perdonadme, héroes. Debí escuchar a Uther. Tenía… tenía que… verlo por mí misma. Poder mirarle a los ojos una última vez. Lo siento.' WHERE (`CreatureID`='36955') AND (`GroupID`='8') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36955', `GroupID`='9', `ID`='0', `Locale`='esES', `Text`='Ahora sabemos qué debemos hacer. Les daré estas noticias al rey Varian y al alto señor Vadín.' WHERE (`CreatureID`='36955') AND (`GroupID`='9') AND (`ID`='0');

-- Lady Sylvanas Brisaveloz --
UPDATE `creature_text_locale` SET `CreatureID`='37223', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='¡No... no puede ser! La Agonía de Escarcha está justo ante nosotros, sin vigilancia, tal y como dijo el gnomo. ¡Venid, héroes!' WHERE (`CreatureID`='37223') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37223', `GroupID`='1', `ID`='0', `Locale`='esES', `Text`='Al estar tan cerca de la espada que puso fin a mi vida… el dolor… vuelve.' WHERE (`CreatureID`='37223') AND (`GroupID`='1') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37223', `GroupID`='2', `ID`='0', `Locale`='esES', `Text`='No me atrevo a tocarla. ¡Atrás! ¡Atrás mientras intento comunicarme con la espada! Puede que nuestra salvación se halle dentro...' WHERE (`CreatureID`='37223') AND (`GroupID`='2') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37223', `GroupID`='3', `ID`='0', `Locale`='esES', `Text`='Uther... Uther el Iluminado. ¿Cómo...?' WHERE (`CreatureID`='37223') AND (`GroupID`='3') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37223', `GroupID`='4', `ID`='0', `Locale`='esES', `Text`='¿El Rey Exánime está aquí? Entonces, ¡hoy cumpliré mi destino!' WHERE (`CreatureID`='37223') AND (`GroupID`='4') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37223', `GroupID`='5', `ID`='0', `Locale`='esES', `Text`='Tiene que haber un modo...' WHERE (`CreatureID`='37223') AND (`GroupID`='5') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37223', `GroupID`='6', `ID`='0', `Locale`='esES', `Text`='¿Quién afrontaría tal carga?' WHERE (`CreatureID`='37223') AND (`GroupID`='6') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37223', `GroupID`='7', `ID`='0', `Locale`='esES', `Text`='El Trono Helado...' WHERE (`CreatureID`='37223') AND (`GroupID`='7') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37223', `GroupID`='8', `ID`='0', `Locale`='esES', `Text`='¡No escaparás de mí tan fácilmente, Arthas! ¡Obtendré mi venganza!' WHERE (`CreatureID`='37223') AND (`GroupID`='8') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37554', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='Es... demasiado poderoso. Héroes, rápido… ¡venid! ¡Debemos abandonar este lugar ahora mismo! Haré lo que pueda para inmovilizarlo mientras huimos.' WHERE (`CreatureID`='37554') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37554', `GroupID`='1', `ID`='0', `Locale`='esES', `Text`='Ninguna pared detendrá a la Reina alma en pena. Mantened a los no-muertos a raya, héroes. ¡Destruiré la barrera!' WHERE (`CreatureID`='37554') AND (`GroupID`='1') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37554', `GroupID`='2', `ID`='0', `Locale`='esES', `Text`='¡Otra barrera! Sed fuertes, campeones. Derrumbaré el muro.' WHERE (`CreatureID`='37554') AND (`GroupID`='2') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37554', `GroupID`='3', `ID`='0', `Locale`='esES', `Text`='Me canso de estos juegos, Arthas. ¡Tus muros no me detendrán!' WHERE (`CreatureID`='37554') AND (`GroupID`='3') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37554', `GroupID`='4', `ID`='0', `Locale`='esES', `Text`='¡No impedirás que escapemos, demonio! Acabad con los no-muertos mientras derribo esta barrera.' WHERE (`CreatureID`='37554') AND (`GroupID`='4') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37554', `GroupID`='5', `ID`='0', `Locale`='esES', `Text`='Hay una salida ahí delante. ¡VAMOS!' WHERE (`CreatureID`='37554') AND (`GroupID`='5') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37554', `GroupID`='6', `ID`='0', `Locale`='esES', `Text`='Casi estamos… ¡No os rindáis!' WHERE (`CreatureID`='37554') AND (`GroupID`='6') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37554', `GroupID`='7', `ID`='0', `Locale`='esES', `Text`='¡MALDICIÓN, NO HAY SALIDA! Así es cómo acaba… ¡Preparaos, héroes, hoy tendrá lugar nuestra última batalla!' WHERE (`CreatureID`='37554') AND (`GroupID`='7') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37554', `GroupID`='8', `ID`='0', `Locale`='esES', `Text`='Estamos a salvo… por ahora. Su fuerza se ha multiplicado desde nuestra última batalla. Necesitamos un ejército poderoso para destruir al Rey Exánime, mejor incluso que el que la Horda puede convocar.' WHERE (`CreatureID`='37554') AND (`GroupID`='8') AND (`ID`='0');

-- Quel'Delar --
UPDATE `creature_text_locale` SET `CreatureID`='37158', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='¡%s se prepara para atacar!' WHERE (`CreatureID`='37158') AND (`GroupID`='0') AND (`ID`='0');

-- Uther el Iluminado --
UPDATE `creature_text_locale` SET `CreatureID`='37225', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='¡JAINA! ¿Realmente eres tú?' WHERE (`CreatureID`='37225') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37225', `GroupID`='1', `ID`='0', `Locale`='esES', `Text`='Jaina, no tenéis mucho tiempo. El Rey Exánime ve lo que ve la espada. Llegará en cualquier momento.' WHERE (`CreatureID`='37225') AND (`GroupID`='1') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37225', `GroupID`='2', `ID`='0', `Locale`='esES', `Text`='No, niña. Arthas no está aquí. Arthas no es más que una presencia en la mente del Rey Exánime. Un presencia cada vez más débil...' WHERE (`CreatureID`='37225') AND (`GroupID`='2') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37225', `GroupID`='3', `ID`='0', `Locale`='esES', `Text`='Jaina, escúchame. Debes acabar con el Rey Exánime. No puedes razonar con él. Os matará a ti y a tus aliados y os levantará como poderosos soldados de la Plaga.' WHERE (`CreatureID`='37225') AND (`GroupID`='3') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37225', `GroupID`='4', `ID`='0', `Locale`='esES', `Text`='Despierta, niña. Debes acabar con el Rey Exánime en el lugar donde se fusionó con Ner\'zhul, en lo alto de la aguja, en el Trono Helado. Es el único modo.' WHERE (`CreatureID`='37225') AND (`GroupID`='4') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37225', `GroupID`='5', `ID`='0', `Locale`='esES', `Text`='Hay... algo más que deberías saber sobre el Rey Exánime. Nunca se debe perder el control sobre la Plaga. Incluso si vencéis al Rey Exánime, otro deberá ocupar su lugar. Sin el dominio de su maestro, la Plaga camparía a sus anchas por el mundo, destruyendo todo ser viviente.' WHERE (`CreatureID`='37225') AND (`GroupID`='5') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37225', `GroupID`='6', `ID`='0', `Locale`='esES', `Text`='Un gran sacrificio para un alma noble...' WHERE (`CreatureID`='37225') AND (`GroupID`='6') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37225', `GroupID`='7', `ID`='0', `Locale`='esES', `Text`='No lo sé, Jaina. Supongo que la parte de Arthas que vive dentro del Rey Exánime es todo lo que evita que la Plaga aniquile Azeroth.' WHERE (`CreatureID`='37225') AND (`GroupID`='7') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37225', `GroupID`='8', `ID`='0', `Locale`='esES', `Text`='¡No, Jaina! ARRRRRRGHHHH... Se... acerca. Debes... debes...' WHERE (`CreatureID`='37225') AND (`GroupID`='8') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37225', `GroupID`='9', `ID`='0', `Locale`='esES', `Text`='Cuidado. Ya he oído antes que esa hoja maldita nos salvaría. Mira a tu alrededor y observa lo que ha brotado de la Agonía de Escarcha.' WHERE (`CreatureID`='37225') AND (`GroupID`='9') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37225', `GroupID`='10', `ID`='0', `Locale`='esES', `Text`='No tenéis mucho tiempo. El Rey Exánime ve lo que ve la espada. Llegará en cualquier momento.' WHERE (`CreatureID`='37225') AND (`GroupID`='10') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37225', `GroupID`='11', `ID`='0', `Locale`='esES', `Text`='No puedes derrotar al Rey Exánime. Aquí no. Estarías loca si lo intentases. Matará a los que te siguen y los levantará como poderosos soldados de la Plaga. Pero en tu caso, Sylvanas… la recompensa que tiene para ti sería peor que la última.' WHERE (`CreatureID`='37225') AND (`GroupID`='11') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37225', `GroupID`='12', `ID`='0', `Locale`='esES', `Text`='Tal vez, pero debes saber que siempre debe haber un Rey Exánime. Incluso si derrotas a Arthas, otro deberá tomar su lugar. Sin el dominio del Rey Exánime, la Plaga invadirá el mundo como langostas, destruyendo todo lo que toque.' WHERE (`CreatureID`='37225') AND (`GroupID`='12') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37225', `GroupID`='13', `ID`='0', `Locale`='esES', `Text`='No lo sé, Reina alma en pena. Supongo que la parte de Arthas que vive dentro del Rey Exánime es todo lo que evita que la Plaga aniquile Azeroth.' WHERE (`CreatureID`='37225') AND (`GroupID`='13') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37225', `GroupID`='14', `ID`='0', `Locale`='esES', `Text`='Por tanto, la única forma de derrotar al Rey Exánime es destruirlo en el lugar donde fue creado.' WHERE (`CreatureID`='37225') AND (`GroupID`='14') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37225', `GroupID`='15', `ID`='0', `Locale`='esES', `Text`='Eso es. ARRRRRRGHHHH... Se... Acerca. Tú… tú debes...' WHERE (`CreatureID`='37225') AND (`GroupID`='15') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37225', `GroupID`='16', `ID`='0', `Locale`='esES', `Text`='¡Alto! ¡No llevéis esa espada más allá!' WHERE (`CreatureID`='37225') AND (`GroupID`='16') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37225', `GroupID`='17', `ID`='0', `Locale`='esES', `Text`='¿Os dais cuenta de lo que habéis hecho?' WHERE (`CreatureID`='37225') AND (`GroupID`='17') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37225', `GroupID`='18', `ID`='0', `Locale`='esES', `Text`='Habéis forjado esta espada de saronita, la mismísima sangre de un dios antiguo. El poder del Rey Exánime llama a esta arma.' WHERE (`CreatureID`='37225') AND (`GroupID`='18') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37225', `GroupID`='19', `ID`='0', `Locale`='esES', `Text`='Cada segundo que os demoráis, Quel\'Delar bebe del mal de este lugar.' WHERE (`CreatureID`='37225') AND (`GroupID`='19') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37225', `GroupID`='20', `ID`='0', `Locale`='esES', `Text`='Solo hay una manera de limpiar esta espada. Apresuraos a La Fuente del Sol y sumergid la espada en sus aguas.' WHERE (`CreatureID`='37225') AND (`GroupID`='20') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37225', `GroupID`='21', `ID`='0', `Locale`='esES', `Text`='No puedo resistir más la llamada de la Agonía de Escarcha…' WHERE (`CreatureID`='37225') AND (`GroupID`='21') AND (`ID`='0');

-- Atracador del cielo Korn Marcanegra --
UPDATE `creature_text_locale` SET `CreatureID`='30824', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='¡FUEGO! ¡FUEGO!' WHERE (`CreatureID`='30824') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='30824', `GroupID`='1', `ID`='0', `Locale`='esES', `Text`='¡A bordo, YA! La ladera de la montaña se derrumbará en cualquier momento.' WHERE (`CreatureID`='30824') AND (`GroupID`='1') AND (`ID`='0');

-- Gran Capitán Justin Bartlett --
UPDATE `creature_text_locale` SET `CreatureID`='30344', `GroupID`='1', `ID`='0', `Locale`='esES', `Text`='¡Rápido, a bordo! ¡No debemos entretenernos! La ladera de la montaña se derrumbará en cualquier momento.' WHERE (`CreatureID`='30344') AND (`GroupID`='1') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='30344', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='¡FUEGO! ¡FUEGO!' WHERE (`CreatureID`='30344') AND (`GroupID`='0') AND (`ID`='0');