
-- CÁMARAS DE PIEDRA --

-- Krystallus --
UPDATE `creature_text_locale` SET `CreatureID`='27977', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='Aplastar...' WHERE (`CreatureID`='27977') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27977', `GroupID`='1', `ID`='0', `Locale`='esES', `Text`='Ja... Ja... Ja...' WHERE (`CreatureID`='27977') AND (`GroupID`='1') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27977', `GroupID`='2', `ID`='0', `Locale`='esES', `Text`='Uuuuhhhhhhhhhh......' WHERE (`CreatureID`='27977') AND (`GroupID`='2') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27977', `GroupID`='3', `ID`='0', `Locale`='esES', `Text`='Romperos...' WHERE (`CreatureID`='27977') AND (`GroupID`='3') AND (`ID`='0');

-- Doncella de Pena --
UPDATE `creature_text_locale` SET `CreatureID`='27975', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='No deberíais haber venido... ¡ahora moriréis!' WHERE (`CreatureID`='27975') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27975', `GroupID`='1', `ID`='0', `Locale`='esES', `Text`='¿Por qué tiene que ser así?' WHERE (`CreatureID`='27975') AND (`GroupID`='1') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27975', `GroupID`='1', `ID`='1', `Locale`='esES', `Text`='¡Tú te lo has buscado!' WHERE (`CreatureID`='27975') AND (`GroupID`='1') AND (`ID`='1');
UPDATE `creature_text_locale` SET `CreatureID`='27975', `GroupID`='1', `ID`='2', `Locale`='esES', `Text`='Mi carga se vuelve más pesada...' WHERE (`CreatureID`='27975') AND (`GroupID`='1') AND (`ID`='2');
UPDATE `creature_text_locale` SET `CreatureID`='27975', `GroupID`='1', `ID`='3', `Locale`='esES', `Text`='¡Esto es culpa tuya!' WHERE (`CreatureID`='27975') AND (`GroupID`='1') AND (`ID`='3');
UPDATE `creature_text_locale` SET `CreatureID`='27975', `GroupID`='2', `ID`='0', `Locale`='esES', `Text`='¡Espero que os pudráis todos! Yo nunca... quise... esto.' WHERE (`CreatureID`='27975') AND (`GroupID`='2') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27975', `GroupID`='3', `ID`='0', `Locale`='esES', `Text`='Tanto tiempo perdido... ¡que nunca recuperarás!' WHERE (`CreatureID`='27975') AND (`GroupID`='3') AND (`ID`='0');

-- Brann Barbabronce --
UPDATE `creature_text_locale` SET `CreatureID`='28070', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='¡Os estáis ganando el pan!' WHERE (`CreatureID`='28070') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28070', `GroupID`='0', `ID`='1', `Locale`='esES', `Text`='¡Seguid adelante, así se hace!' WHERE (`CreatureID`='28070') AND (`GroupID`='0') AND (`ID`='1');
UPDATE `creature_text_locale` SET `CreatureID`='28070', `GroupID`='0', `ID`='2', `Locale`='esES', `Text`='¡Seguid así! ¡Acabad con todos!' WHERE (`CreatureID`='28070') AND (`GroupID`='0') AND (`ID`='2');
UPDATE `creature_text_locale` SET `CreatureID`='28070', `GroupID`='1', `ID`='0', `Locale`='esES', `Text`='Estoy totalmente machacado... puede que... no lo logre.' WHERE (`CreatureID`='28070') AND (`GroupID`='1') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28070', `GroupID`='2', `ID`='0', `Locale`='esES', `Text`='¡Aún no!... Aún no…' WHERE (`CreatureID`='28070') AND (`GroupID`='2') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28070', `GroupID`='3', `ID`='0', `Locale`='esES', `Text`='¡Hago todo lo que puedo!' WHERE (`CreatureID`='28070') AND (`GroupID`='3') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28070', `GroupID`='3', `ID`='1', `Locale`='esES', `Text`='¡Que la luz te proteja!' WHERE (`CreatureID`='28070') AND (`GroupID`='3') AND (`ID`='1');
UPDATE `creature_text_locale` SET `CreatureID`='28070', `GroupID`='3', `ID`='2', `Locale`='esES', `Text`='¡Espero que esto valga la pena!' WHERE (`CreatureID`='28070') AND (`GroupID`='3') AND (`ID`='2');
UPDATE `creature_text_locale` SET `CreatureID`='28070', `GroupID`='4', `ID`='0', `Locale`='esES', `Text`='¡Hora de conseguir respuestas! ¡Que empiece el espectáculo!' WHERE (`CreatureID`='28070') AND (`GroupID`='4') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28070', `GroupID`='5', `ID`='0', `Locale`='esES', `Text`='¡Tranquilos! ¡El viejo Brann os cubre las espaldas! Distraed a ese monstruo de metal y yo veré si puedo convencer a esta máquina de que os ayude.' WHERE (`CreatureID`='28070') AND (`GroupID`='5') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28070', `GroupID`='6', `ID`='0', `Locale`='esES', `Text`='Esto es un poquito más difícil que antes... Oh, maldita... ¡vienen!' WHERE (`CreatureID`='28070') AND (`GroupID`='6') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28070', `GroupID`='7', `ID`='0', `Locale`='esES', `Text`='En el nombre de Madoran, ¿qué ha hecho eso? ¡Oh! Esperad, creo que lo tengo...' WHERE (`CreatureID`='28070') AND (`GroupID`='7') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28070', `GroupID`='8', `ID`='0', `Locale`='esES', `Text`='Ja, ¡funciona! ¡Nos viene al pelo! ¡Toma esto, brillante bestia de hierro!' WHERE (`CreatureID`='28070') AND (`GroupID`='8') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28070', `GroupID`='9', `ID`='0', `Locale`='esES', `Text`='Tomaos un segundo y saboread esto conmigo. Pronto... Se desvelará todo. Bueno, ¡hagámoslo!' WHERE (`CreatureID`='28070') AND (`GroupID`='9') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28070', `GroupID`='10', `ID`='0', `Locale`='esES', `Text`='¡Atentos! Tendré esto listo en un par de...' WHERE (`CreatureID`='28070') AND (`GroupID`='10') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28070', `GroupID`='11', `ID`='0', `Locale`='esES', `Text`='Oh, eso no suena nada bien. Puede que tengamos alguna que otra complicación...' WHERE (`CreatureID`='28070') AND (`GroupID`='11') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28070', `GroupID`='12', `ID`='0', `Locale`='esES', `Text`='Ah, quieres jugar duro, ¿eh? ¡A mí me encanta!' WHERE (`CreatureID`='28070') AND (`GroupID`='12') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28070', `GroupID`='13', `ID`='0', `Locale`='esES', `Text`='Un par de minutos más y … Oh, oh.' WHERE (`CreatureID`='28070') AND (`GroupID`='13') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28070', `GroupID`='14', `ID`='0', `Locale`='esES', `Text`='¿Aumentado? ¿Cuál es la buena noticia?' WHERE (`CreatureID`='28070') AND (`GroupID`='14') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28070', `GroupID`='15', `ID`='0', `Locale`='esES', `Text`='¡Ese era el problema! Ahora, estoy avanzando…' WHERE (`CreatureID`='28070') AND (`GroupID`='15') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28070', `GroupID`='16', `ID`='0', `Locale`='esES', `Text`='¡Espera! ¡Mientras yo esté al mando, no se va a higienizar a nadie!' WHERE (`CreatureID`='28070') AND (`GroupID`='16') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28070', `GroupID`='17', `ID`='0', `Locale`='esES', `Text`='¡Ja! ¡Al fin ganaron los viejos dedos mágicos! Ahora pongámonos a…' WHERE (`CreatureID`='28070') AND (`GroupID`='17') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28070', `GroupID`='18', `ID`='0', `Locale`='esES', `Text`='¿Purgar? No, no, no, no... ¿Dónde...? Ajá, esto debería funcionar...' WHERE (`CreatureID`='28070') AND (`GroupID`='18') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28070', `GroupID`='19', `ID`='0', `Locale`='esES', `Text`='¿Petición? ¿Para qué crees que estoy aquí, para tomarme un café? ¡Suéltalo ya!' WHERE (`CreatureID`='28070') AND (`GroupID`='19') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28070', `GroupID`='20', `ID`='0', `Locale`='esES', `Text`='¡Dime cómo nacieron los enanos y empieza por el principio!' WHERE (`CreatureID`='28070') AND (`GroupID`='20') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28070', `GroupID`='21', `ID`='0', `Locale`='esES', `Text`='Vale, vale... sé que los terráneos estaban hechos con piedra para dar forma a las regiones más profundas del mundo. ¿Pero, qué pasa con las anomalías? ¿Matriz no estabilizada y qué más?' WHERE (`CreatureID`='28070') AND (`GroupID`='21') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28070', `GroupID`='22', `ID`='0', `Locale`='esES', `Text`='Necro...qué...demo… habla en maldito común, ¿quieres?' WHERE (`CreatureID`='28070') AND (`GroupID`='22') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28070', `GroupID`='23', `ID`='0', `Locale`='esES', `Text`='¿Dioses antiguos, eh? Así que lanzaron a los terráneos esta maldición de la carne... ¿y después qué?' WHERE (`CreatureID`='28070') AND (`GroupID`='23') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28070', `GroupID`='24', `ID`='0', `Locale`='esES', `Text`='Si hubieran matado a los dioses antiguos, Azeroth estaría destruido...' WHERE (`CreatureID`='28070') AND (`GroupID`='24') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28070', `GroupID`='25', `ID`='0', `Locale`='esES', `Text`='¿Qué protectores?' WHERE (`CreatureID`='28070') AND (`GroupID`='25') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28070', `GroupID`='26', `ID`='0', `Locale`='esES', `Text`='Aesir y Vanir... Vale, entonces la Forja de los Deseos ha empezado a hacer nuevos terráneos... ¿pero qué les pasó a los viejos?' WHERE (`CreatureID`='28070') AND (`GroupID`='26') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28070', `GroupID`='27', `ID`='0', `Locale`='esES', `Text`='¡Alto! ¿Los Aesir y los Vanir fueron a la guerra? ¿Por qué?' WHERE (`CreatureID`='28070') AND (`GroupID`='27') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28070', `GroupID`='28', `ID`='0', `Locale`='esES', `Text`='Este \"Loken\" parece un personaje peligroso. Me alegro de que ya no tengamos que preocuparnos por él. Así que... si lo he entendido, los terráneos originales se despertaron de esa estasis y para cuando la desestabili...lo que sea... se habían convertido en enanos normales. O al menos... antepasados de enanos.' WHERE (`CreatureID`='28070') AND (`GroupID`='28') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28070', `GroupID`='29', `ID`='0', `Locale`='esES', `Text`='Oh, vaya… Eso es mucho que asimilar. Voy a necesitar algo de tiempo para digerirlo todo. Gracias.' WHERE (`CreatureID`='28070') AND (`GroupID`='29') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28070', `GroupID`='30', `ID`='0', `Locale`='esES', `Text`='¡¿Loken?! Ya me estoy hartando... puede que hayamos neutralizado a los enanos férreos, ¡pero apostaría a que en otra parte hay otra máquina escupiendo un montón de esos vrykuls férreos!' WHERE (`CreatureID`='28070') AND (`GroupID`='30') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28070', `GroupID`='31', `ID`='0', `Locale`='esES', `Text`='Usaré la forja para hacer terráneos que harán guardia... ¡Pero nuestro gran desafío continúa: encontrar y detener a Loken!' WHERE (`CreatureID`='28070') AND (`GroupID`='31') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28070', `GroupID`='32', `ID`='0', `Locale`='esES', `Text`='Es hora de ver qué hay detrás de la puerta cercana a la entrada. Voy a infiltrarme por allí, con cuidado y en silencio. Reúnete conmigo en la puerta y haré que entremos.' WHERE (`CreatureID`='28070') AND (`GroupID`='32') AND (`ID`='0');

-- Sjonnir el Afilador --
UPDATE `creature_text_locale` SET `CreatureID`='27978', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='Suaves y vulnerables caparazones. Breves y frágiles vidas. ¡No podéis escapar de la maldición de la carne!' WHERE (`CreatureID`='27978') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27978', `GroupID`='1', `ID`='0', `Locale`='esES', `Text`='¡La carne no es rival para el hierro!' WHERE (`CreatureID`='27978') AND (`GroupID`='1') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27978', `GroupID`='1', `ID`='1', `Locale`='esES', `Text`='¡Los ejércitos de hierro asfixiarán el mundo!' WHERE (`CreatureID`='27978') AND (`GroupID`='1') AND (`ID`='1');
UPDATE `creature_text_locale` SET `CreatureID`='27978', `GroupID`='1', `ID`='2', `Locale`='esES', `Text`='Anulado.' WHERE (`CreatureID`='27978') AND (`GroupID`='1') AND (`ID`='2');
UPDATE `creature_text_locale` SET `CreatureID`='27978', `GroupID`='2', `ID`='0', `Locale`='esES', `Text`='Loken no descansará... ¡hasta que recupere la forja! ¡No cambiaréis... nada!' WHERE (`CreatureID`='27978') AND (`GroupID`='2') AND (`ID`='0');

-- Kaddrak --
UPDATE `creature_text_locale` SET `CreatureID`='30898', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='Incumplimiento del código de seguridad en progreso. Análisis de los archivos históricos relegado a la cola de menor prioridad. Contramedidas activadas.' WHERE (`CreatureID`='30898') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='30898', `GroupID`='1', `ID`='0', `Locale`='esES', `Text`='Accediendo... los creadores llegaron para extirpar la infección simbiótica. La investigación reveló que la infestación del dios antiguo se había vuelto maligna. Extirpar los parásitos daría como resultado la pérdida del anfitrión...' WHERE (`CreatureID`='30898') AND (`GroupID`='1') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='30898', `GroupID`='2', `ID`='0', `Locale`='esES', `Text`='Correcto. Los creadores neutralizaron la amenaza parasitaria y la contuvieron en el anfitrión. La Forja de los Deseos y otros sistemas fueron diseñados para crear nuevos terráneos. Se implementaron salvaguardas y se designaron protectores.' WHERE (`CreatureID`='30898') AND (`GroupID`='2') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='30898', `GroupID`='3', `ID`='0', `Locale`='esES', `Text`='Designaciones: Aesir y Vanir. O en la nomenclatura común, gigantes de la tormenta y la tierra. El centinela Loken fue designado supremo. Los dragones Aspectos fueron enviados a vigilar la evolución en Azeroth.' WHERE (`CreatureID`='30898') AND (`GroupID`='3') AND (`ID`='0');

-- Abedneum --
UPDATE `creature_text_locale` SET `CreatureID`='30899', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='Aviso: patrón de forma de vida no reconocido. Procedimiento de archivado finalizado. Si la interferencia continúa, el responsable será marcado como objetivo.' WHERE (`CreatureID`='30899') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='30899', `GroupID`='1', `ID`='0', `Locale`='esES', `Text`='Índice de amenaza crítico. Análisis del vacío desviado. Iniciando protocolo de higienización.' WHERE (`CreatureID`='30899') AND (`GroupID`='1') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='30899', `GroupID`='2', `ID`='0', `Locale`='esES', `Text`='Alerta: sistema de seguridad desactivado. Comenzando purga de memoria y...' WHERE (`CreatureID`='30899') AND (`GroupID`='2') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='30899', `GroupID`='3', `ID`='0', `Locale`='esES', `Text`='Sistema en línea. Patrón de forma de vida reconocido. Bienvenido, Branbronzan. ¿Petición?' WHERE (`CreatureID`='30899') AND (`GroupID`='3') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='30899', `GroupID`='4', `ID`='0', `Locale`='esES', `Text`='Accediendo a datos prehistóricos... recuperados. En el comienzo, los terráneos fueron creados para...' WHERE (`CreatureID`='30899') AND (`GroupID`='4') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='30899', `GroupID`='5', `ID`='0', `Locale`='esES', `Text`='Accediendo... En las primeras etapas de su ciclo de desarrollo, simbiontes parasitarios necrofóbicos infectaron Azeroth.' WHERE (`CreatureID`='30899') AND (`GroupID`='5') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='30899', `GroupID`='6', `ID`='0', `Locale`='esES', `Text`='Designación: Dioses antiguos. Los dioses antiguos inutilizaron todos los sistemas, incluyendo los terráneos, para facilitar la asimilación. Esta matriz de desestabilización ha sido denominada \"la maldición de la carne\". Los efectos de la desestabilización aumentaron con el paso del tiempo.' WHERE (`CreatureID`='30899') AND (`GroupID`='6') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='30899', `GroupID`='7', `ID`='0', `Locale`='esES', `Text`='Aceptado, Branbronzan. Sesión finalizada.' WHERE (`CreatureID`='30899') AND (`GroupID`='7') AND (`ID`='0');

-- Marnak --
UPDATE `creature_text_locale` SET `CreatureID`='30897', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='Límite de índice de amenaza superado. Archivo celestial cancelado. Nivel de seguridad aumentado.' WHERE (`CreatureID`='30897') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='30897', `GroupID`='1', `ID`='0', `Locale`='esES', `Text`='Hay trasfondo adicional relevante a tu solicitud: siguiendo el combate global entre Aesir y Vanir...' WHERE (`CreatureID`='30897') AND (`GroupID`='1') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='30897', `GroupID`='2', `ID`='0', `Locale`='esES', `Text`='Desconocido. Los datos sugieren que el ímpetu del combate original con el principal designado Loken, que neutralizó a los Aesir y Vanir restantes, afectó al final del conflicto. El principal designado Loken comenzó la estasis de varias semillas de razas, incluyendo terráneos, gigantes y vrykul en instalaciones de contención designadas.' WHERE (`CreatureID`='30897') AND (`GroupID`='2') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='30897', `GroupID`='3', `ID`='0', `Locale`='esES', `Text`='Eso es esencialmente correcto.' WHERE (`CreatureID`='30897') AND (`GroupID`='3') AND (`ID`='0');