
-- EL OCULUS --

-- Drakos el Interrogador --
UPDATE `creature_text_locale` SET `CreatureID`='27654', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='¡Los prisioneros no serán liberados! ¡La palabra de Malygos es ley!' WHERE (`CreatureID`='27654') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27654', `GroupID`='1', `ID`='0', `Locale`='esES', `Text`='Un castigo apropiado.' WHERE (`CreatureID`='27654') AND (`GroupID`='1') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27654', `GroupID`='1', `ID`='1', `Locale`='esES', `Text`='¡Sentencia ejecutada!' WHERE (`CreatureID`='27654') AND (`GroupID`='1') AND (`ID`='1');
UPDATE `creature_text_locale` SET `CreatureID`='27654', `GroupID`='1', `ID`='2', `Locale`='esES', `Text`='¡Otra baja de guerra!' WHERE (`CreatureID`='27654') AND (`GroupID`='1') AND (`ID`='2');
UPDATE `creature_text_locale` SET `CreatureID`='27654', `GroupID`='2', `ID`='0', `Locale`='esES', `Text`='La guerra... continúa.' WHERE (`CreatureID`='27654') AND (`GroupID`='2') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27654', `GroupID`='3', `ID`='0', `Locale`='esES', `Text`='¡Es demasiado tarde para correr!' WHERE (`CreatureID`='27654') AND (`GroupID`='3') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27654', `GroupID`='3', `ID`='1', `Locale`='esES', `Text`='Reuníos...' WHERE (`CreatureID`='27654') AND (`GroupID`='3') AND (`ID`='1');
UPDATE `creature_text_locale` SET `CreatureID`='27654', `GroupID`='3', `ID`='2', `Locale`='esES', `Text`='¡Nadie escapará!' WHERE (`CreatureID`='27654') AND (`GroupID`='3') AND (`ID`='2');
UPDATE `creature_text_locale` SET `CreatureID`='27654', `GroupID`='3', `ID`='3', `Locale`='esES', `Text`='¡Os condeno a muerte!' WHERE (`CreatureID`='27654') AND (`GroupID`='3') AND (`ID`='3');
UPDATE `creature_text_locale` SET `CreatureID`='27654', `GroupID`='4', `ID`='0', `Locale`='esES', `Text`='¡Temblad, gusanos!' WHERE (`CreatureID`='27654') AND (`GroupID`='4') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27654', `GroupID`='4', `ID`='1', `Locale`='esES', `Text`='¡Os aplastaré!' WHERE (`CreatureID`='27654') AND (`GroupID`='4') AND (`ID`='1');
UPDATE `creature_text_locale` SET `CreatureID`='27654', `GroupID`='4', `ID`='2', `Locale`='esES', `Text`='¿Podéis volar?' WHERE (`CreatureID`='27654') AND (`GroupID`='4') AND (`ID`='2');

-- Varos Zancanubes --
UPDATE `creature_text_locale` SET `CreatureID`='27447', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='¡No habrá piedad!' WHERE (`CreatureID`='27447') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27447', `GroupID`='1', `ID`='1', `Locale`='esES', `Text`='¡Reventadlos! ¡Acabad con ellos!' WHERE (`CreatureID`='27447') AND (`GroupID`='1') AND (`ID`='1');
UPDATE `creature_text_locale` SET `CreatureID`='27447', `GroupID`='2', `ID`='2', `Locale`='esES', `Text`='¡%s llama a un capitán del anillo azur!' WHERE (`CreatureID`='27447') AND (`GroupID`='2') AND (`ID`='2');
UPDATE `creature_text_locale` SET `CreatureID`='27447', `GroupID`='3', `ID`='3', `Locale`='esES', `Text`='¡Son demasiado... fuertes! Hemos subestimado su... fortaleza.' WHERE (`CreatureID`='27447') AND (`GroupID`='3') AND (`ID`='3');
UPDATE `creature_text_locale` SET `CreatureID`='27447', `GroupID`='4', `ID`='0', `Locale`='esES', `Text`='Intrusos, vuestra victoria será efímera. Soy el comandante Varos Zancanubes. Mis dracos controlan el cielo y protegen este conducto. ¡Yo me encargaré personalmente de que El Oculus no caiga en vuestro poder!' WHERE (`CreatureID`='27447') AND (`GroupID`='4') AND (`ID`='0');

-- Urom --
UPDATE `creature_text_locale` SET `CreatureID`='27655', `GroupID`='2', `ID`='0', `Locale`='esES', `Text`='Seguís luchando. Seguís aferrándoos a principios erróneos. Si sobrevivís, me encontraréis en el anillo central.' WHERE (`CreatureID`='27655') AND (`GroupID`='2') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27655', `GroupID`='1', `ID`='0', `Locale`='esES', `Text`='Es evidente que mis mascotas han fracasado. Quizá sea necesaria otra demostración.' WHERE (`CreatureID`='27655') AND (`GroupID`='1') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27655', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='¿Qué tenemos aquí? ¿Aquellos que se atreven a desafiar al Tejehechizos? Aquellos a quienes les falta previsión y entendimiento. ¿Cómo puedo explicároslo? ¡Malygos está intentado salvar al mundo de sí mismo! ¡Bah! ¡No malgastéis mi tiempo!' WHERE (`CreatureID`='27655') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27655', `GroupID`='3', `ID`='0', `Locale`='esES', `Text`='¡Pobres necios ciegos!' WHERE (`CreatureID`='27655') AND (`GroupID`='3') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27655', `GroupID`='4', `ID`='0', `Locale`='esES', `Text`='¡%s comienza a lanzar Deflagración arcana potenciada!' WHERE (`CreatureID`='27655') AND (`GroupID`='4') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27655', `GroupID`='5', `ID`='0', `Locale`='esES', `Text`='Una muestra... ¡una pequeña muestra del poder del Tejehechizos!' WHERE (`CreatureID`='27655') AND (`GroupID`='5') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27655', `GroupID`='5', `ID`='1', `Locale`='esES', `Text`='Tanta energía inestable... ¡pero vale la pena correr el riesgo de destruiros!' WHERE (`CreatureID`='27655') AND (`GroupID`='5') AND (`ID`='1');
UPDATE `creature_text_locale` SET `CreatureID`='27655', `GroupID`='6', `ID`='0', `Locale`='esES', `Text`='Todo lo que he hecho... ha sido por Azeroth.' WHERE (`CreatureID`='27655') AND (`GroupID`='6') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27655', `GroupID`='7', `ID`='0', `Locale`='esES', `Text`='¡Si pudieras entenderlo!' WHERE (`CreatureID`='27655') AND (`GroupID`='7') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27655', `GroupID`='7', `ID`='1', `Locale`='esES', `Text`='Ahora lo ves, ¿verdad?' WHERE (`CreatureID`='27655') AND (`GroupID`='7') AND (`ID`='1');
UPDATE `creature_text_locale` SET `CreatureID`='27655', `GroupID`='7', `ID`='2', `Locale`='esES', `Text`='Desafortunado, pero necesario.' WHERE (`CreatureID`='27655') AND (`GroupID`='7') AND (`ID`='2');

-- Eregos --
UPDATE `creature_text_locale` SET `CreatureID`='27656', `GroupID`='1', `ID`='0', `Locale`='esES', `Text`='¡Entrometidos descarados, estáis fuera de vuestro elemento! ¡Os enterraré!' WHERE (`CreatureID`='27656') AND (`GroupID`='1') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27656', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='¡Simplones! No podéis comprender las fuerzas que habéis puesto en marcha. ¡El conducto de líneas Ley no será interrumpido! ¡Vuestra derrota será total!' WHERE (`CreatureID`='27656') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27656', `GroupID`='2', `ID`='0', `Locale`='esES', `Text`='Tanta insolencia... tanta arrogancia... ¡deben ser CASTIGADAS!' WHERE (`CreatureID`='27656') AND (`GroupID`='2') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27656', `GroupID`='3', `ID`='0', `Locale`='esES', `Text`='Hay mucha caída...' WHERE (`CreatureID`='27656') AND (`GroupID`='3') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27656', `GroupID`='3', `ID`='1', `Locale`='esES', `Text`='¡Vuelve a la tierra!' WHERE (`CreatureID`='27656') AND (`GroupID`='3') AND (`ID`='1');
UPDATE `creature_text_locale` SET `CreatureID`='27656', `GroupID`='3', `ID`='2', `Locale`='esES', `Text`='¡Disfruta de la caída!' WHERE (`CreatureID`='27656') AND (`GroupID`='3') AND (`ID`='2');
UPDATE `creature_text_locale` SET `CreatureID`='27656', `GroupID`='4', `ID`='0', `Locale`='esES', `Text`='Saboread esta pequeña victoria, criaturitas insensatas. Vosotros y vuestros aliados dragones habéis ganado esta batalla, pero nosotros ganaremos la guerra de El Nexo.' WHERE (`CreatureID`='27656') AND (`GroupID`='4') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27656', `GroupID`='5', `ID`='0', `Locale`='esES', `Text`='¡Mandamos sobre lo Arcano! ¡No se puede usar contra nosotros!' WHERE (`CreatureID`='27656') AND (`GroupID`='5') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27656', `GroupID`='5', `ID`='1', `Locale`='esES', `Text`='¡Es absurdo intentar extinguir tu fuego!' WHERE (`CreatureID`='27656') AND (`GroupID`='5') AND (`ID`='1');
UPDATE `creature_text_locale` SET `CreatureID`='27656', `GroupID`='5', `ID`='2', `Locale`='esES', `Text`='¡La magia de la naturaleza no os ayudará ahora!' WHERE (`CreatureID`='27656') AND (`GroupID`='5') AND (`ID`='2');

-- Draco ámbar --
UPDATE `creature_text_locale` SET `CreatureID`='27755', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='¡%s se aleja volando!' WHERE (`CreatureID`='27755') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27755', `GroupID`='1', `ID`='0', `Locale`='esES', `Text`='Te doy la bienvenida, colega. ¡Mantén la cabeza agachada y agárrate bien!' WHERE (`CreatureID`='27755') AND (`GroupID`='1') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27755', `GroupID`='2', `ID`='0', `Locale`='esES', `Text`='Usa la Lanza de choque para dañar a los enemigos. Si nos metemos en problemas, Parar tiempo congelará en su sitio a todos los enemigos, ¡entonces dales con la Lanza de choque para hacer mucho daño!' WHERE (`CreatureID`='27755') AND (`GroupID`='2') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27755', `GroupID`='3', `ID`='0', `Locale`='esES', `Text`='Ahora que tengo todo mi poder, puedo utilizar Falla temporal. Puedes usarlo para hacer que los enemigos sufran daño adicional y conseguir Cargas de choque. ¡Guárdalas y después usa la Lanza de choque para hacer un daño enorme!' WHERE (`CreatureID`='27755') AND (`GroupID`='3') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27755', `GroupID`='4', `ID`='0', `Locale`='esES', `Text`='¡Estoy malherido! ¡No podré soportarlo mucho más!' WHERE (`CreatureID`='27755') AND (`GroupID`='4') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27755', `GroupID`='5', `ID`='0', `Locale`='esES', `Text`='Quedan $3486W ensamblajes de centrifugadora. Debemos encontrar el modo de destruirlos para desactivar el escudo protector de Varos Zancanubes. Los ensamblajes deberían estar a medio camino hacia la cima de El Oculus, en el Anillo de Aceleración.' WHERE (`CreatureID`='27755') AND (`GroupID`='5') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27755', `GroupID`='6', `ID`='0', `Locale`='esES', `Text`='Queda un ensamblaje de centrifugadora. Debemos encontrar el modo de destruirlo para desactivar el escudo protector de Varos Zancanubes. El ensamblaje debería estar a medio camino hacia la cima de El Oculus, en el Anillo de Aceleración.' WHERE (`CreatureID`='27755') AND (`GroupID`='6') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27755', `GroupID`='7', `ID`='0', `Locale`='esES', `Text`='¡El escudo está desconectado, Varos es vulnerable! Al vencerle, los guardianes del anillo azur deberían dispersarse y permitirnos acceder a los anillos superiores. Varos se encuentra sobre una plataforma flotante a medio camino hacia la cima del Oculus, en el Anillo de Aceleración.' WHERE (`CreatureID`='27755') AND (`GroupID`='7') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27755', `GroupID`='8', `ID`='0', `Locale`='esES', `Text`='El Señor de la magia Urom es nuestro siguiente objetivo. Se esconde en una de las plataformas flotantes del Anillo de Transmutación, cerca de la cima del Oculus. Mucho ojo: Urom es un conjurador muy poderoso y puede que no esté solo.' WHERE (`CreatureID`='27755') AND (`GroupID`='8') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27755', `GroupID`='9', `ID`='0', `Locale`='esES', `Text`='El Guardián-Ley Eregos es lo único que se interpone entre nosotros y el control del Oculus. Él sobrevuela el Anillo de Alineación, en lo más alto del Oculus. El poder de Eregos es increíble, quédate sobre mí cuando nos enfrentemos a él y deja que luche yo.' WHERE (`CreatureID`='27755') AND (`GroupID`='9') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27755', `GroupID`='10', `ID`='0', `Locale`='esES', `Text`='Hemos arrebatado el control del Oculus a los ejércitos de Malygos. No estás perdiendo peso, $gpequeño:pequeña;. Mis alas ansían el cielo abierto.' WHERE (`CreatureID`='27755') AND (`GroupID`='10') AND (`ID`='0');

-- Draco rubí --
UPDATE `creature_text_locale` SET `CreatureID`='27756', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='¡%s se aleja volando!' WHERE (`CreatureID`='27756') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27756', `GroupID`='1', `ID`='0', `Locale`='esES', `Text`='Te doy la bienvenida, colega. ¡Mantén la cabeza agachada y agárrate bien!' WHERE (`CreatureID`='27756') AND (`GroupID`='1') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27756', `GroupID`='2', `ID`='0', `Locale`='esES', `Text`='Para dañar a los enemigos utiliza Cólera abrasadora y si empiezo a recibir daño, usa Maniobras evasivas. ¡Recuerda que para poder usar las Maniobras evasivas debo acumular Cargas evasivas al recibir daño!' WHERE (`CreatureID`='27756') AND (`GroupID`='2') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27756', `GroupID`='3', `ID`='0', `Locale`='esES', `Text`='Ahora que tengo todo mi poder puedo realizar Mártir. Puedes usarlo para proteger a otros dracos, pero yo recibiré mucho daño, ¡así que asegúrate de usar Maniobras evasivas también!' WHERE (`CreatureID`='27756') AND (`GroupID`='3') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27756', `GroupID`='4', `ID`='0', `Locale`='esES', `Text`='¡Estoy malherido! ¡No podré soportarlo mucho más!' WHERE (`CreatureID`='27756') AND (`GroupID`='4') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27756', `GroupID`='5', `ID`='0', `Locale`='esES', `Text`='Quedan $3486W ensamblajes de centrifugadora. Debemos encontrar el modo de destruirlos para desactivar el escudo protector de Varos Zancanubes. Los ensamblajes deberían estar a medio camino hacia la cima de El Oculus, en el Anillo de Aceleración.' WHERE (`CreatureID`='27756') AND (`GroupID`='5') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27756', `GroupID`='6', `ID`='0', `Locale`='esES', `Text`='Queda un ensamblaje de centrifugadora. Debemos encontrar el modo de destruirlo para desactivar el escudo protector de Varos Zancanubes. El ensamblaje debería estar a medio camino hacia la cima de El Oculus, en el Anillo de Aceleración.' WHERE (`CreatureID`='27756') AND (`GroupID`='6') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27756', `GroupID`='7', `ID`='0', `Locale`='esES', `Text`='¡El escudo está desconectado, Varos es vulnerable! Al vencerle, los guardianes del anillo azur deberían dispersarse y permitirnos acceder a los anillos superiores. Varos se encuentra sobre una plataforma flotante a medio camino hacia la cima del Oculus, en el Anillo de Aceleración.' WHERE (`CreatureID`='27756') AND (`GroupID`='7') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27756', `GroupID`='8', `ID`='0', `Locale`='esES', `Text`='El Señor de la magia Urom es nuestro siguiente objetivo. Se esconde en una de las plataformas flotantes del Anillo de Transmutación, cerca de la cima del Oculus. Mucho ojo: Urom es un conjurador muy poderoso y puede que no esté solo.' WHERE (`CreatureID`='27756') AND (`GroupID`='8') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27756', `GroupID`='9', `ID`='0', `Locale`='esES', `Text`='El Guardián-Ley Eregos es lo único que se interpone entre nosotros y el control del Oculus. Él sobrevuela el Anillo de Alineación, en lo más alto del Oculus. El poder de Eregos es increíble, quédate sobre mí cuando nos enfrentemos a él y deja que luche yo.' WHERE (`CreatureID`='27756') AND (`GroupID`='9') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27756', `GroupID`='10', `ID`='0', `Locale`='esES', `Text`='Hemos arrebatado el control del Oculus a los ejércitos de Malygos. No estás perdiendo peso, $gpequeño:pequeña;. Mis alas ansían el cielo abierto.' WHERE (`CreatureID`='27756') AND (`GroupID`='10') AND (`ID`='0');

-- Draco esmeralda --
UPDATE `creature_text_locale` SET `CreatureID`='27692', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='¡%s se aleja volando!' WHERE (`CreatureID`='27692') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27692', `GroupID`='1', `ID`='0', `Locale`='esES', `Text`='Te doy la bienvenida, colega. ¡Mantén la cabeza agachada y agárrate bien!' WHERE (`CreatureID`='27692') AND (`GroupID`='1') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27692', `GroupID`='2', `ID`='0', `Locale`='esES', `Text`='Usa el Veneno parasitante para dañar a los enemigos y mantenerme sano. Tocar la pesadilla es muy poderoso, pero me hace daño, ¡así que úsalo solo cuando tenga mucha salud!' WHERE (`CreatureID`='27692') AND (`GroupID`='2') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27692', `GroupID`='3', `ID`='0', `Locale`='esES', `Text`='Ahora que tengo todo mi poder, puedo utilizar Cauce de sueño. Puedes emplearlo para sanar a otros dracos, pero drena mi salud, ¡así que asegúrate de que también usas el Veneno parasitante!' WHERE (`CreatureID`='27692') AND (`GroupID`='3') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27692', `GroupID`='4', `ID`='0', `Locale`='esES', `Text`='¡Estoy malherido! ¡No podré soportarlo mucho más!' WHERE (`CreatureID`='27692') AND (`GroupID`='4') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27692', `GroupID`='5', `ID`='0', `Locale`='esES', `Text`='Quedan $3486W ensamblajes de centrifugadora. Debemos encontrar el modo de destruirlos para desactivar el escudo protector de Varos Zancanubes. Los ensamblajes deberían estar a medio camino hacia la cima de El Oculus, en el Anillo de Aceleración.' WHERE (`CreatureID`='27692') AND (`GroupID`='5') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27692', `GroupID`='6', `ID`='0', `Locale`='esES', `Text`='Queda un ensamblaje de centrifugadora. Debemos encontrar el modo de destruirlo para desactivar el escudo protector de Varos Zancanubes. El ensamblaje debería estar a medio camino hacia la cima de El Oculus, en el Anillo de Aceleración.' WHERE (`CreatureID`='27692') AND (`GroupID`='6') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27692', `GroupID`='7', `ID`='0', `Locale`='esES', `Text`='¡El escudo está desconectado, Varos es vulnerable! Al vencerle, los guardianes del anillo azur deberían dispersarse y permitirnos acceder a los anillos superiores. Varos se encuentra sobre una plataforma flotante a medio camino hacia la cima del Oculus, en el Anillo de Aceleración.' WHERE (`CreatureID`='27692') AND (`GroupID`='7') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27692', `GroupID`='8', `ID`='0', `Locale`='esES', `Text`='El Señor de la magia Urom es nuestro siguiente objetivo. Se esconde en una de las plataformas flotantes del Anillo de Transmutación, cerca de la cima del Oculus. Mucho ojo: Urom es un conjurador muy poderoso y puede que no esté solo.' WHERE (`CreatureID`='27692') AND (`GroupID`='8') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27692', `GroupID`='9', `ID`='0', `Locale`='esES', `Text`='El Guardián-Ley Eregos es lo único que se interpone entre nosotros y el control del Oculus. Él sobrevuela el Anillo de Alineación, en lo más alto del Oculus. El poder de Eregos es increíble, quédate sobre mí cuando nos enfrentemos a él y deja que luche yo.' WHERE (`CreatureID`='27692') AND (`GroupID`='9') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='27692', `GroupID`='10', `ID`='0', `Locale`='esES', `Text`='Hemos arrebatado el control del Oculus a los ejércitos de Malygos. No estás perdiendo peso, $gpequeño:pequeña;. Mis alas ansían el cielo abierto.' WHERE (`CreatureID`='27692') AND (`GroupID`='10') AND (`ID`='0');

-- Belgaristrasz --
UPDATE `creature_text_locale` SET `CreatureID`='27658', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='Gracias por liberarnos, mortales. Tened cuidado, el Vuelo Azul ha sido alertado de vuestra presencia. Mientras hablamos, Malygos envía a Varos Zancanubes y a sus guardianes del anillo para defender El Oculus. Necesitaréis nuestra ayuda o no tendréis nada que hacer.' WHERE (`CreatureID`='27658') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28012', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='El tramposo Señor de la magia Urom protege el tercer anillo. Aparecerá solo e indefenso, ¡pero que no te engañen las apariencias! Urom es un poderoso conjurador que dirige un grupo de criaturas fantasmales. Búscale arriba.' WHERE (`CreatureID`='28012') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='28012', `GroupID`='1', `ID`='1', `Locale`='esES', `Text`='El mayor de tus desafíos aún está por llegar. El Guardián-Ley Eregos es un dragón Azul de inmenso poder. Lo encontrarás sobrevolando el anillo superior.' WHERE (`CreatureID`='28012') AND (`GroupID`='1') AND (`ID`='1');