
-- FOSO DE SARON --

/* Textos faltantes en la base de datos.

-- Señor de la Plaga Tyrannus --
Han entrado intrusos en el dominio del maestro. ¡Sonad la alarma!
Ummm, carnaza. Ni siquiera servís para trabajar en la cantera. Saboread estos últimos momentos, pues pronto no seréis más que no-muertos descerebrados.
Vuestro último recuerdo en vida será un dolor lleno de agonía.
Esbirros, ¡destruid a estos intrusos!

-- Lady Jaina Valiente y misma versión para Sylvanas --
¡Héroes de la Alianza, al ataque!
¡NO! ¡MONSTRUO!
Cumplo con mi deber. Perdonadme, nobles soldados...
Tendréis que atravesar esa cantera por vuestra cuenta.
Liberad a los esclavos de la Alianza que os encontréis. Seguramente necesitemos su ayuda en la batalla contra Tyrannus. Reuniré refuerzos y nos veremos al otro lado de la cantera.

-- Martin Victus: después de maestro forja y evento final --

*/

-- Maestro de forja Gargelus --
UPDATE `creature_text_locale` SET `CreatureID`='36494', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='Bichejos a mis pies. ¡Traéis a Gargelus cosas ricas para comer!' WHERE (`CreatureID`='36494') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36494', `GroupID`='1', `ID`='0', `Locale`='esES', `Text`='Hacha floja. Gargelus hace mejor y APLASTA.' WHERE (`CreatureID`='36494') AND (`GroupID`='1') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36494', `GroupID`='2', `ID`='0', `Locale`='esES', `Text`='Gargelus cansado de débiles mortales. ¡Ahora huesos se hielan!' WHERE (`CreatureID`='36494') AND (`GroupID`='2') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36494', `GroupID`='3', `ID`='0', `Locale`='esES', `Text`='Gargelus espera llevar calzones limpios. Mucha vergüenza si no. Luego.' WHERE (`CreatureID`='36494') AND (`GroupID`='3') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36494', `GroupID`='4', `ID`='0', `Locale`='esES', `Text`='Guardaré para comer. Luego.' WHERE (`CreatureID`='36494') AND (`GroupID`='4') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36494', `GroupID`='4', `ID`='1', `Locale`='esES', `Text`='Este no tan rico para comer ahora. ¡Gargelus tonto! ¡MALO! ¡MALO!' WHERE (`CreatureID`='36494') AND (`GroupID`='4') AND (`ID`='1');
UPDATE `creature_text_locale` SET `CreatureID`='36494', `GroupID`='5', `ID`='0', `Locale`='esES', `Text`='¡%s te lanza un pedrusco de saronita enorme!' WHERE (`CreatureID`='36494') AND (`GroupID`='5') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36494', `GroupID`='6', `ID`='0', `Locale`='esES', `Text`='%s lanza |cFF00AACCCongelación profunda|r sobre $n.' WHERE (`CreatureID`='36494') AND (`GroupID`='6') AND (`ID`='0');

-- Puagh --
UPDATE `creature_text_locale` SET `CreatureID`='36477', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='¡No se debe interrumpir nuestro trabajo! ¡Agh, ocúpate de ellos!' WHERE (`CreatureID`='36477') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36477', `GroupID`='1', `ID`='0', `Locale`='esES', `Text`='Seguro que podríamos usar estos trozos.' WHERE (`CreatureID`='36477') AND (`GroupID`='1') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36477', `GroupID`='1', `ID`='1', `Locale`='esES', `Text`='¡El suministro de piernas y brazos escasea! ¡Gracias por tu aportación!' WHERE (`CreatureID`='36477') AND (`GroupID`='1') AND (`ID`='1');
UPDATE `creature_text_locale` SET `CreatureID`='36477', `GroupID`='2', `ID`='0', `Locale`='esES', `Text`='¡Deja de moverte! Quieto mientras los estallo a todos.' WHERE (`CreatureID`='36477') AND (`GroupID`='2') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36477', `GroupID`='3', `ID`='0', `Locale`='esES', `Text`='¡%s comienza a invocar minas explosivas!' WHERE (`CreatureID`='36477') AND (`GroupID`='3') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36477', `GroupID`='4', `ID`='0', `Locale`='esES', `Text`='¡Rápido! Envenénalos mientras están cerca.' WHERE (`CreatureID`='36477') AND (`GroupID`='4') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36477', `GroupID`='5', `ID`='0', `Locale`='esES', `Text`='¡No, ese! ¡Ese! ¡Ve a por ese!' WHERE (`CreatureID`='36477') AND (`GroupID`='5') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36477', `GroupID`='5', `ID`='1', `Locale`='esES', `Text`='He cambiado de idea, ¡a por ese mejor!' WHERE (`CreatureID`='36477') AND (`GroupID`='5') AND (`ID`='1');
UPDATE `creature_text_locale` SET `CreatureID`='36477', `GroupID`='5', `ID`='2', `Locale`='esES', `Text`='¿Para qué lo atacas? ¡El peligroso está ahí, idiota!' WHERE (`CreatureID`='36477') AND (`GroupID`='5') AND (`ID`='2');
UPDATE `creature_text_locale` SET `CreatureID`='36477', `GroupID`='6', `ID`='0', `Locale`='esES', `Text`='¡Esperad! ¡Parad! No me matéis, por favor. Os contaré todo.' WHERE (`CreatureID`='36477') AND (`GroupID`='6') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36477', `GroupID`='7', `ID`='0', `Locale`='esES', `Text`='Lo que buscáis se encuentra en la guarida del maestro, pero debéis acabar con Tyrannus para entrar. Dentro de las Cámaras de Reflexión encontraréis a la Agonía de Escarcha. Ella... ella esconde la verdad.' WHERE (`CreatureID`='36477') AND (`GroupID`='7') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36477', `GroupID`='8', `ID`='0', `Locale`='esES', `Text`='¡Os juro que es cierto! Por favor, ¡¡no me matéis!!' WHERE (`CreatureID`='36477') AND (`GroupID`='8') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36477', `GroupID`='9', `ID`='0', `Locale`='esES', `Text`='Urgh... ¡No!' WHERE (`CreatureID`='36477') AND (`GroupID`='9') AND (`ID`='0');

-- Agh --
UPDATE `creature_text_locale` SET `CreatureID`='36476', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='¡%s comienza a desatar una nube de veneno tóxica!' WHERE (`CreatureID`='36476') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36476', `GroupID`='1', `ID`='0', `Locale`='esES', `Text`='¡%s te persigue! ¡Corre!' WHERE (`CreatureID`='36476') AND (`GroupID`='1') AND (`ID`='0');

-- Señor de la Plaga Tyrannus --
UPDATE `creature_text_locale` SET `CreatureID`='36794', `GroupID`='1', `ID`='0', `Locale`='esES', `Text`='¡Bicho asqueroso! ¡La muerte es lo que te espera!' WHERE (`CreatureID`='36794') AND (`GroupID`='1') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36794', `GroupID`='2', `ID`='0', `Locale`='esES', `Text`='No creáis que os voy a permitir la entrada al sagrario de mi maestro tan fácilmente. Seguid si osáis.' WHERE (`CreatureID`='36794') AND (`GroupID`='2') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36794', `GroupID`='3', `ID`='0', `Locale`='esES', `Text`='Dientefrío, ¡atrápalos en el túnel! ¡ENTIÉRRALOS VIVOS!' WHERE (`CreatureID`='36794') AND (`GroupID`='3') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36658', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='Otro ocupará su lugar. Perdéis el tiempo.' WHERE (`CreatureID`='36658') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36658', `GroupID`='3', `ID`='0', `Locale`='esES', `Text`='Vuestra búsqueda será en vano, intrusos, pues el Rey Exánime ha puesto un ejército de no-muertos a mis órdenes. ¡Mirad!' WHERE (`CreatureID`='36658') AND (`GroupID`='3') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36658', `GroupID`='4', `ID`='0', `Locale`='esES', `Text`='¡Gusanos persistentes! No alcanzaréis la entrada de la guarida de mi señor. ¡Soldados, destruidlos!' WHERE (`CreatureID`='36658') AND (`GroupID`='4') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36658', `GroupID`='5', `ID`='0', `Locale`='esES', `Text`='Dientefrío, ¡atrápalos en el túnel! ¡ENTIÉRRALOS VIVOS!' WHERE (`CreatureID`='36658') AND (`GroupID`='5') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36658', `GroupID`='6', `ID`='0', `Locale`='esES', `Text`='¡Ay! Valientes aventureros, vuestra intromisión ha llegado a su fin. ¿Oís el ruido de huesos y acero acercándose por ese túnel? Es el sonido de vuestra inminente muerte.' WHERE (`CreatureID`='36658') AND (`GroupID`='6') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36658', `GroupID`='7', `ID`='0', `Locale`='esES', `Text`='Ja, un gesto tan divertido de la multitud. Cuando haya terminado con vosotros, la espada de mi maestro se alimentará de vuestras almas. ¡Morid!' WHERE (`CreatureID`='36658') AND (`GroupID`='7') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36658', `GroupID`='8', `ID`='0', `Locale`='esES', `Text`='No fallaré al Rey Exánime. ¡Venid a conocer vuestro final!' WHERE (`CreatureID`='36658') AND (`GroupID`='8') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36658', `GroupID`='9', `ID`='0', `Locale`='esES', `Text`='Qué vergüenza. ¡Estás mejor muerto!' WHERE (`CreatureID`='36658') AND (`GroupID`='9') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36658', `GroupID`='9', `ID`='1', `Locale`='esES', `Text`='Quizá deberías haberte quedado... ¡en las montañas!' WHERE (`CreatureID`='36658') AND (`GroupID`='9') AND (`ID`='1');
UPDATE `creature_text_locale` SET `CreatureID`='36658', `GroupID`='10', `ID`='0', `Locale`='esES', `Text`='Imposible... Dientefrío... Avisa...' WHERE (`CreatureID`='36658') AND (`GroupID`='10') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36658', `GroupID`='11', `ID`='0', `Locale`='esES', `Text`='¡Dientefrío, destruye a este insensato!' WHERE (`CreatureID`='36658') AND (`GroupID`='11') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36658', `GroupID`='12', `ID`='0', `Locale`='esES', `Text`='¡La vermis de escarcha Dientefrío mira a $n y prepara un helado ataque!' WHERE (`CreatureID`='36658') AND (`GroupID`='12') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36658', `GroupID`='13', `ID`='0', `Locale`='esES', `Text`='Poder... ¡sobrecogedor!' WHERE (`CreatureID`='36658') AND (`GroupID`='13') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36658', `GroupID`='14', `ID`='0', `Locale`='esES', `Text`='¡%s gruñe y se hincha con poder oscuro!' WHERE (`CreatureID`='36658') AND (`GroupID`='14') AND (`ID`='0');

-- Esclavos de la Alianza --
UPDATE `creature_text_locale` SET `CreatureID`='36764', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='¡Qué gusto da verte! No tienes ni idea.' WHERE (`CreatureID`='36764') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36764', `GroupID`='0', `ID`='1', `Locale`='esES', `Text`='%s deja que su pico de minería se arrastre por el suelo mientras se acerca, exhausto.' WHERE (`CreatureID`='36764') AND (`GroupID`='0') AND (`ID`='1');
UPDATE `creature_text_locale` SET `CreatureID`='36764', `GroupID`='0', `ID`='2', `Locale`='esES', `Text`='Te debo una larga noche bebiendo, $gamigo mío:amiga mía;.' WHERE (`CreatureID`='36764') AND (`GroupID`='0') AND (`ID`='2');
UPDATE `creature_text_locale` SET `CreatureID`='36764', `GroupID`='0', `ID`='3', `Locale`='esES', `Text`='Si con mi vida o muerte puedo devolverte el favor, lo haré.' WHERE (`CreatureID`='36764') AND (`GroupID`='0') AND (`ID`='3');
UPDATE `creature_text_locale` SET `CreatureID`='36764', `GroupID`='0', `ID`='4', `Locale`='esES', `Text`='Voy a volver al frente de la cantera. Mata a unos cuantos por mí.' WHERE (`CreatureID`='36764') AND (`GroupID`='0') AND (`ID`='4');
UPDATE `creature_text_locale` SET `CreatureID`='36764', `GroupID`='0', `ID`='5', `Locale`='esES', `Text`='Casi había perdido la esperanza.' WHERE (`CreatureID`='36764') AND (`GroupID`='0') AND (`ID`='5');
UPDATE `creature_text_locale` SET `CreatureID`='36764', `GroupID`='0', `ID`='6', `Locale`='esES', `Text`='Pensé que moriría en este foso. Gracias.' WHERE (`CreatureID`='36764') AND (`GroupID`='0') AND (`ID`='6');
UPDATE `creature_text_locale` SET `CreatureID`='36764', `GroupID`='0', `ID`='7', `Locale`='esES', `Text`='No dejes que ninguno viva.' WHERE (`CreatureID`='36764') AND (`GroupID`='0') AND (`ID`='7');
UPDATE `creature_text_locale` SET `CreatureID`='36764', `GroupID`='0', `ID`='8', `Locale`='esES', `Text`='Por favor, lleva a cabo nuestra venganza sobre el Señor de la Plaga.' WHERE (`CreatureID`='36764') AND (`GroupID`='0') AND (`ID`='8');
UPDATE `creature_text_locale` SET `CreatureID`='36764', `GroupID`='0', `ID`='9', `Locale`='esES', `Text`='Cuando mates al maestro del foso, escupe sobre su cadáver, ¿vale?' WHERE (`CreatureID`='36764') AND (`GroupID`='0') AND (`ID`='9');
UPDATE `creature_text_locale` SET `CreatureID`='36764', `GroupID`='0', `ID`='10', `Locale`='esES', `Text`='Había perdido la noción del tiempo en este maldito lugar. Da gusto verte, $gamigo:amiga;.' WHERE (`CreatureID`='36764') AND (`GroupID`='0') AND (`ID`='10');
UPDATE `creature_text_locale` SET `CreatureID`='36764', `GroupID`='0', `ID`='11', `Locale`='esES', `Text`='Demasiados morimos en este foso. Demasiados.' WHERE (`CreatureID`='36764') AND (`GroupID`='0') AND (`ID`='11');
UPDATE `creature_text_locale` SET `CreatureID`='36764', `GroupID`='0', `ID`='12', `Locale`='esES', `Text`='Me alegro tanto de que estés aquí. No habría aguantado mucho más.' WHERE (`CreatureID`='36764') AND (`GroupID`='0') AND (`ID`='12');
UPDATE `creature_text_locale` SET `CreatureID`='36764', `GroupID`='0', `ID`='13', `Locale`='esES', `Text`='Ahora viene mi venganza.' WHERE (`CreatureID`='36764') AND (`GroupID`='0') AND (`ID`='13');
UPDATE `creature_text_locale` SET `CreatureID`='36764', `GroupID`='0', `ID`='14', `Locale`='esES', `Text`='Te mereces un buen abrazo de hombres.' WHERE (`CreatureID`='36764') AND (`GroupID`='0') AND (`ID`='14');
UPDATE `creature_text_locale` SET `CreatureID`='36764', `GroupID`='0', `ID`='15', `Locale`='esES', `Text`='Algún día encontraré la manera de devolverte el favor, $ghéroe:heroína;.' WHERE (`CreatureID`='36764') AND (`GroupID`='0') AND (`ID`='15');
UPDATE `creature_text_locale` SET `CreatureID`='36764', `GroupID`='0', `ID`='16', `Locale`='esES', `Text`='No puedo creer lo que ven mis ojos. Gracias, muchas gracias.' WHERE (`CreatureID`='36764') AND (`GroupID`='0') AND (`ID`='16');
UPDATE `creature_text_locale` SET `CreatureID`='36764', `GroupID`='0', `ID`='17', `Locale`='esES', `Text`='%s asiente dando las gracias.' WHERE (`CreatureID`='36764') AND (`GroupID`='0') AND (`ID`='17');
UPDATE `creature_text_locale` SET `CreatureID`='36764', `GroupID`='0', `ID`='18', `Locale`='esES', `Text`='%s ofrece una sonrisa de agradecimiento.' WHERE (`CreatureID`='36764') AND (`GroupID`='0') AND (`ID`='18');
UPDATE `creature_text_locale` SET `CreatureID`='36764', `GroupID`='0', `ID`='19', `Locale`='esES', `Text`='%s casi se derrumba mientras camina dando tumbos hacia ti.' WHERE (`CreatureID`='36764') AND (`GroupID`='0') AND (`ID`='19');
UPDATE `creature_text_locale` SET `CreatureID`='36764', `GroupID`='0', `ID`='20', `Locale`='esES', `Text`='%s te mira fijamente un momento, está claro que le cuesta creer que seas real.' WHERE (`CreatureID`='36764') AND (`GroupID`='0') AND (`ID`='20');
UPDATE `creature_text_locale` SET `CreatureID`='36764', `GroupID`='0', `ID`='21', `Locale`='esES', `Text`='%s suelta una risita rápida y cínica sobre su fortuna.' WHERE (`CreatureID`='36764') AND (`GroupID`='0') AND (`ID`='21');
UPDATE `creature_text_locale` SET `CreatureID`='36764', `GroupID`='0', `ID`='22', `Locale`='esES', `Text`='%s levanta su mano vacía y brinda por ti.' WHERE (`CreatureID`='36764') AND (`GroupID`='0') AND (`ID`='22');
UPDATE `creature_text_locale` SET `CreatureID`='36764', `GroupID`='0', `ID`='23', `Locale`='esES', `Text`='%s cierra los ojos y saborea la libertad un instante.' WHERE (`CreatureID`='36764') AND (`GroupID`='0') AND (`ID`='23');
UPDATE `creature_text_locale` SET `CreatureID`='36764', `GroupID`='0', `ID`='24', `Locale`='esES', `Text`='Voy a volver para ayudar a liberar a los demás esclavos. Gracias de nuevo, $ghéroe:heroína;.' WHERE (`CreatureID`='36764') AND (`GroupID`='0') AND (`ID`='24');
UPDATE `creature_text_locale` SET `CreatureID`='36765', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='¡Qué gusto da verte! No tienes ni idea.' WHERE (`CreatureID`='36765') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36765', `GroupID`='0', `ID`='1', `Locale`='esES', `Text`='%s deja que su pico de minería se arrastre por el suelo mientras se acerca, exhausto.' WHERE (`CreatureID`='36765') AND (`GroupID`='0') AND (`ID`='1');
UPDATE `creature_text_locale` SET `CreatureID`='36765', `GroupID`='0', `ID`='2', `Locale`='esES', `Text`='Te debo una larga noche bebiendo, $gamigo mío:amiga mía;.' WHERE (`CreatureID`='36765') AND (`GroupID`='0') AND (`ID`='2');
UPDATE `creature_text_locale` SET `CreatureID`='36765', `GroupID`='0', `ID`='3', `Locale`='esES', `Text`='Si con mi vida o muerte puedo devolverte el favor, lo haré.' WHERE (`CreatureID`='36765') AND (`GroupID`='0') AND (`ID`='3');
UPDATE `creature_text_locale` SET `CreatureID`='36765', `GroupID`='0', `ID`='4', `Locale`='esES', `Text`='Voy a volver al frente de la cantera. Mata a unos cuantos por mí.' WHERE (`CreatureID`='36765') AND (`GroupID`='0') AND (`ID`='4');
UPDATE `creature_text_locale` SET `CreatureID`='36765', `GroupID`='0', `ID`='5', `Locale`='esES', `Text`='Casi había perdido la esperanza.' WHERE (`CreatureID`='36765') AND (`GroupID`='0') AND (`ID`='5');
UPDATE `creature_text_locale` SET `CreatureID`='36765', `GroupID`='0', `ID`='6', `Locale`='esES', `Text`='Pensé que moriría en este foso. Gracias.' WHERE (`CreatureID`='36765') AND (`GroupID`='0') AND (`ID`='6');
UPDATE `creature_text_locale` SET `CreatureID`='36765', `GroupID`='0', `ID`='7', `Locale`='esES', `Text`='No dejes que ninguno viva.' WHERE (`CreatureID`='36765') AND (`GroupID`='0') AND (`ID`='7');
UPDATE `creature_text_locale` SET `CreatureID`='36765', `GroupID`='0', `ID`='8', `Locale`='esES', `Text`='Por favor, lleva a cabo nuestra venganza sobre el Señor de la Plaga.' WHERE (`CreatureID`='36765') AND (`GroupID`='0') AND (`ID`='8');
UPDATE `creature_text_locale` SET `CreatureID`='36765', `GroupID`='0', `ID`='9', `Locale`='esES', `Text`='Cuando mates al maestro del foso, escupe sobre su cadáver, ¿vale?' WHERE (`CreatureID`='36765') AND (`GroupID`='0') AND (`ID`='9');
UPDATE `creature_text_locale` SET `CreatureID`='36765', `GroupID`='0', `ID`='10', `Locale`='esES', `Text`='Había perdido la noción del tiempo en este maldito lugar. Da gusto verte, $gamigo:amiga;.' WHERE (`CreatureID`='36765') AND (`GroupID`='0') AND (`ID`='10');
UPDATE `creature_text_locale` SET `CreatureID`='36765', `GroupID`='0', `ID`='11', `Locale`='esES', `Text`='Demasiados morimos en este foso. Demasiados.' WHERE (`CreatureID`='36765') AND (`GroupID`='0') AND (`ID`='11');
UPDATE `creature_text_locale` SET `CreatureID`='36765', `GroupID`='0', `ID`='12', `Locale`='esES', `Text`='Me alegro tanto de que estés aquí. No habría aguantado mucho más.' WHERE (`CreatureID`='36765') AND (`GroupID`='0') AND (`ID`='12');
UPDATE `creature_text_locale` SET `CreatureID`='36765', `GroupID`='0', `ID`='13', `Locale`='esES', `Text`='Ahora viene mi venganza.' WHERE (`CreatureID`='36765') AND (`GroupID`='0') AND (`ID`='13');
UPDATE `creature_text_locale` SET `CreatureID`='36765', `GroupID`='0', `ID`='14', `Locale`='esES', `Text`='Te mereces un buen abrazo de hombres.' WHERE (`CreatureID`='36765') AND (`GroupID`='0') AND (`ID`='14');
UPDATE `creature_text_locale` SET `CreatureID`='36765', `GroupID`='0', `ID`='15', `Locale`='esES', `Text`='Algún día encontraré la manera de devolverte el favor, $ghéroe:heroína;.' WHERE (`CreatureID`='36765') AND (`GroupID`='0') AND (`ID`='15');
UPDATE `creature_text_locale` SET `CreatureID`='36765', `GroupID`='0', `ID`='16', `Locale`='esES', `Text`='No puedo creer lo que ven mis ojos. Gracias, muchas gracias.' WHERE (`CreatureID`='36765') AND (`GroupID`='0') AND (`ID`='16');
UPDATE `creature_text_locale` SET `CreatureID`='36765', `GroupID`='0', `ID`='17', `Locale`='esES', `Text`='%s asiente dando las gracias.' WHERE (`CreatureID`='36765') AND (`GroupID`='0') AND (`ID`='17');
UPDATE `creature_text_locale` SET `CreatureID`='36765', `GroupID`='0', `ID`='18', `Locale`='esES', `Text`='%s ofrece una sonrisa de agradecimiento.' WHERE (`CreatureID`='36765') AND (`GroupID`='0') AND (`ID`='18');
UPDATE `creature_text_locale` SET `CreatureID`='36765', `GroupID`='0', `ID`='19', `Locale`='esES', `Text`='%s casi se derrumba mientras camina dando tumbos hacia ti.' WHERE (`CreatureID`='36765') AND (`GroupID`='0') AND (`ID`='19');
UPDATE `creature_text_locale` SET `CreatureID`='36765', `GroupID`='0', `ID`='20', `Locale`='esES', `Text`='%s te mira fijamente un momento, está claro que le cuesta creer que seas real.' WHERE (`CreatureID`='36765') AND (`GroupID`='0') AND (`ID`='20');
UPDATE `creature_text_locale` SET `CreatureID`='36765', `GroupID`='0', `ID`='21', `Locale`='esES', `Text`='%s suelta una risita rápida y cínica sobre su fortuna.' WHERE (`CreatureID`='36765') AND (`GroupID`='0') AND (`ID`='21');
UPDATE `creature_text_locale` SET `CreatureID`='36765', `GroupID`='0', `ID`='22', `Locale`='esES', `Text`='%s levanta su mano vacía y brinda por ti.' WHERE (`CreatureID`='36765') AND (`GroupID`='0') AND (`ID`='22');
UPDATE `creature_text_locale` SET `CreatureID`='36765', `GroupID`='0', `ID`='23', `Locale`='esES', `Text`='%s cierra los ojos y saborea la libertad un instante.' WHERE (`CreatureID`='36765') AND (`GroupID`='0') AND (`ID`='23');
UPDATE `creature_text_locale` SET `CreatureID`='36765', `GroupID`='0', `ID`='24', `Locale`='esES', `Text`='Voy a volver para ayudar a liberar a los demás esclavos. Gracias de nuevo, $ghéroe:heroína;.' WHERE (`CreatureID`='36765') AND (`GroupID`='0') AND (`ID`='24');
UPDATE `creature_text_locale` SET `CreatureID`='36766', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='¡Qué gusto da verte! No tienes ni idea.' WHERE (`CreatureID`='36766') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36766', `GroupID`='0', `ID`='1', `Locale`='esES', `Text`='%s deja que su pico de minería se arrastre por el suelo mientras se acerca, exhausto.' WHERE (`CreatureID`='36766') AND (`GroupID`='0') AND (`ID`='1');
UPDATE `creature_text_locale` SET `CreatureID`='36766', `GroupID`='0', `ID`='2', `Locale`='esES', `Text`='Te debo una larga noche bebiendo, $gamigo mío:amiga mía;.' WHERE (`CreatureID`='36766') AND (`GroupID`='0') AND (`ID`='2');
UPDATE `creature_text_locale` SET `CreatureID`='36766', `GroupID`='0', `ID`='3', `Locale`='esES', `Text`='Si con mi vida o muerte puedo devolverte el favor, lo haré.' WHERE (`CreatureID`='36766') AND (`GroupID`='0') AND (`ID`='3');
UPDATE `creature_text_locale` SET `CreatureID`='36766', `GroupID`='0', `ID`='4', `Locale`='esES', `Text`='Voy a volver al frente de la cantera. Mata a unos cuantos por mí.' WHERE (`CreatureID`='36766') AND (`GroupID`='0') AND (`ID`='4');
UPDATE `creature_text_locale` SET `CreatureID`='36766', `GroupID`='0', `ID`='5', `Locale`='esES', `Text`='Casi había perdido la esperanza.' WHERE (`CreatureID`='36766') AND (`GroupID`='0') AND (`ID`='5');
UPDATE `creature_text_locale` SET `CreatureID`='36766', `GroupID`='0', `ID`='6', `Locale`='esES', `Text`='Pensé que moriría en este foso. Gracias.' WHERE (`CreatureID`='36766') AND (`GroupID`='0') AND (`ID`='6');
UPDATE `creature_text_locale` SET `CreatureID`='36766', `GroupID`='0', `ID`='7', `Locale`='esES', `Text`='No dejes que ninguno viva.' WHERE (`CreatureID`='36766') AND (`GroupID`='0') AND (`ID`='7');
UPDATE `creature_text_locale` SET `CreatureID`='36766', `GroupID`='0', `ID`='8', `Locale`='esES', `Text`='Por favor, lleva a cabo nuestra venganza sobre el Señor de la Plaga.' WHERE (`CreatureID`='36766') AND (`GroupID`='0') AND (`ID`='8');
UPDATE `creature_text_locale` SET `CreatureID`='36766', `GroupID`='0', `ID`='9', `Locale`='esES', `Text`='Cuando mates al maestro del foso, escupe sobre su cadáver, ¿vale?' WHERE (`CreatureID`='36766') AND (`GroupID`='0') AND (`ID`='9');
UPDATE `creature_text_locale` SET `CreatureID`='36766', `GroupID`='0', `ID`='10', `Locale`='esES', `Text`='Había perdido la noción del tiempo en este maldito lugar. Da gusto verte, $gamigo:amiga;.' WHERE (`CreatureID`='36766') AND (`GroupID`='0') AND (`ID`='10');
UPDATE `creature_text_locale` SET `CreatureID`='36766', `GroupID`='0', `ID`='11', `Locale`='esES', `Text`='Demasiados morimos en este foso. Demasiados.' WHERE (`CreatureID`='36766') AND (`GroupID`='0') AND (`ID`='11');
UPDATE `creature_text_locale` SET `CreatureID`='36766', `GroupID`='0', `ID`='12', `Locale`='esES', `Text`='Me alegro tanto de que estés aquí. No habría aguantado mucho más.' WHERE (`CreatureID`='36766') AND (`GroupID`='0') AND (`ID`='12');
UPDATE `creature_text_locale` SET `CreatureID`='36766', `GroupID`='0', `ID`='13', `Locale`='esES', `Text`='Ahora viene mi venganza.' WHERE (`CreatureID`='36766') AND (`GroupID`='0') AND (`ID`='13');
UPDATE `creature_text_locale` SET `CreatureID`='36766', `GroupID`='0', `ID`='14', `Locale`='esES', `Text`='Te mereces un buen abrazo de hombres.' WHERE (`CreatureID`='36766') AND (`GroupID`='0') AND (`ID`='14');
UPDATE `creature_text_locale` SET `CreatureID`='36766', `GroupID`='0', `ID`='15', `Locale`='esES', `Text`='Algún día encontraré la manera de devolverte el favor, $ghéroe:heroína;.' WHERE (`CreatureID`='36766') AND (`GroupID`='0') AND (`ID`='15');
UPDATE `creature_text_locale` SET `CreatureID`='36766', `GroupID`='0', `ID`='16', `Locale`='esES', `Text`='No puedo creer lo que ven mis ojos. Gracias, muchas gracias.' WHERE (`CreatureID`='36766') AND (`GroupID`='0') AND (`ID`='16');
UPDATE `creature_text_locale` SET `CreatureID`='36766', `GroupID`='0', `ID`='17', `Locale`='esES', `Text`='%s asiente dando las gracias.' WHERE (`CreatureID`='36766') AND (`GroupID`='0') AND (`ID`='17');
UPDATE `creature_text_locale` SET `CreatureID`='36766', `GroupID`='0', `ID`='18', `Locale`='esES', `Text`='%s ofrece una sonrisa de agradecimiento.' WHERE (`CreatureID`='36766') AND (`GroupID`='0') AND (`ID`='18');
UPDATE `creature_text_locale` SET `CreatureID`='36766', `GroupID`='0', `ID`='19', `Locale`='esES', `Text`='%s casi se derrumba mientras camina dando tumbos hacia ti.' WHERE (`CreatureID`='36766') AND (`GroupID`='0') AND (`ID`='19');
UPDATE `creature_text_locale` SET `CreatureID`='36766', `GroupID`='0', `ID`='20', `Locale`='esES', `Text`='%s te mira fijamente un momento, está claro que le cuesta creer que seas real.' WHERE (`CreatureID`='36766') AND (`GroupID`='0') AND (`ID`='20');
UPDATE `creature_text_locale` SET `CreatureID`='36766', `GroupID`='0', `ID`='21', `Locale`='esES', `Text`='%s suelta una risita rápida y cínica sobre su fortuna.' WHERE (`CreatureID`='36766') AND (`GroupID`='0') AND (`ID`='21');
UPDATE `creature_text_locale` SET `CreatureID`='36766', `GroupID`='0', `ID`='22', `Locale`='esES', `Text`='%s levanta su mano vacía y brinda por ti.' WHERE (`CreatureID`='36766') AND (`GroupID`='0') AND (`ID`='22');
UPDATE `creature_text_locale` SET `CreatureID`='36766', `GroupID`='0', `ID`='23', `Locale`='esES', `Text`='%s cierra los ojos y saborea la libertad un instante.' WHERE (`CreatureID`='36766') AND (`GroupID`='0') AND (`ID`='23');
UPDATE `creature_text_locale` SET `CreatureID`='36766', `GroupID`='0', `ID`='24', `Locale`='esES', `Text`='Voy a volver para ayudar a liberar a los demás esclavos. Gracias de nuevo, $ghéroe:heroína;.' WHERE (`CreatureID`='36766') AND (`GroupID`='0') AND (`ID`='24');
UPDATE `creature_text_locale` SET `CreatureID`='36767', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='¡Qué gusto da verte! No tienes ni idea.' WHERE (`CreatureID`='36767') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36767', `GroupID`='0', `ID`='1', `Locale`='esES', `Text`='%s deja que su pico de minería se arrastre por el suelo mientras se acerca, exhausto.' WHERE (`CreatureID`='36767') AND (`GroupID`='0') AND (`ID`='1');
UPDATE `creature_text_locale` SET `CreatureID`='36767', `GroupID`='0', `ID`='2', `Locale`='esES', `Text`='Te debo una larga noche bebiendo, $gamigo mío:amiga mía;.' WHERE (`CreatureID`='36767') AND (`GroupID`='0') AND (`ID`='2');
UPDATE `creature_text_locale` SET `CreatureID`='36767', `GroupID`='0', `ID`='3', `Locale`='esES', `Text`='Si con mi vida o muerte puedo devolverte el favor, lo haré.' WHERE (`CreatureID`='36767') AND (`GroupID`='0') AND (`ID`='3');
UPDATE `creature_text_locale` SET `CreatureID`='36767', `GroupID`='0', `ID`='4', `Locale`='esES', `Text`='Voy a volver al frente de la cantera. Mata a unos cuantos por mí.' WHERE (`CreatureID`='36767') AND (`GroupID`='0') AND (`ID`='4');
UPDATE `creature_text_locale` SET `CreatureID`='36767', `GroupID`='0', `ID`='5', `Locale`='esES', `Text`='Casi había perdido la esperanza.' WHERE (`CreatureID`='36767') AND (`GroupID`='0') AND (`ID`='5');
UPDATE `creature_text_locale` SET `CreatureID`='36767', `GroupID`='0', `ID`='6', `Locale`='esES', `Text`='Pensé que moriría en este foso. Gracias.' WHERE (`CreatureID`='36767') AND (`GroupID`='0') AND (`ID`='6');
UPDATE `creature_text_locale` SET `CreatureID`='36767', `GroupID`='0', `ID`='7', `Locale`='esES', `Text`='No dejes que ninguno viva.' WHERE (`CreatureID`='36767') AND (`GroupID`='0') AND (`ID`='7');
UPDATE `creature_text_locale` SET `CreatureID`='36767', `GroupID`='0', `ID`='8', `Locale`='esES', `Text`='Por favor, lleva a cabo nuestra venganza sobre el Señor de la Plaga.' WHERE (`CreatureID`='36767') AND (`GroupID`='0') AND (`ID`='8');
UPDATE `creature_text_locale` SET `CreatureID`='36767', `GroupID`='0', `ID`='9', `Locale`='esES', `Text`='Cuando mates al maestro del foso, escupe sobre su cadáver, ¿vale?' WHERE (`CreatureID`='36767') AND (`GroupID`='0') AND (`ID`='9');
UPDATE `creature_text_locale` SET `CreatureID`='36767', `GroupID`='0', `ID`='10', `Locale`='esES', `Text`='Había perdido la noción del tiempo en este maldito lugar. Da gusto verte, $gamigo:amiga;.' WHERE (`CreatureID`='36767') AND (`GroupID`='0') AND (`ID`='10');
UPDATE `creature_text_locale` SET `CreatureID`='36767', `GroupID`='0', `ID`='11', `Locale`='esES', `Text`='Demasiados morimos en este foso. Demasiados.' WHERE (`CreatureID`='36767') AND (`GroupID`='0') AND (`ID`='11');
UPDATE `creature_text_locale` SET `CreatureID`='36767', `GroupID`='0', `ID`='12', `Locale`='esES', `Text`='Me alegro tanto de que estés aquí. No habría aguantado mucho más.' WHERE (`CreatureID`='36767') AND (`GroupID`='0') AND (`ID`='12');
UPDATE `creature_text_locale` SET `CreatureID`='36767', `GroupID`='0', `ID`='13', `Locale`='esES', `Text`='Ahora viene mi venganza.' WHERE (`CreatureID`='36767') AND (`GroupID`='0') AND (`ID`='13');
UPDATE `creature_text_locale` SET `CreatureID`='36767', `GroupID`='0', `ID`='14', `Locale`='esES', `Text`='Te mereces un buen abrazo de hombres.' WHERE (`CreatureID`='36767') AND (`GroupID`='0') AND (`ID`='14');
UPDATE `creature_text_locale` SET `CreatureID`='36767', `GroupID`='0', `ID`='15', `Locale`='esES', `Text`='Algún día encontraré la manera de devolverte el favor, $ghéroe:heroína;.' WHERE (`CreatureID`='36767') AND (`GroupID`='0') AND (`ID`='15');
UPDATE `creature_text_locale` SET `CreatureID`='36767', `GroupID`='0', `ID`='16', `Locale`='esES', `Text`='No puedo creer lo que ven mis ojos. Gracias, muchas gracias.' WHERE (`CreatureID`='36767') AND (`GroupID`='0') AND (`ID`='16');
UPDATE `creature_text_locale` SET `CreatureID`='36767', `GroupID`='0', `ID`='17', `Locale`='esES', `Text`='%s asiente dando las gracias.' WHERE (`CreatureID`='36767') AND (`GroupID`='0') AND (`ID`='17');
UPDATE `creature_text_locale` SET `CreatureID`='36767', `GroupID`='0', `ID`='18', `Locale`='esES', `Text`='%s ofrece una sonrisa de agradecimiento.' WHERE (`CreatureID`='36767') AND (`GroupID`='0') AND (`ID`='18');
UPDATE `creature_text_locale` SET `CreatureID`='36767', `GroupID`='0', `ID`='19', `Locale`='esES', `Text`='%s casi se derrumba mientras camina dando tumbos hacia ti.' WHERE (`CreatureID`='36767') AND (`GroupID`='0') AND (`ID`='19');
UPDATE `creature_text_locale` SET `CreatureID`='36767', `GroupID`='0', `ID`='20', `Locale`='esES', `Text`='%s te mira fijamente un momento, está claro que le cuesta creer que seas real.' WHERE (`CreatureID`='36767') AND (`GroupID`='0') AND (`ID`='20');
UPDATE `creature_text_locale` SET `CreatureID`='36767', `GroupID`='0', `ID`='21', `Locale`='esES', `Text`='%s suelta una risita rápida y cínica sobre su fortuna.' WHERE (`CreatureID`='36767') AND (`GroupID`='0') AND (`ID`='21');
UPDATE `creature_text_locale` SET `CreatureID`='36767', `GroupID`='0', `ID`='22', `Locale`='esES', `Text`='%s levanta su mano vacía y brinda por ti.' WHERE (`CreatureID`='36767') AND (`GroupID`='0') AND (`ID`='22');
UPDATE `creature_text_locale` SET `CreatureID`='36767', `GroupID`='0', `ID`='23', `Locale`='esES', `Text`='%s cierra los ojos y saborea la libertad un instante.' WHERE (`CreatureID`='36767') AND (`GroupID`='0') AND (`ID`='23');
UPDATE `creature_text_locale` SET `CreatureID`='36767', `GroupID`='0', `ID`='24', `Locale`='esES', `Text`='Voy a volver para ayudar a liberar a los demás esclavos. Gracias de nuevo, $ghéroe:heroína;.' WHERE (`CreatureID`='36767') AND (`GroupID`='0') AND (`ID`='24');

-- Esclavos de la Horda --
UPDATE `creature_text_locale` SET `CreatureID`='36770', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='¡Qué gusto da verte! No tienes ni idea.' WHERE (`CreatureID`='36770') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36770', `GroupID`='0', `ID`='1', `Locale`='esES', `Text`='%s deja que su pico de minería se arrastre por el suelo mientras se acerca, exhausto.' WHERE (`CreatureID`='36770') AND (`GroupID`='0') AND (`ID`='1');
UPDATE `creature_text_locale` SET `CreatureID`='36770', `GroupID`='0', `ID`='2', `Locale`='esES', `Text`='Te debo una larga noche bebiendo, $gamigo mío:amiga mía;.' WHERE (`CreatureID`='36770') AND (`GroupID`='0') AND (`ID`='2');
UPDATE `creature_text_locale` SET `CreatureID`='36770', `GroupID`='0', `ID`='3', `Locale`='esES', `Text`='Si con mi vida o muerte puedo devolverte el favor, lo haré.' WHERE (`CreatureID`='36770') AND (`GroupID`='0') AND (`ID`='3');
UPDATE `creature_text_locale` SET `CreatureID`='36770', `GroupID`='0', `ID`='4', `Locale`='esES', `Text`='Voy a volver al frente de la cantera. Mata a unos cuantos por mí.' WHERE (`CreatureID`='36770') AND (`GroupID`='0') AND (`ID`='4');
UPDATE `creature_text_locale` SET `CreatureID`='36770', `GroupID`='0', `ID`='5', `Locale`='esES', `Text`='Casi había perdido la esperanza.' WHERE (`CreatureID`='36770') AND (`GroupID`='0') AND (`ID`='5');
UPDATE `creature_text_locale` SET `CreatureID`='36770', `GroupID`='0', `ID`='6', `Locale`='esES', `Text`='Pensé que moriría en este foso. Gracias.' WHERE (`CreatureID`='36770') AND (`GroupID`='0') AND (`ID`='6');
UPDATE `creature_text_locale` SET `CreatureID`='36770', `GroupID`='0', `ID`='7', `Locale`='esES', `Text`='No dejes que ninguno viva.' WHERE (`CreatureID`='36770') AND (`GroupID`='0') AND (`ID`='7');
UPDATE `creature_text_locale` SET `CreatureID`='36770', `GroupID`='0', `ID`='8', `Locale`='esES', `Text`='Por favor, lleva a cabo nuestra venganza sobre el Señor de la Plaga.' WHERE (`CreatureID`='36770') AND (`GroupID`='0') AND (`ID`='8');
UPDATE `creature_text_locale` SET `CreatureID`='36770', `GroupID`='0', `ID`='9', `Locale`='esES', `Text`='Cuando mates al maestro del foso, escupe sobre su cadáver, ¿vale?' WHERE (`CreatureID`='36770') AND (`GroupID`='0') AND (`ID`='9');
UPDATE `creature_text_locale` SET `CreatureID`='36770', `GroupID`='0', `ID`='10', `Locale`='esES', `Text`='Había perdido la noción del tiempo en este maldito lugar. Da gusto verte, $gamigo:amiga;.' WHERE (`CreatureID`='36770') AND (`GroupID`='0') AND (`ID`='10');
UPDATE `creature_text_locale` SET `CreatureID`='36770', `GroupID`='0', `ID`='11', `Locale`='esES', `Text`='Demasiados morimos en este foso. Demasiados.' WHERE (`CreatureID`='36770') AND (`GroupID`='0') AND (`ID`='11');
UPDATE `creature_text_locale` SET `CreatureID`='36770', `GroupID`='0', `ID`='12', `Locale`='esES', `Text`='Me alegro tanto de que estés aquí. No habría aguantado mucho más.' WHERE (`CreatureID`='36770') AND (`GroupID`='0') AND (`ID`='12');
UPDATE `creature_text_locale` SET `CreatureID`='36770', `GroupID`='0', `ID`='13', `Locale`='esES', `Text`='Ahora viene mi venganza.' WHERE (`CreatureID`='36770') AND (`GroupID`='0') AND (`ID`='13');
UPDATE `creature_text_locale` SET `CreatureID`='36770', `GroupID`='0', `ID`='14', `Locale`='esES', `Text`='Te mereces un buen abrazo de hombres.' WHERE (`CreatureID`='36770') AND (`GroupID`='0') AND (`ID`='14');
UPDATE `creature_text_locale` SET `CreatureID`='36770', `GroupID`='0', `ID`='15', `Locale`='esES', `Text`='Algún día encontraré la manera de devolverte el favor, $ghéroe:heroína;.' WHERE (`CreatureID`='36770') AND (`GroupID`='0') AND (`ID`='15');
UPDATE `creature_text_locale` SET `CreatureID`='36770', `GroupID`='0', `ID`='16', `Locale`='esES', `Text`='No puedo creer lo que ven mis ojos. Gracias, muchas gracias.' WHERE (`CreatureID`='36770') AND (`GroupID`='0') AND (`ID`='16');
UPDATE `creature_text_locale` SET `CreatureID`='36770', `GroupID`='0', `ID`='17', `Locale`='esES', `Text`='%s asiente dando las gracias.' WHERE (`CreatureID`='36770') AND (`GroupID`='0') AND (`ID`='17');
UPDATE `creature_text_locale` SET `CreatureID`='36770', `GroupID`='0', `ID`='18', `Locale`='esES', `Text`='%s ofrece una sonrisa de agradecimiento.' WHERE (`CreatureID`='36770') AND (`GroupID`='0') AND (`ID`='18');
UPDATE `creature_text_locale` SET `CreatureID`='36770', `GroupID`='0', `ID`='19', `Locale`='esES', `Text`='%s casi se derrumba mientras camina dando tumbos hacia ti.' WHERE (`CreatureID`='36770') AND (`GroupID`='0') AND (`ID`='19');
UPDATE `creature_text_locale` SET `CreatureID`='36770', `GroupID`='0', `ID`='20', `Locale`='esES', `Text`='%s te mira fijamente un momento, está claro que le cuesta creer que seas real.' WHERE (`CreatureID`='36770') AND (`GroupID`='0') AND (`ID`='20');
UPDATE `creature_text_locale` SET `CreatureID`='36770', `GroupID`='0', `ID`='21', `Locale`='esES', `Text`='%s suelta una risita rápida y cínica sobre su fortuna.' WHERE (`CreatureID`='36770') AND (`GroupID`='0') AND (`ID`='21');
UPDATE `creature_text_locale` SET `CreatureID`='36770', `GroupID`='0', `ID`='22', `Locale`='esES', `Text`='%s levanta su mano vacía y brinda por ti.' WHERE (`CreatureID`='36770') AND (`GroupID`='0') AND (`ID`='22');
UPDATE `creature_text_locale` SET `CreatureID`='36770', `GroupID`='0', `ID`='23', `Locale`='esES', `Text`='%s cierra los ojos y saborea la libertad un instante.' WHERE (`CreatureID`='36770') AND (`GroupID`='0') AND (`ID`='23');
UPDATE `creature_text_locale` SET `CreatureID`='36770', `GroupID`='0', `ID`='24', `Locale`='esES', `Text`='Voy a volver para ayudar a liberar a los demás esclavos. Gracias de nuevo, $ghéroe:heroína;.' WHERE (`CreatureID`='36770') AND (`GroupID`='0') AND (`ID`='24');
UPDATE `creature_text_locale` SET `CreatureID`='36771', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='¡Qué gusto da verte! No tienes ni idea.' WHERE (`CreatureID`='36771') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36771', `GroupID`='0', `ID`='1', `Locale`='esES', `Text`='%s deja que su pico de minería se arrastre por el suelo mientras se acerca, exhausto.' WHERE (`CreatureID`='36771') AND (`GroupID`='0') AND (`ID`='1');
UPDATE `creature_text_locale` SET `CreatureID`='36771', `GroupID`='0', `ID`='2', `Locale`='esES', `Text`='Te debo una larga noche bebiendo, $gamigo mío:amiga mía;.' WHERE (`CreatureID`='36771') AND (`GroupID`='0') AND (`ID`='2');
UPDATE `creature_text_locale` SET `CreatureID`='36771', `GroupID`='0', `ID`='3', `Locale`='esES', `Text`='Si con mi vida o muerte puedo devolverte el favor, lo haré.' WHERE (`CreatureID`='36771') AND (`GroupID`='0') AND (`ID`='3');
UPDATE `creature_text_locale` SET `CreatureID`='36771', `GroupID`='0', `ID`='4', `Locale`='esES', `Text`='Voy a volver al frente de la cantera. Mata a unos cuantos por mí.' WHERE (`CreatureID`='36771') AND (`GroupID`='0') AND (`ID`='4');
UPDATE `creature_text_locale` SET `CreatureID`='36771', `GroupID`='0', `ID`='5', `Locale`='esES', `Text`='Casi había perdido la esperanza.' WHERE (`CreatureID`='36771') AND (`GroupID`='0') AND (`ID`='5');
UPDATE `creature_text_locale` SET `CreatureID`='36771', `GroupID`='0', `ID`='6', `Locale`='esES', `Text`='Pensé que moriría en este foso. Gracias.' WHERE (`CreatureID`='36771') AND (`GroupID`='0') AND (`ID`='6');
UPDATE `creature_text_locale` SET `CreatureID`='36771', `GroupID`='0', `ID`='7', `Locale`='esES', `Text`='No dejes que ninguno viva.' WHERE (`CreatureID`='36771') AND (`GroupID`='0') AND (`ID`='7');
UPDATE `creature_text_locale` SET `CreatureID`='36771', `GroupID`='0', `ID`='8', `Locale`='esES', `Text`='Por favor, lleva a cabo nuestra venganza sobre el Señor de la Plaga.' WHERE (`CreatureID`='36771') AND (`GroupID`='0') AND (`ID`='8');
UPDATE `creature_text_locale` SET `CreatureID`='36771', `GroupID`='0', `ID`='9', `Locale`='esES', `Text`='Cuando mates al maestro del foso, escupe sobre su cadáver, ¿vale?' WHERE (`CreatureID`='36771') AND (`GroupID`='0') AND (`ID`='9');
UPDATE `creature_text_locale` SET `CreatureID`='36771', `GroupID`='0', `ID`='10', `Locale`='esES', `Text`='Había perdido la noción del tiempo en este maldito lugar. Da gusto verte, $gamigo:amiga;.' WHERE (`CreatureID`='36771') AND (`GroupID`='0') AND (`ID`='10');
UPDATE `creature_text_locale` SET `CreatureID`='36771', `GroupID`='0', `ID`='11', `Locale`='esES', `Text`='Demasiados morimos en este foso. Demasiados.' WHERE (`CreatureID`='36771') AND (`GroupID`='0') AND (`ID`='11');
UPDATE `creature_text_locale` SET `CreatureID`='36771', `GroupID`='0', `ID`='12', `Locale`='esES', `Text`='Me alegro tanto de que estés aquí. No habría aguantado mucho más.' WHERE (`CreatureID`='36771') AND (`GroupID`='0') AND (`ID`='12');
UPDATE `creature_text_locale` SET `CreatureID`='36771', `GroupID`='0', `ID`='13', `Locale`='esES', `Text`='Ahora viene mi venganza.' WHERE (`CreatureID`='36771') AND (`GroupID`='0') AND (`ID`='13');
UPDATE `creature_text_locale` SET `CreatureID`='36771', `GroupID`='0', `ID`='14', `Locale`='esES', `Text`='Te mereces un buen abrazo de hombres.' WHERE (`CreatureID`='36771') AND (`GroupID`='0') AND (`ID`='14');
UPDATE `creature_text_locale` SET `CreatureID`='36771', `GroupID`='0', `ID`='15', `Locale`='esES', `Text`='Algún día encontraré la manera de devolverte el favor, $ghéroe:heroína;.' WHERE (`CreatureID`='36771') AND (`GroupID`='0') AND (`ID`='15');
UPDATE `creature_text_locale` SET `CreatureID`='36771', `GroupID`='0', `ID`='16', `Locale`='esES', `Text`='No puedo creer lo que ven mis ojos. Gracias, muchas gracias.' WHERE (`CreatureID`='36771') AND (`GroupID`='0') AND (`ID`='16');
UPDATE `creature_text_locale` SET `CreatureID`='36771', `GroupID`='0', `ID`='17', `Locale`='esES', `Text`='%s asiente dando las gracias.' WHERE (`CreatureID`='36771') AND (`GroupID`='0') AND (`ID`='17');
UPDATE `creature_text_locale` SET `CreatureID`='36771', `GroupID`='0', `ID`='18', `Locale`='esES', `Text`='%s ofrece una sonrisa de agradecimiento.' WHERE (`CreatureID`='36771') AND (`GroupID`='0') AND (`ID`='18');
UPDATE `creature_text_locale` SET `CreatureID`='36771', `GroupID`='0', `ID`='19', `Locale`='esES', `Text`='%s casi se derrumba mientras camina dando tumbos hacia ti.' WHERE (`CreatureID`='36771') AND (`GroupID`='0') AND (`ID`='19');
UPDATE `creature_text_locale` SET `CreatureID`='36771', `GroupID`='0', `ID`='20', `Locale`='esES', `Text`='%s te mira fijamente un momento, está claro que le cuesta creer que seas real.' WHERE (`CreatureID`='36771') AND (`GroupID`='0') AND (`ID`='20');
UPDATE `creature_text_locale` SET `CreatureID`='36771', `GroupID`='0', `ID`='21', `Locale`='esES', `Text`='%s suelta una risita rápida y cínica sobre su fortuna.' WHERE (`CreatureID`='36771') AND (`GroupID`='0') AND (`ID`='21');
UPDATE `creature_text_locale` SET `CreatureID`='36771', `GroupID`='0', `ID`='22', `Locale`='esES', `Text`='%s levanta su mano vacía y brinda por ti.' WHERE (`CreatureID`='36771') AND (`GroupID`='0') AND (`ID`='22');
UPDATE `creature_text_locale` SET `CreatureID`='36771', `GroupID`='0', `ID`='23', `Locale`='esES', `Text`='%s cierra los ojos y saborea la libertad un instante.' WHERE (`CreatureID`='36771') AND (`GroupID`='0') AND (`ID`='23');
UPDATE `creature_text_locale` SET `CreatureID`='36771', `GroupID`='0', `ID`='24', `Locale`='esES', `Text`='Voy a volver para ayudar a liberar a los demás esclavos. Gracias de nuevo, $ghéroe:heroína;.' WHERE (`CreatureID`='36771') AND (`GroupID`='0') AND (`ID`='24');
UPDATE `creature_text_locale` SET `CreatureID`='36772', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='¡Qué gusto da verte! No tienes ni idea.' WHERE (`CreatureID`='36772') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36772', `GroupID`='0', `ID`='1', `Locale`='esES', `Text`='%s deja que su pico de minería se arrastre por el suelo mientras se acerca, exhausto.' WHERE (`CreatureID`='36772') AND (`GroupID`='0') AND (`ID`='1');
UPDATE `creature_text_locale` SET `CreatureID`='36772', `GroupID`='0', `ID`='2', `Locale`='esES', `Text`='Te debo una larga noche bebiendo, $gamigo mío:amiga mía;.' WHERE (`CreatureID`='36772') AND (`GroupID`='0') AND (`ID`='2');
UPDATE `creature_text_locale` SET `CreatureID`='36772', `GroupID`='0', `ID`='3', `Locale`='esES', `Text`='Si con mi vida o muerte puedo devolverte el favor, lo haré.' WHERE (`CreatureID`='36772') AND (`GroupID`='0') AND (`ID`='3');
UPDATE `creature_text_locale` SET `CreatureID`='36772', `GroupID`='0', `ID`='4', `Locale`='esES', `Text`='Voy a volver al frente de la cantera. Mata a unos cuantos por mí.' WHERE (`CreatureID`='36772') AND (`GroupID`='0') AND (`ID`='4');
UPDATE `creature_text_locale` SET `CreatureID`='36772', `GroupID`='0', `ID`='5', `Locale`='esES', `Text`='Casi había perdido la esperanza.' WHERE (`CreatureID`='36772') AND (`GroupID`='0') AND (`ID`='5');
UPDATE `creature_text_locale` SET `CreatureID`='36772', `GroupID`='0', `ID`='6', `Locale`='esES', `Text`='Pensé que moriría en este foso. Gracias.' WHERE (`CreatureID`='36772') AND (`GroupID`='0') AND (`ID`='6');
UPDATE `creature_text_locale` SET `CreatureID`='36772', `GroupID`='0', `ID`='7', `Locale`='esES', `Text`='No dejes que ninguno viva.' WHERE (`CreatureID`='36772') AND (`GroupID`='0') AND (`ID`='7');
UPDATE `creature_text_locale` SET `CreatureID`='36772', `GroupID`='0', `ID`='8', `Locale`='esES', `Text`='Por favor, lleva a cabo nuestra venganza sobre el Señor de la Plaga.' WHERE (`CreatureID`='36772') AND (`GroupID`='0') AND (`ID`='8');
UPDATE `creature_text_locale` SET `CreatureID`='36772', `GroupID`='0', `ID`='9', `Locale`='esES', `Text`='Cuando mates al maestro del foso, escupe sobre su cadáver, ¿vale?' WHERE (`CreatureID`='36772') AND (`GroupID`='0') AND (`ID`='9');
UPDATE `creature_text_locale` SET `CreatureID`='36772', `GroupID`='0', `ID`='10', `Locale`='esES', `Text`='Había perdido la noción del tiempo en este maldito lugar. Da gusto verte, $gamigo:amiga;.' WHERE (`CreatureID`='36772') AND (`GroupID`='0') AND (`ID`='10');
UPDATE `creature_text_locale` SET `CreatureID`='36772', `GroupID`='0', `ID`='11', `Locale`='esES', `Text`='Demasiados morimos en este foso. Demasiados.' WHERE (`CreatureID`='36772') AND (`GroupID`='0') AND (`ID`='11');
UPDATE `creature_text_locale` SET `CreatureID`='36772', `GroupID`='0', `ID`='12', `Locale`='esES', `Text`='Me alegro tanto de que estés aquí. No habría aguantado mucho más.' WHERE (`CreatureID`='36772') AND (`GroupID`='0') AND (`ID`='12');
UPDATE `creature_text_locale` SET `CreatureID`='36772', `GroupID`='0', `ID`='13', `Locale`='esES', `Text`='Ahora viene mi venganza.' WHERE (`CreatureID`='36772') AND (`GroupID`='0') AND (`ID`='13');
UPDATE `creature_text_locale` SET `CreatureID`='36772', `GroupID`='0', `ID`='14', `Locale`='esES', `Text`='Te mereces un buen abrazo de hombres.' WHERE (`CreatureID`='36772') AND (`GroupID`='0') AND (`ID`='14');
UPDATE `creature_text_locale` SET `CreatureID`='36772', `GroupID`='0', `ID`='15', `Locale`='esES', `Text`='Algún día encontraré la manera de devolverte el favor, $ghéroe:heroína;.' WHERE (`CreatureID`='36772') AND (`GroupID`='0') AND (`ID`='15');
UPDATE `creature_text_locale` SET `CreatureID`='36772', `GroupID`='0', `ID`='16', `Locale`='esES', `Text`='No puedo creer lo que ven mis ojos. Gracias, muchas gracias.' WHERE (`CreatureID`='36772') AND (`GroupID`='0') AND (`ID`='16');
UPDATE `creature_text_locale` SET `CreatureID`='36772', `GroupID`='0', `ID`='17', `Locale`='esES', `Text`='%s asiente dando las gracias.' WHERE (`CreatureID`='36772') AND (`GroupID`='0') AND (`ID`='17');
UPDATE `creature_text_locale` SET `CreatureID`='36772', `GroupID`='0', `ID`='18', `Locale`='esES', `Text`='%s ofrece una sonrisa de agradecimiento.' WHERE (`CreatureID`='36772') AND (`GroupID`='0') AND (`ID`='18');
UPDATE `creature_text_locale` SET `CreatureID`='36772', `GroupID`='0', `ID`='19', `Locale`='esES', `Text`='%s casi se derrumba mientras camina dando tumbos hacia ti.' WHERE (`CreatureID`='36772') AND (`GroupID`='0') AND (`ID`='19');
UPDATE `creature_text_locale` SET `CreatureID`='36772', `GroupID`='0', `ID`='20', `Locale`='esES', `Text`='%s te mira fijamente un momento, está claro que le cuesta creer que seas real.' WHERE (`CreatureID`='36772') AND (`GroupID`='0') AND (`ID`='20');
UPDATE `creature_text_locale` SET `CreatureID`='36772', `GroupID`='0', `ID`='21', `Locale`='esES', `Text`='%s suelta una risita rápida y cínica sobre su fortuna.' WHERE (`CreatureID`='36772') AND (`GroupID`='0') AND (`ID`='21');
UPDATE `creature_text_locale` SET `CreatureID`='36772', `GroupID`='0', `ID`='22', `Locale`='esES', `Text`='%s levanta su mano vacía y brinda por ti.' WHERE (`CreatureID`='36772') AND (`GroupID`='0') AND (`ID`='22');
UPDATE `creature_text_locale` SET `CreatureID`='36772', `GroupID`='0', `ID`='23', `Locale`='esES', `Text`='%s cierra los ojos y saborea la libertad un instante.' WHERE (`CreatureID`='36772') AND (`GroupID`='0') AND (`ID`='23');
UPDATE `creature_text_locale` SET `CreatureID`='36772', `GroupID`='0', `ID`='24', `Locale`='esES', `Text`='Voy a volver para ayudar a liberar a los demás esclavos. Gracias de nuevo, $ghéroe:heroína;.' WHERE (`CreatureID`='36772') AND (`GroupID`='0') AND (`ID`='24');
UPDATE `creature_text_locale` SET `CreatureID`='36773', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='¡Qué gusto da verte! No tienes ni idea.' WHERE (`CreatureID`='36773') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36773', `GroupID`='0', `ID`='1', `Locale`='esES', `Text`='%s deja que su pico de minería se arrastre por el suelo mientras se acerca, exhausto.' WHERE (`CreatureID`='36773') AND (`GroupID`='0') AND (`ID`='1');
UPDATE `creature_text_locale` SET `CreatureID`='36773', `GroupID`='0', `ID`='2', `Locale`='esES', `Text`='Te debo una larga noche bebiendo, $gamigo mío:amiga mía;.' WHERE (`CreatureID`='36773') AND (`GroupID`='0') AND (`ID`='2');
UPDATE `creature_text_locale` SET `CreatureID`='36773', `GroupID`='0', `ID`='3', `Locale`='esES', `Text`='Si con mi vida o muerte puedo devolverte el favor, lo haré.' WHERE (`CreatureID`='36773') AND (`GroupID`='0') AND (`ID`='3');
UPDATE `creature_text_locale` SET `CreatureID`='36773', `GroupID`='0', `ID`='4', `Locale`='esES', `Text`='Voy a volver al frente de la cantera. Mata a unos cuantos por mí.' WHERE (`CreatureID`='36773') AND (`GroupID`='0') AND (`ID`='4');
UPDATE `creature_text_locale` SET `CreatureID`='36773', `GroupID`='0', `ID`='5', `Locale`='esES', `Text`='Casi había perdido la esperanza.' WHERE (`CreatureID`='36773') AND (`GroupID`='0') AND (`ID`='5');
UPDATE `creature_text_locale` SET `CreatureID`='36773', `GroupID`='0', `ID`='6', `Locale`='esES', `Text`='Pensé que moriría en este foso. Gracias.' WHERE (`CreatureID`='36773') AND (`GroupID`='0') AND (`ID`='6');
UPDATE `creature_text_locale` SET `CreatureID`='36773', `GroupID`='0', `ID`='7', `Locale`='esES', `Text`='No dejes que ninguno viva.' WHERE (`CreatureID`='36773') AND (`GroupID`='0') AND (`ID`='7');
UPDATE `creature_text_locale` SET `CreatureID`='36773', `GroupID`='0', `ID`='8', `Locale`='esES', `Text`='Por favor, lleva a cabo nuestra venganza sobre el Señor de la Plaga.' WHERE (`CreatureID`='36773') AND (`GroupID`='0') AND (`ID`='8');
UPDATE `creature_text_locale` SET `CreatureID`='36773', `GroupID`='0', `ID`='9', `Locale`='esES', `Text`='Cuando mates al maestro del foso, escupe sobre su cadáver, ¿vale?' WHERE (`CreatureID`='36773') AND (`GroupID`='0') AND (`ID`='9');
UPDATE `creature_text_locale` SET `CreatureID`='36773', `GroupID`='0', `ID`='10', `Locale`='esES', `Text`='Había perdido la noción del tiempo en este maldito lugar. Da gusto verte, $gamigo:amiga;.' WHERE (`CreatureID`='36773') AND (`GroupID`='0') AND (`ID`='10');
UPDATE `creature_text_locale` SET `CreatureID`='36773', `GroupID`='0', `ID`='11', `Locale`='esES', `Text`='Demasiados morimos en este foso. Demasiados.' WHERE (`CreatureID`='36773') AND (`GroupID`='0') AND (`ID`='11');
UPDATE `creature_text_locale` SET `CreatureID`='36773', `GroupID`='0', `ID`='12', `Locale`='esES', `Text`='Me alegro tanto de que estés aquí. No habría aguantado mucho más.' WHERE (`CreatureID`='36773') AND (`GroupID`='0') AND (`ID`='12');
UPDATE `creature_text_locale` SET `CreatureID`='36773', `GroupID`='0', `ID`='13', `Locale`='esES', `Text`='Ahora viene mi venganza.' WHERE (`CreatureID`='36773') AND (`GroupID`='0') AND (`ID`='13');
UPDATE `creature_text_locale` SET `CreatureID`='36773', `GroupID`='0', `ID`='14', `Locale`='esES', `Text`='Te mereces un buen abrazo de hombres.' WHERE (`CreatureID`='36773') AND (`GroupID`='0') AND (`ID`='14');
UPDATE `creature_text_locale` SET `CreatureID`='36773', `GroupID`='0', `ID`='15', `Locale`='esES', `Text`='Algún día encontraré la manera de devolverte el favor, $ghéroe:heroína;.' WHERE (`CreatureID`='36773') AND (`GroupID`='0') AND (`ID`='15');
UPDATE `creature_text_locale` SET `CreatureID`='36773', `GroupID`='0', `ID`='16', `Locale`='esES', `Text`='No puedo creer lo que ven mis ojos. Gracias, muchas gracias.' WHERE (`CreatureID`='36773') AND (`GroupID`='0') AND (`ID`='16');
UPDATE `creature_text_locale` SET `CreatureID`='36773', `GroupID`='0', `ID`='17', `Locale`='esES', `Text`='%s asiente dando las gracias.' WHERE (`CreatureID`='36773') AND (`GroupID`='0') AND (`ID`='17');
UPDATE `creature_text_locale` SET `CreatureID`='36773', `GroupID`='0', `ID`='18', `Locale`='esES', `Text`='%s ofrece una sonrisa de agradecimiento.' WHERE (`CreatureID`='36773') AND (`GroupID`='0') AND (`ID`='18');
UPDATE `creature_text_locale` SET `CreatureID`='36773', `GroupID`='0', `ID`='19', `Locale`='esES', `Text`='%s casi se derrumba mientras camina dando tumbos hacia ti.' WHERE (`CreatureID`='36773') AND (`GroupID`='0') AND (`ID`='19');
UPDATE `creature_text_locale` SET `CreatureID`='36773', `GroupID`='0', `ID`='20', `Locale`='esES', `Text`='%s te mira fijamente un momento, está claro que le cuesta creer que seas real.' WHERE (`CreatureID`='36773') AND (`GroupID`='0') AND (`ID`='20');
UPDATE `creature_text_locale` SET `CreatureID`='36773', `GroupID`='0', `ID`='21', `Locale`='esES', `Text`='%s suelta una risita rápida y cínica sobre su fortuna.' WHERE (`CreatureID`='36773') AND (`GroupID`='0') AND (`ID`='21');
UPDATE `creature_text_locale` SET `CreatureID`='36773', `GroupID`='0', `ID`='22', `Locale`='esES', `Text`='%s levanta su mano vacía y brinda por ti.' WHERE (`CreatureID`='36773') AND (`GroupID`='0') AND (`ID`='22');
UPDATE `creature_text_locale` SET `CreatureID`='36773', `GroupID`='0', `ID`='23', `Locale`='esES', `Text`='%s cierra los ojos y saborea la libertad un instante.' WHERE (`CreatureID`='36773') AND (`GroupID`='0') AND (`ID`='23');
UPDATE `creature_text_locale` SET `CreatureID`='36773', `GroupID`='0', `ID`='24', `Locale`='esES', `Text`='Voy a volver para ayudar a liberar a los demás esclavos. Gracias de nuevo, $ghéroe:heroína;.' WHERE (`CreatureID`='36773') AND (`GroupID`='0') AND (`ID`='24');

-- Gorkun Testahierro --
UPDATE `creature_text_locale` SET `CreatureID`='37592', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='¡Héroes! Retendremos a los no-muertos cuanto podamos, hasta nuestro aliento final. ¡Ocupaos del Señor de la Plaga!' WHERE (`CreatureID`='37592') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37592', `GroupID`='1', `ID`='0', `Locale`='esES', `Text`='Valientes campeones, os debemos la vida, nuestra libertad... Aunque sea un pequeño gesto frente a nuestra gran deuda, prometo que, de hoy en adelante, todos conocerán vuestras hazañas y el llameante camino de Luz que lograsteis que atravesara esta oscura ciudadela.' WHERE (`CreatureID`='37592') AND (`GroupID`='1') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='37592', `GroupID`='2', `ID`='0', `Locale`='esES', `Text`='Hoy habéis demostrado no solo vuestro valor, si no también que ningún enemigo, ni siquiera el Rey Exánime, puede interponerse cuando la Horda y la Alianza dejan de lado sus diferencias y...' WHERE (`CreatureID`='37592') AND (`GroupID`='2') AND (`ID`='0');

-- Lady Jaina Valiente --
UPDATE `creature_text_locale` SET `CreatureID`='36993', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='No soy tan ingenua como para creerte cuando pides clemencia, pero te escucharé.' WHERE (`CreatureID`='36993') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36993', `GroupID`='1', `ID`='0', `Locale`='esES', `Text`='¿La Agonía de Escarcha está sin vigilancia? ¡Imposible!' WHERE (`CreatureID`='36993') AND (`GroupID`='1') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36993', `GroupID`='2', `ID`='0', `Locale`='esES', `Text`='Qué final tan cruel. Vamos, héroes. Veamos si la historia del gnomo es cierta. Si separamos a Arthas de la Agonía de Escarcha, puede que logremos detenerle.' WHERE (`CreatureID`='36993') AND (`GroupID`='2') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36993', `GroupID`='3', `ID`='0', `Locale`='esES', `Text`='¡Héroes, venid!' WHERE (`CreatureID`='36993') AND (`GroupID`='3') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36993', `GroupID`='4', `ID`='0', `Locale`='esES', `Text`='La Reina de Escarcha se ha ido. Debemos seguir adelante. Nuestro objetivo está cerca.' WHERE (`CreatureID`='36993') AND (`GroupID`='4') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36993', `GroupID`='5', `ID`='0', `Locale`='esES', `Text`='No... pude salvarlos... ¡Maldito seas, Arthas! ¡MALDITO SEAS!' WHERE (`CreatureID`='36993') AND (`GroupID`='5') AND (`ID`='0');

-- Lady Sylvanas Brisaveloz --
UPDATE `creature_text_locale` SET `CreatureID`='36990', `GroupID`='0', `ID`='0', `Locale`='esES', `Text`='¿Por qué debería perdonarte la vida la Reina alma en pena?' WHERE (`CreatureID`='36990') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36990', `GroupID`='1', `ID`='0', `Locale`='esES', `Text`='¿La Agonía de Escarcha? El Rey Exánime nunca deja su espada. Si me mientes...' WHERE (`CreatureID`='36990') AND (`GroupID`='1') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36990', `GroupID`='2', `ID`='0', `Locale`='esES', `Text`='Un final propio para un traidor. Vamos, debemos liberar a los esclavos y ver qué hay en la estancia del Rey Exánime.' WHERE (`CreatureID`='36990') AND (`GroupID`='2') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36990', `GroupID`='3', `ID`='0', `Locale`='esES', `Text`='¡Protegeos detrás de mí! ¡Rápido!' WHERE (`CreatureID`='36990') AND (`GroupID`='3') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='36990', `GroupID`='4', `ID`='0', `Locale`='esES', `Text`='Pensé que nunca se callaría. Por fin, Sindragosa silenció a ese loco impertinente. ¡A las Cámaras de Reflexión, campeones! Nuestro objetivo está cerca... Lo presiento.' WHERE (`CreatureID`='36990') AND (`GroupID`='4') AND (`ID`='0');