
/*Nuevo contenido basado en la última actualización de la base de datos TDB 335.62*/

-- General --
UPDATE `locales_creature_text` SET `entry`='34965', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡No puedes detener a los Kvaldir!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='34965') AND (`groupid`='0') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='34980', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¿Te atreves a desafiar a Drottinn Hrothgar, rey de los mares?', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='34980') AND (`groupid`='0') AND (`id`='0');

-- Boticario Hanes --
UPDATE `locales_creature_text` SET `entry`='23784', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡No podrías haber venido en mejor momento! Vamos a salir de aquí.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23784') AND (`groupid`='0') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='23784', `groupid`='1', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Sí, vamos... pero no sin dejarles antes a nuestros anfitriones de la Alianza algo para que no se olviden de nosotros!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23784') AND (`groupid`='1') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='23784', `groupid`='2', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Disponen de suministros limitados en este campamento. Sería una verdadera lástima si algo les pasara.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23784') AND (`groupid`='2') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='23784', `groupid`='3', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Oh, sí... ¡contempla como arden!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23784') AND (`groupid`='3') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='23784', `groupid`='4', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Ya casi hemos acabado!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23784') AND (`groupid`='4') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='23784', `groupid`='5', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Esto os enseñará a no meteros con un boticario, perros de la Alianza!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23784') AND (`groupid`='5') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='23784', `groupid`='6', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Vamos a salir de aquí.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23784') AND (`groupid`='6') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='23784', `groupid`='7', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡No disparéis! ¡Boticario en camino!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23784') AND (`groupid`='7') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='23784', `groupid`='8', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Estamos en deuda contigo, $gamigo:amiga;. Habla con Lysander en Campo Venganza; él te proporcionará una recompensa conveniente.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23784') AND (`groupid`='8') AND (`id`='0');

-- Ojo del Rey Exánime --
UPDATE `locales_creature_text` SET `entry`='23837', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Indagando sobre muchas de las situaciones insignificantes de Corona de Hielo, te tropiezas con algo interesante...', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23837') AND (`groupid`='0') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='23837', `groupid`='1', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Hay un ruido detrás de ti!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23837') AND (`groupid`='1') AND (`id`='0');

-- Defensor de la Guardia Oeste --
UPDATE `locales_creature_text` SET `entry`='23842', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¿Uh...?', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23842') AND (`groupid`='0') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='23842', `groupid`='0', `id`='1', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Interesante.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23842') AND (`groupid`='0') AND (`id`='1');
UPDATE `locales_creature_text` SET `entry`='23842', `groupid`='0', `id`='2', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Ostras.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23842') AND (`groupid`='0') AND (`id`='2');
UPDATE `locales_creature_text` SET `entry`='23842', `groupid`='0', `id`='3', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¿Se encuentra bien?', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23842') AND (`groupid`='0') AND (`id`='3');
UPDATE `locales_creature_text` SET `entry`='23842', `groupid`='0', `id`='4', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Al capitán no le va a gustar esto.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23842') AND (`groupid`='0') AND (`id`='4');
UPDATE `locales_creature_text` SET `entry`='23842', `groupid`='0', `id`='5', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Guau.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23842') AND (`groupid`='0') AND (`id`='5');
UPDATE `locales_creature_text` SET `entry`='23842', `groupid`='1', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='No sabía que podían hacer eso.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23842') AND (`groupid`='1') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='23842', `groupid`='1', `id`='1', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Esto es... especial.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23842') AND (`groupid`='1') AND (`id`='1');
UPDATE `locales_creature_text` SET `entry`='23842', `groupid`='1', `id`='2', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Que divertido!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23842') AND (`groupid`='1') AND (`id`='2');
UPDATE `locales_creature_text` SET `entry`='23842', `groupid`='1', `id`='3', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¿Esta es la nueva peste Renegada?', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23842') AND (`groupid`='1') AND (`id`='3');
UPDATE `locales_creature_text` SET `entry`='23842', `groupid`='1', `id`='4', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¿Qué clase de enfermo eres?', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23842') AND (`groupid`='1') AND (`id`='4');
UPDATE `locales_creature_text` SET `entry`='23842', `groupid`='1', `id`='5', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Oh, dios!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23842') AND (`groupid`='1') AND (`id`='5');
UPDATE `locales_creature_text` SET `entry`='23842', `groupid`='1', `id`='6', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Me siento mal.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23842') AND (`groupid`='1') AND (`id`='6');
UPDATE `locales_creature_text` SET `entry`='23842', `groupid`='1', `id`='7', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Esto NO debería haber pasado.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23842') AND (`groupid`='1') AND (`id`='7');
UPDATE `locales_creature_text` SET `entry`='23844', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¿Se encuentra bien?', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23844') AND (`groupid`='0') AND (`id`='0');

-- Zelfrax --
UPDATE `locales_creature_text` SET `entry`='23864', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Esta tierra era mía mucho antes de que tu miserable especie pusiera los pies aquí.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23864') AND (`groupid`='0') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='23864', `groupid`='1', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Todos los que se aventuran aquí me pertenecen, ¡incluso tú!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23864') AND (`groupid`='1') AND (`id`='0');

-- Mayor Molina --
UPDATE `locales_creature_text` SET `entry`='23905', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Tiradores, formad y tomad posiciones!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23905') AND (`groupid`='0') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='23905', `groupid`='1', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Preparaos para disparar a mi orden! Apuntad al objetivo...', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23905') AND (`groupid`='1') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='23905', `groupid`='2', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡FUEGO A DISCRECIÓN!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23905') AND (`groupid`='2') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='23905', `groupid`='3', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Lo hemos conseguido! ¡Hemos acabado con Tethyr!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23905') AND (`groupid`='3') AND (`id`='0');

-- Sargento Lorric --
UPDATE `locales_creature_text` SET `entry`='23963', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Fuego!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23963') AND (`groupid`='0') AND (`id`='0');

-- Expedicionario perturbado --
UPDATE `locales_creature_text` SET `entry`='23967', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Todo terminará pronto. ¡Pronto sentirás el abrazo del Que No Debe Ser Nombrado!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23967') AND (`groupid`='0') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='23967', `groupid`='0', `id`='1', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Si estás aquí, entonces podría estar muy cerca!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23967') AND (`groupid`='0') AND (`id`='1');
UPDATE `locales_creature_text` SET `entry`='23967', `groupid`='0', `id`='2', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='La verdad os hará libres. ¡Como nosotros, estarás con él para siempre!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23967') AND (`groupid`='0') AND (`id`='2');
UPDATE `locales_creature_text` SET `entry`='23967', `groupid`='0', `id`='3', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='No puedes irte... ¡No debe encontrarnos!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23967') AND (`groupid`='0') AND (`id`='3');
UPDATE `locales_creature_text` SET `entry`='23967', `groupid`='0', `id`='4', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Todo terminará pronto. ¡Pronto sentirás el abrazo del Que No Debe Ser Nombrado!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23967') AND (`groupid`='0') AND (`id`='4');
UPDATE `locales_creature_text` SET `entry`='23967', `groupid`='0', `id`='5', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Ahora tendrás que unirte a nosotros... permanentemente!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23967') AND (`groupid`='0') AND (`id`='5');
UPDATE `locales_creature_text` SET `entry`='23967', `groupid`='0', `id`='6', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Ahora tendrás que unirte a nosotros... permanentemente!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23967') AND (`groupid`='0') AND (`id`='6');
UPDATE `locales_creature_text` SET `entry`='23967', `groupid`='0', `id`='7', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Ja ja ja ja! ¡Debo encontrar los secretos!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23967') AND (`groupid`='0') AND (`id`='7');
UPDATE `locales_creature_text` SET `entry`='23967', `groupid`='0', `id`='8', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Perdóname, oh, grande. ¡No quise decir aprender la verdad!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23967') AND (`groupid`='0') AND (`id`='8');
UPDATE `locales_creature_text` SET `entry`='23967', `groupid`='0', `id`='9', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Si sólo hubiera más tiempo!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23967') AND (`groupid`='0') AND (`id`='9');
UPDATE `locales_creature_text` SET `entry`='23967', `groupid`='0', `id`='10', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Está viniendo! ¡ESCÓNDETE!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23967') AND (`groupid`='0') AND (`id`='10');
UPDATE `locales_creature_text` SET `entry`='23967', `groupid`='0', `id`='11', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡El final está cerca! ¡Lo Que No Debe Ser Nombrado ya está aquí casi!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23967') AND (`groupid`='0') AND (`id`='11');
UPDATE `locales_creature_text` SET `entry`='23967', `groupid`='0', `id`='12', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Estamos a salvo; ¡nunca podrá llegar hasta aquí!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23967') AND (`groupid`='0') AND (`id`='12');
UPDATE `locales_creature_text` SET `entry`='23967', `groupid`='0', `id`='13', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Cuando uno estudia y cava, uno revela la verdad.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23967') AND (`groupid`='0') AND (`id`='13');
UPDATE `locales_creature_text` SET `entry`='23967', `groupid`='0', `id`='14', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Pondré fin a tu vida antes de que te des cuenta de la horrible verdad!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23967') AND (`groupid`='0') AND (`id`='14');
UPDATE `locales_creature_text` SET `entry`='23967', `groupid`='0', `id`='15', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Intruso! ¡Fuiste enviado para acabar con nosotros!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='23967') AND (`groupid`='0') AND (`id`='15');

-- Drak'aguul --
UPDATE `locales_creature_text` SET `entry`='26919', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Ser más fuertes de lo que pensaba, ¡atacadlos!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='26919') AND (`groupid`='0') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='26919', `groupid`='1', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Espera mis órdenes, yo encargar de esto!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='26919') AND (`groupid`='1') AND (`id`='0');

-- Alexstrasza la Protectora --
UPDATE `locales_creature_text` SET `entry`='26917', `groupid`='2', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Si estuviera en mi forma de dragón no habría espacio para nadie más, $gpequeño:pequeña;.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='26917') AND (`groupid`='2') AND (`id`='0');

-- Sobrestante Durval --
UPDATE `locales_creature_text` SET `entry`='26920', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Pagarás por esto!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='26920') AND (`groupid`='0') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='26920', `groupid`='0', `id`='1', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Necio! ¡Nunca saldrás con esto!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='26920') AND (`groupid`='0') AND (`id`='1');
UPDATE `locales_creature_text` SET `entry`='26920', `groupid`='0', `id`='2', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¿Te atreves a desafiar a los hijos de hierro?', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='26920') AND (`groupid`='0') AND (`id`='2');
UPDATE `locales_creature_text` SET `entry`='26920', `groupid`='0', `id`='3', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¿Qué crees que estás haciendo?', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='26920') AND (`groupid`='0') AND (`id`='3');

-- Sobrestante Korgan --
UPDATE `locales_creature_text` SET `entry`='26921', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Pagarás por esto!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='26921') AND (`groupid`='0') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='26921', `groupid`='0', `id`='1', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Necio! ¡Nunca saldrás con esto!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='26921') AND (`groupid`='0') AND (`id`='1');
UPDATE `locales_creature_text` SET `entry`='26921', `groupid`='0', `id`='2', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¿Te atreves a desafiar a los hijos de hierro?', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='26921') AND (`groupid`='0') AND (`id`='2');
UPDATE `locales_creature_text` SET `entry`='26921', `groupid`='0', `id`='3', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¿Qué crees que estás haciendo?', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='26921') AND (`groupid`='0') AND (`id`='3');

-- Sobrestante Lochli --
UPDATE `locales_creature_text` SET `entry`='26922', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Pagarás por esto!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='26922') AND (`groupid`='0') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='26922', `groupid`='0', `id`='1', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Necio! ¡Nunca saldrás con esto!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='26922') AND (`groupid`='0') AND (`id`='1');
UPDATE `locales_creature_text` SET `entry`='26922', `groupid`='0', `id`='2', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¿Te atreves a desafiar a los hijos de hierro?', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='26922') AND (`groupid`='0') AND (`id`='2');
UPDATE `locales_creature_text` SET `entry`='26922', `groupid`='0', `id`='3', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¿Qué crees que estás haciendo?', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='26922') AND (`groupid`='0') AND (`id`='3');

-- Sobrestante Brunon --
UPDATE `locales_creature_text` SET `entry`='26923', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Pagarás por esto!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='26923') AND (`groupid`='0') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='26923', `groupid`='0', `id`='1', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Necio! ¡Nunca saldrás con esto!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='26923') AND (`groupid`='0') AND (`id`='1');
UPDATE `locales_creature_text` SET `entry`='26923', `groupid`='0', `id`='2', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¿Te atreves a desafiar a los hijos de hierro?', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='26923') AND (`groupid`='0') AND (`id`='2');
UPDATE `locales_creature_text` SET `entry`='26923', `groupid`='0', `id`='3', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¿Qué crees que estás haciendo?', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='26923') AND (`groupid`='0') AND (`id`='3');

-- Sasha --
UPDATE `locales_creature_text` SET `entry`='26935', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Soy lo suficientemente mayor como para disparar a bestias como tú justo entre los ojos... al doble de distancia.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='26935') AND (`groupid`='0') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='26935', `groupid`='1', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='No te atrevas a hablar de mi padre, monstruo. Era el doble de hombre que jamás serás.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='26935') AND (`groupid`='1') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='26935', `groupid`='2', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Prefiero estar muerta que ser una de vosotros! ¿Creéis que seguís siendo humanos? ¡Sois... animales!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='26935') AND (`groupid`='2') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='26935', `groupid`='3', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Sorpresa, escoria! Vas a decirme dónde está mi hermana o descargaré un cartucho de balas de veraplata en el corazón de tu esposa.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='26935') AND (`groupid`='3') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='26935', `groupid`='4', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¿Dónde está Anya?', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='26935') AND (`groupid`='4') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='26935', `groupid`='5', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Una última cosa: necesito saber dónde está Arugal.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='26935') AND (`groupid`='5') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='26935', `groupid`='6', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Anya! ¡Estás bien!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='26935') AND (`groupid`='6') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='26935', `groupid`='7', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¿Mala luna? ¿No querrás decir Luna de sangre?', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='26935') AND (`groupid`='7') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='26935', `groupid`='8', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='No te preocupes, hermana... nadie puede hacerte daño ahora.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='26935') AND (`groupid`='8') AND (`id`='0');

-- Anatoly --
UPDATE `locales_creature_text` SET `entry`='26971', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¿Qué edad tienes, muchacha?', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='26971') AND (`groupid`='0') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='26971', `groupid`='1', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='No te saldrás con la tuya, ¿lo sabes? Eres un niña.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='26971') AND (`groupid`='1') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='26971', `groupid`='2', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Tu padre era débil, Sasha... no tenía las agallas para hacer lo que tenía que hacer.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='26971') AND (`groupid`='2') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='26971', `groupid`='3', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Todos terminaremos sirviendo al Rey Exánime, chica. Mejor así que convertirse en un cadáver podrido.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='26971') AND (`groupid`='3') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='26971', `groupid`='4', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Detente! ¡No dispares! ¡No hagas daño a Tatjana!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='26971') AND (`groupid`='4') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='26971', `groupid`='5', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='La mocosa estava presa en la guarida de lobo al otro lado de la montaña. Ella debía ser llevada a Arugal. ¿Podemos irnos ahora?', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='26971') AND (`groupid`='5') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='26971', `groupid`='6', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Perdóname, Tatjana...', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='26971') AND (`groupid`='6') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='26971', `groupid`='7', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Nada de lo que puedas hacer se puede comparar con lo que Arugal puede hacer con nosotros! ¡Yo mismo te desgarraré!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='26971') AND (`groupid`='7') AND (`id`='0');

-- Grom'thar el Portador del Trueno --
UPDATE `locales_creature_text` SET `entry`='27002', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Consumiré tu carne y me hurgaré los dientes con tus huesos!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27002') AND (`groupid`='0') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='27002', `groupid`='1', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡No eres un magnatauro! ¿Dónde... obtuviste... tal fuerza?', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27002') AND (`groupid`='1') AND (`id`='0');

-- Gólem de guerra mermado --
UPDATE `locales_creature_text` SET `entry`='27017', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Iniciando la recolección de energía.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27017') AND (`groupid`='0') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='27017', `groupid`='1', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Recolección de energía completada.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27017') AND (`groupid`='1') AND (`id`='0');

-- Comerciante de pellejos Jun'ik --
UPDATE `locales_creature_text` SET `entry`='27037', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡No, por favor! ¡No lo hagas!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27037') AND (`groupid`='0') AND (`id`='0');

-- Trituradora de Xink --
UPDATE `locales_creature_text` SET `entry`='27061', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Trituradora de Xink preparada y disponible para la destrucción del bosque.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27061') AND (`groupid`='0') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='27061', `groupid`='1', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Funciones de seguridad de la Trituradora de Xink activadas. Volviendo a la base.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27061') AND (`groupid`='1') AND (`id`='0');

-- Gorgonna --
UPDATE `locales_creature_text` SET `entry`='27102', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Deja que me encargue, hermana.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27102') AND (`groupid`='0') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='27102', `groupid`='1', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¿En qué estabas pensando, provocándola así?', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27102') AND (`groupid`='1') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='27102', `groupid`='2', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='He demostrado buen juicio cuando tú no. ¡No quiero ver como nos llevas a la ruina, Krenna!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27102') AND (`groupid`='2') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='27102', `groupid`='3', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Ya lo veremos.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27102') AND (`groupid`='3') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='27102', `groupid`='4', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Tú... idiota! Realmente lo has hecho esta vez. Voy a tener que hacer que parezca que tu pierna está rota.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27102') AND (`groupid`='4') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='27102', `groupid`='5', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Ahora no te muevas si realmente quieres volver a caminar de nuevo!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27102') AND (`groupid`='5') AND (`id`='0');

-- Ingeniero de asedio de la Séptima Legión --

UPDATE `locales_creature_text` SET `entry`='27163', `groupid`='0', `id`='1', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Mantenlos lejos de mí durante unos 15 segundos y esta cosa estará prácticamente muerta.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27163') AND (`groupid`='0') AND (`id`='1');
UPDATE `locales_creature_text` SET `entry`='27163', `groupid`='0', `id`='2', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Cúbreme!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27163') AND (`groupid`='0') AND (`id`='2');
UPDATE `locales_creature_text` SET `entry`='27163', `groupid`='0', `id`='3', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Cuando haya terminado con este carro de la Plaga se verá como si un duende lo hubiera construido! ¡Mantenme a salvo!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27163') AND (`groupid`='0') AND (`id`='3');
UPDATE `locales_creature_text` SET `entry`='27163', `groupid`='0', `id`='4', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Quítame a los malos de encima!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27163') AND (`groupid`='0') AND (`id`='4');
UPDATE `locales_creature_text` SET `entry`='27163', `groupid`='1', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='%s hábilmente monta una máquina extraña.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27163') AND (`groupid`='1') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='27163', `groupid`='2', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Eso es lo que debes hacer! Sólo unos segundos más.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27163') AND (`groupid`='2') AND (`id`='0');

-- Señor de la guerra Jin'arrak --
UPDATE `locales_creature_text` SET `entry`='27199', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Ahhhh! ¿Que me está pasando, colega?', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27199') AND (`groupid`='0') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='27199', `groupid`='1', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Finalmente, una ofrenda digna!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27199') AND (`groupid`='1') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='27199', `groupid`='2', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Cómo te atreves a invocarme sin una ofrenda!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27199') AND (`groupid`='2') AND (`id`='0');

-- Sacerdote cuervo del Embate --
UPDATE `locales_creature_text` SET `entry`='27202', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Abbendis te verá purgado!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27202') AND (`groupid`='0') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='27202', `groupid`='0', `id`='1', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Eres impuro!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27202') AND (`groupid`='0') AND (`id`='1');
UPDATE `locales_creature_text` SET `entry`='27202', `groupid`='0', `id`='2', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Eh, ¿qué estás haciendo?', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27202') AND (`groupid`='0') AND (`id`='2');
UPDATE `locales_creature_text` SET `entry`='27202', `groupid`='1', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Siento la corrupción de esta tierra en ti, lacayo. Informa al Obispo antes de seguir adelante.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27202') AND (`groupid`='1') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='27202', `groupid`='1', `id`='1', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Tu protección es fuerte, $gchico:chica;. Continúa tu trabajo.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27202') AND (`groupid`='1') AND (`id`='1');
UPDATE `locales_creature_text` SET `entry`='27202', `groupid`='1', `id`='2', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='El Gran Almirante ha venido a velar por nuestra dedicación. Si te veo vagueando de nuevo en tu puesto de trabajo, te destriparé yo mismo.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27202') AND (`groupid`='1') AND (`id`='2');
UPDATE `locales_creature_text` SET `entry`='27202', `groupid`='1', `id`='3', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Necesitas la bendición del Obispo. Ve a verlo pronto.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27202') AND (`groupid`='1') AND (`id`='3');
UPDATE `locales_creature_text` SET `entry`='27202', `groupid`='2', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡AYUDA! ¡AYUDA! ¡$gESTE HOMBRE:ESTA MUJER; HA ROBADO MI IMAGEN!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27202') AND (`groupid`='2') AND (`id`='0');

-- Lacayo del Embate --
UPDATE `locales_creature_text` SET `entry`='27203', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Se purificado por el acero!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27203') AND (`groupid`='0') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='27203', `groupid`='0', `id`='1', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Por la Luz!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27203') AND (`groupid`='0') AND (`id`='1');
UPDATE `locales_creature_text` SET `entry`='27203', `groupid`='0', `id`='2', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡En el nombre de la Luz!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27203') AND (`groupid`='0') AND (`id`='2');
UPDATE `locales_creature_text` SET `entry`='27203', `groupid`='0', `id`='3', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Vas a ser limpiado!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27203') AND (`groupid`='0') AND (`id`='3');

-- Torturador LeCraft --
UPDATE `locales_creature_text` SET `entry`='27209', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¿Vienes a jugar?', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27209') AND (`groupid`='0') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='27209', `groupid`='1', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Ay! ¡No te diré NADA, $gasqueroso:asquerosa; $r!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27209') AND (`groupid`='1') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='27209', `groupid`='2', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Espera... ESPERA! ¡¿Que es lo que quieres saber?! Sé que eres $gel:la; $c $gllamado:llamada; $N.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27209') AND (`groupid`='2') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='27209', `groupid`='3', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡AH... NO! ¡Sabemos que has estado robando nuestras armadura, armas y caballos!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27209') AND (`groupid`='3') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='27209', `groupid`='4', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Sabemos... que tú no sabes... por qué somos inmunes... a la supuesta plaga. El Gran almirante Viento Oeste de alguna manera le concedió al sumo abad esa súplica. Te lo ruego... no más... ¡¿por favor?!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27209') AND (`groupid`='4') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='27209', `groupid`='5', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡AHHHHHHHHH! ¡Por favor... sabemos... que tienes... un espía... disfrazado de... uno de nosotros! Allí... eso es todo lo que sé. Por favor... compasión... ¡PARAD!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27209') AND (`groupid`='5') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='27209', `groupid`='6', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Por favor... ya basta. Haré... lo que sea...', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27209') AND (`groupid`='6') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='27209', `groupid`='7', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Te lo suplico... no más.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27209') AND (`groupid`='7') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='27209', `groupid`='8', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡AHHHHHHHHH!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27209') AND (`groupid`='8') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='27209', `groupid`='9', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡No obtendrás... nada más... de mí!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27209') AND (`groupid`='9') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='27209', `groupid`='10', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Todos ellos... suplicaron... por sus... vidas!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27209') AND (`groupid`='10') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='27209', `groupid`='11', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='TE LO HE DICHO... ¡No sé... nada... más!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27209') AND (`groupid`='11') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='27209', `groupid`='12', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Tan solo... acaba con esto.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27209') AND (`groupid`='12') AND (`id`='0');

-- Alta general Abbendis --
UPDATE `locales_creature_text` SET `entry`='27210', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Ahora te mostraré el verdadero poder del Embate!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27210') AND (`groupid`='0') AND (`id`='0');

-- Imagen de Loken --
UPDATE `locales_creature_text` SET `entry`='27212', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Llegas tarde, supervisor.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27212') AND (`groupid`='0') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='27212', `groupid`='1', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='El destino no esperará. Tus artesanos deben aumentar su producción de gólems de guerra antes de que el líder gigante de piedra y su ejército alcancen Ulduar.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27212') AND (`groupid`='1') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='27212', `groupid`='2', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Diles a tus Runaférrea que sigan convirtiendo todos los gigantes de piedra que puedan. Los que no se sometan deben ser destruidos.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27212') AND (`groupid`='2') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='27212', `groupid`='3', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Si los gigantes de piedra interfieren en nuestro trabajo en Ulduar, te haré totalmente responsable de la situación. No se debe permitir que los mortales acudan en ayuda de los gigantes.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27212') AND (`groupid`='3') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='27212', `groupid`='4', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Vuelve a tus obligaciones, supervisor. Asegúrate de informar a tus trabajadores de la urgencia de sus tareas.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='27212') AND (`groupid`='4') AND (`id`='0');

-- Linda Ann Kastingbrillo --
UPDATE `locales_creature_text` SET `entry`='32687', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Ahí va $gel mejor:la mejor; $c que tengo el honor de conocer.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='32687') AND (`groupid`='0') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='32687', `groupid`='0', `id`='1', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Eres toda una inspiración, $N.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='32687') AND (`groupid`='0') AND (`id`='1');
UPDATE `locales_creature_text` SET `entry`='32687', `groupid`='0', `id`='2', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Eres un ejemplo perfecto de $ghombre:mujer;, $N.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='32687') AND (`groupid`='0') AND (`id`='2');
UPDATE `locales_creature_text` SET `entry`='32687', `groupid`='0', `id`='3', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='No podrías preguntar por alguien mejor que $N, de verdad.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='32687') AND (`groupid`='0') AND (`id`='3');
UPDATE `locales_creature_text` SET `entry`='32687', `groupid`='0', `id`='4', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Es maravilloso verte de nuevo, $N. Maravilloso.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='32687') AND (`groupid`='0') AND (`id`='4');
UPDATE `locales_creature_text` SET `entry`='32687', `groupid`='0', `id`='5', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡$N! ¡Es bueno verte de nuevo por aquí! ¿Tan $gliado:liada; como siempre, eh?', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='32687') AND (`groupid`='0') AND (`id`='5');
-- Arcanista Alec --
UPDATE `locales_creature_text` SET `entry`='32692', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Ahí va $gel mejor:la mejor; $c que tengo el honor de conocer.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='32692') AND (`groupid`='0') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='32692', `groupid`='0', `id`='1', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Eres toda una inspiración, $N.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='32692') AND (`groupid`='0') AND (`id`='1');
UPDATE `locales_creature_text` SET `entry`='32692', `groupid`='0', `id`='2', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Eres un ejemplo perfecto de $ghombre:mujer;, $N.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='32692') AND (`groupid`='0') AND (`id`='2');
UPDATE `locales_creature_text` SET `entry`='32692', `groupid`='0', `id`='3', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='No podrías preguntar por alguien mejor que $N, de verdad.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='32692') AND (`groupid`='0') AND (`id`='3');
UPDATE `locales_creature_text` SET `entry`='32692', `groupid`='0', `id`='4', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Es maravilloso verte de nuevo, $N. Maravilloso.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='32692') AND (`groupid`='0') AND (`id`='4');
UPDATE `locales_creature_text` SET `entry`='32692', `groupid`='0', `id`='5', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡$N! ¡Es bueno verte de nuevo por aquí! ¿Tan $gliado:liada; como siempre, eh?', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='32692') AND (`groupid`='0') AND (`id`='5');

-- Mercaderes ambulantes --
UPDATE `locales_creature_text` SET `entry`='32638', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Hakmud no puede trabajar en estas condiciones! ¡Adios!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='32638') AND (`groupid`='0') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='32638', `groupid`='0', `id`='1', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Pensaba que éramos amigos, colega. ¿Dejas tirado a Hakmud?', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='32638') AND (`groupid`='0') AND (`id`='1');
UPDATE `locales_creature_text` SET `entry`='32638', `groupid`='0', `id`='2', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Gracias, colega! ¡Gracias por nada!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='32638') AND (`groupid`='0') AND (`id`='2');
UPDATE `locales_creature_text` SET `entry`='32638', `groupid`='0', `id`='3', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¿Qué se supone que tiene que hacer Hakmud ahora, colega?', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='32638') AND (`groupid`='0') AND (`id`='3');
UPDATE `locales_creature_text` SET `entry`='32638', `groupid`='0', `id`='4', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¿Por qué tratas a Hakmud así, colega?', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='32638') AND (`groupid`='0') AND (`id`='4');
UPDATE `locales_creature_text` SET `entry`='32639', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Adiós! ¡Fuiste el mejor amigo que Gnimo ha tenido nunca!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='32639') AND (`groupid`='0') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='32639', `groupid`='0', `id`='1', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Nadie quiere a Gnimo…', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='32639') AND (`groupid`='0') AND (`id`='1');
UPDATE `locales_creature_text` SET `entry`='32639', `groupid`='0', `id`='2', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Es hora de que Gnimo se desactive.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='32639') AND (`groupid`='0') AND (`id`='2');
UPDATE `locales_creature_text` SET `entry`='32641', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Nuestra amistad se ha ACABADO!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='32641') AND (`groupid`='0') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='32641', `groupid`='0', `id`='1', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Eh, sí… Siempre he querido que me dejen tirado en cualquier sitio.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='32641') AND (`groupid`='0') AND (`id`='1');
UPDATE `locales_creature_text` SET `entry`='32641', `groupid`='0', `id`='2', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Oh, ya veo cómo va… ¿Vas a hacerme eso a mí, no?', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='32641') AND (`groupid`='0') AND (`id`='2');
UPDATE `locales_creature_text` SET `entry`='32641', `groupid`='0', `id`='3', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¿Me vas a dejar aquí? ¿Cómo se supone que voy a llegar a casa?', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='32641') AND (`groupid`='0') AND (`id`='3');
UPDATE `locales_creature_text` SET `entry`='32642', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¿De verdad, colega? ¿Dejar atrás a Mojodishu así, sin más?', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='32642') AND (`groupid`='0') AND (`id`='0');
UPDATE `locales_creature_text` SET `entry`='32642', `groupid`='0', `id`='1', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='Vaya mojo más malo que estar haciendo. No decir que Mojodishu no avisar.', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='32642') AND (`groupid`='0') AND (`id`='1');
UPDATE `locales_creature_text` SET `entry`='32642', `groupid`='0', `id`='2', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Así ser entonces!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='32642') AND (`groupid`='0') AND (`id`='2');
-- Illidan Tempestira --
UPDATE `locales_creature_text` SET `entry`='32588', `groupid`='0', `id`='0', `text_loc1`=NULL, `text_loc2`=NULL, `text_loc3`=NULL, `text_loc4`=NULL, `text_loc5`=NULL, `text_loc6`='¡Prepárate a morir!', `text_loc7`=NULL, `text_loc8`=NULL WHERE (`entry`='32588') AND (`groupid`='0') AND (`id`='0');
