
-- CONQUISTA DEL INVIERNO --

-- Textos generales del campo de batalla --
UPDATE `creature_text_locale` SET `CreatureID`='15214', `GroupID`='1', `ID`='0', `Locale`='esES', `text`='¡Han dañado la torre sur!' WHERE (`CreatureID`='15214') AND (`GroupID`='1') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='15214', `GroupID`='2', `ID`='0', `Locale`='esES', `text`='¡Han destruido la torre sur!' WHERE (`CreatureID`='15214') AND (`GroupID`='2') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='15214', `GroupID`='3', `ID`='0', `Locale`='esES', `text`='¡Han dañado la torre este!' WHERE (`CreatureID`='15214') AND (`GroupID`='3') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='15214', `GroupID`='4', `ID`='0', `Locale`='esES', `text`='¡Han destruido la torre este!' WHERE (`CreatureID`='15214') AND (`GroupID`='4') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='15214', `GroupID`='5', `ID`='0', `Locale`='esES', `text`='¡Han dañado la torre oeste!' WHERE (`CreatureID`='15214') AND (`GroupID`='5') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='15214', `GroupID`='6', `ID`='0', `Locale`='esES', `text`='¡Han destruido la torre oeste!' WHERE (`CreatureID`='15214') AND (`GroupID`='6') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='15214', `GroupID`='7', `ID`='0', `Locale`='esES', `text`='¡Han dañado la torre noroeste de la fortaleza!' WHERE (`CreatureID`='15214') AND (`GroupID`='7') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='15214', `GroupID`='8', `ID`='0', `Locale`='esES', `text`='¡Han destruido la torre noroeste de la fortaleza!' WHERE (`CreatureID`='15214') AND (`GroupID`='8') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='15214', `GroupID`='9', `ID`='0', `Locale`='esES', `text`='¡Han dañado la torre sudeste de la fortaleza!' WHERE (`CreatureID`='15214') AND (`GroupID`='9') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='15214', `GroupID`='10', `ID`='0', `Locale`='esES', `text`='¡Han destruido la torre sudeste de la fortaleza!' WHERE (`CreatureID`='15214') AND (`GroupID`='10') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='15214', `GroupID`='11', `ID`='0', `Locale`='esES', `text`='¡La Alianza ha atacado el Taller de Asedio del Templo Quebrado!' WHERE (`CreatureID`='15214') AND (`GroupID`='11') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='15214', `GroupID`='12', `ID`='0', `Locale`='esES', `text`='¡El Taller de Asedio del Templo Quebrado ha sido tomado por la Alianza!' WHERE (`CreatureID`='15214') AND (`GroupID`='12') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='15214', `GroupID`='13', `ID`='0', `Locale`='esES', `text`='¡La Horda ha atacado el Taller de Asedio del Templo Quebrado!' WHERE (`CreatureID`='15214') AND (`GroupID`='13') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='15214', `GroupID`='14', `ID`='0', `Locale`='esES', `text`='¡El Taller de Asedio del Templo Quebrado ha sido tomado por la Horda!' WHERE (`CreatureID`='15214') AND (`GroupID`='14') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='15214', `GroupID`='15', `ID`='0', `Locale`='esES', `text`='¡La Alianza ha atacado el Taller de Asedio Chispa Oriental!' WHERE (`CreatureID`='15214') AND (`GroupID`='15') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='15214', `GroupID`='16', `ID`='0', `Locale`='esES', `text`='¡El Taller de Asedio Chispa Oriental ha sido capturado por la Alianza!' WHERE (`CreatureID`='15214') AND (`GroupID`='16') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='15214', `GroupID`='17', `ID`='0', `Locale`='esES', `text`='¡La Horda ha atacado el Taller de Asedio Chispa Oriental!' WHERE (`CreatureID`='15214') AND (`GroupID`='17') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='15214', `GroupID`='18', `ID`='0', `Locale`='esES', `text`='¡El Taller de Asedio Chispa Oriental ha sido capturado por la Horda!' WHERE (`CreatureID`='15214') AND (`GroupID`='18') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='15214', `GroupID`='19', `ID`='0', `Locale`='esES', `text`='¡La Alianza ha atacado el Taller de Asedio del Anillo Sumergido!' WHERE (`CreatureID`='15214') AND (`GroupID`='19') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='15214', `GroupID`='20', `ID`='0', `Locale`='esES', `text`='¡El Taller de Asedio del Anillo Sumergido ha sido tomado por la Alianza!' WHERE (`CreatureID`='15214') AND (`GroupID`='20') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='15214', `GroupID`='21', `ID`='0', `Locale`='esES', `text`='¡La Horda ha atacado el Taller de Asedio del Anillo Sumergido!' WHERE (`CreatureID`='15214') AND (`GroupID`='21') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='15214', `GroupID`='22', `ID`='0', `Locale`='esES', `text`='¡El Taller de Asedio del Anillo Sumergido ha sido tomado por la Horda!' WHERE (`CreatureID`='15214') AND (`GroupID`='22') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='15214', `GroupID`='23', `ID`='0', `Locale`='esES', `text`='¡La Alianza ha atacado el Taller de Asedio Chispa Occidental!' WHERE (`CreatureID`='15214') AND (`GroupID`='23') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='15214', `GroupID`='24', `ID`='0', `Locale`='esES', `text`='¡El Taller de Asedio Chispa Occidental ha sido capturado por la Alianza!' WHERE (`CreatureID`='15214') AND (`GroupID`='24') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='15214', `GroupID`='25', `ID`='0', `Locale`='esES', `text`='¡La Horda ha atacado el Taller de Asedio Chispa Occidental!' WHERE (`CreatureID`='15214') AND (`GroupID`='25') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='15214', `GroupID`='26', `ID`='0', `Locale`='esES', `text`='¡El Taller de Asedio Chispa Occidental ha sido capturado por la Horda!' WHERE (`CreatureID`='15214') AND (`GroupID`='26') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='15214', `GroupID`='27', `ID`='0', `Locale`='esES', `text`='¡La batalla por el Lago Conquista del Invierno está a punto de comenzar!' WHERE (`CreatureID`='15214') AND (`GroupID`='27') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='15214', `GroupID`='28', `ID`='0', `Locale`='esES', `text`='¡Que comience la batalla!' WHERE (`CreatureID`='15214') AND (`GroupID`='28') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='15214', `GroupID`='29', `ID`='0', `Locale`='esES', `text`='¡La Alianza ha defendido la Fortaleza de Conquista del Invierno!' WHERE (`CreatureID`='15214') AND (`GroupID`='29') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='15214', `GroupID`='30', `ID`='0', `Locale`='esES', `text`='¡La Alianza ha tomado la Fortaleza de Conquista del Invierno!' WHERE (`CreatureID`='15214') AND (`GroupID`='30') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='15214', `GroupID`='31', `ID`='0', `Locale`='esES', `text`='¡La Horda ha defendido la Fortaleza de Conquista del Invierno!' WHERE (`CreatureID`='15214') AND (`GroupID`='31') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='15214', `GroupID`='32', `ID`='0', `Locale`='esES', `text`='¡La Horda ha tomado la Fortaleza de Conquista del Invierno!' WHERE (`CreatureID`='15214') AND (`GroupID`='32') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='15214', `GroupID`='33', `ID`='0', `Locale`='esES', `text`='¡Han dañado la torre noreste de la fortaleza!' WHERE (`CreatureID`='15214') AND (`GroupID`='33') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='15214', `GroupID`='34', `ID`='0', `Locale`='esES', `text`='¡Han destruido la torre noreste de la fortaleza!' WHERE (`CreatureID`='15214') AND (`GroupID`='34') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='15214', `GroupID`='35', `ID`='0', `Locale`='esES', `text`='¡Han dañado la torre sudoeste de la fortaleza!' WHERE (`CreatureID`='15214') AND (`GroupID`='35') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='15214', `GroupID`='36', `ID`='0', `Locale`='esES', `text`='¡Han destruido la torre sudoeste de la fortaleza!' WHERE (`CreatureID`='15214') AND (`GroupID`='36') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='15214', `GroupID`='37', `ID`='0', `Locale`='esES', `text`='Has alcanzado el Rango 1: Cabo' WHERE (`CreatureID`='15214') AND (`GroupID`='37') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='15214', `GroupID`='38', `ID`='0', `Locale`='esES', `text`='Has alcanzado el Rango 2: Teniente primero' WHERE (`CreatureID`='15214') AND (`GroupID`='38') AND (`ID`='0');

-- Comandante Dardosh --
UPDATE `creature_text_locale` SET `CreatureID`='31091', `GroupID`='0', `ID`='0', `Locale`='esES', `text`='¡La primera de las torres de la Alianza ha caído! ¡Destruid las tres y aceleraremos su retirada!' WHERE (`CreatureID`='31091') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='31091', `GroupID`='1', `ID`='0', `Locale`='esES', `text`='¡Lok\'tar! ¡La segunda torre ha caído! ¡Destruid la torre restante y aceleraremos su retirada!' WHERE (`CreatureID`='31091') AND (`GroupID`='1') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='31091', `GroupID`='2', `ID`='0', `Locale`='esES', `text`='¡Las torres de la Alianza han caído! No les hemos dado tregua. ¡Acabad con lo que quede de su ejército!' WHERE (`CreatureID`='31091') AND (`GroupID`='2') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='31091', `GroupID`='3', `ID`='0', `Locale`='esES', `text`='¡No muestres piedad, $N!' WHERE (`CreatureID`='31091') AND (`GroupID`='3') AND (`ID`='0');

-- Comandante Zanneth --
UPDATE `creature_text_locale` SET `CreatureID`='31036', `GroupID`='0', `ID`='0', `Locale`='esES', `text`='¡La primera de las torres de la Horda ha caído! ¡Destruid las tres y aceleraremos su retirada!' WHERE (`CreatureID`='31036') AND (`GroupID`='0') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='31036', `GroupID`='1', `ID`='0', `Locale`='esES', `text`='¡La segunda torre ha caído! ¡Destruid la torre restante y aceleraremos su retirada!' WHERE (`CreatureID`='31036') AND (`GroupID`='1') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='31036', `GroupID`='2', `ID`='0', `Locale`='esES', `text`='¡Las torres de la Horda han caído! No les hemos dado tregua. ¡Acabad con lo que quede de su ejército!' WHERE (`CreatureID`='31036') AND (`GroupID`='2') AND (`ID`='0');
UPDATE `creature_text_locale` SET `CreatureID`='31036', `GroupID`='3', `ID`='0', `Locale`='esES', `text`='¡No muestres piedad, $N!' WHERE (`CreatureID`='31036') AND (`GroupID`='3') AND (`ID`='0');